"""update

Revision ID: 4d2dceba3ed9
Revises: c80eea27f721
Create Date: 2025-01-25 10:13:56.041783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d2dceba3ed9'
down_revision: Union[str, None] = 'c80eea27f721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('model_provider', sa.String(length=255), nullable=False))
    op.add_column('knowledge_documents', sa.Column('separators', sa.JSON(), nullable=True))
    op.drop_index('ix_llm_model_name', table_name='llm_model')
    op.create_index(op.f('ix_llm_model_name'), 'llm_model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_model_name'), table_name='llm_model')
    op.create_index('ix_llm_model_name', 'llm_model', ['name'], unique=False)
    op.drop_column('knowledge_documents', 'separators')
    op.drop_column('knowledge_bases', 'model_provider')
    op.drop_column('knowledge_bases', 'model_id')
    op.create_table('kb_documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kb_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_content', mysql.TEXT(), nullable=True),
    sa.Column('vector_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name='kb_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_kb_documents_id', 'kb_documents', ['id'], unique=False)
    # ### end Alembic commands ###
