import type { AgentTemplate, AgentTemplateCategorySection } from './types';

const OFFICIAL_PROMPTS = {
  enterpriseAssistant: {
    'en-US': '3db60d44-f6a7-4892-8e65-9b7f95f69ab1',
    'zh-Hans': '9fa2ec04-0672-4e4f-9af6-ac4630f542ff',
  },
  supportTriage: {
    'en-US': 'c2b3cc59-36f7-4401-9e0f-c775c478a0f3',
    'zh-Hans': 'ca975ea8-8105-40d0-a9fd-b5865280f906',
  },
  customerSupportReply: {
    'en-US': '8e0ca70d-42b9-4727-8ab3-985886fc2a31',
    'zh-Hans': '09f473c0-39a0-49bb-bf77-5d7b2c0baee2',
  },
  meetingSummary: {
    'en-US': '14f4b8e4-92d3-494f-b61c-36419fc51f8a',
    'zh-Hans': '3756bb26-239b-4ad0-a056-bd4147cb6187',
  },
} as const;

export const TEMPLATE_CATEGORY_SECTIONS: AgentTemplateCategorySection[] = [
  {
    id: 'primary',
    categories: [{ id: 'recommended' }],
  },
  {
    id: 'complexity',
    labelKey: 'agents.templates.byComplexity',
    categories: [{ id: 'starter' }, { id: 'standard' }, { id: 'advanced' }, { id: 'enterprise' }],
  },
  {
    id: 'capability',
    labelKey: 'agents.templates.byCapabilities',
    categories: [
      { id: 'document-intake' },
      { id: 'knowledge-service' },
      { id: 'data-systems' },
      { id: 'integration-automation' },
      { id: 'governance' },
    ],
  },
];

function templateYaml(fileName: string): Pick<AgentTemplate, 'yamlPath' | 'localizedYamlPaths'> {
  const localizedYamlPaths = {
    'en-US': `/templates/agents/en-US/${fileName}`,
    'zh-Hans': `/templates/agents/zh-Hans/${fileName}`,
  } satisfies AgentTemplate['localizedYamlPaths'];

  return {
    yamlPath: localizedYamlPaths['en-US'],
    localizedYamlPaths,
  };
}

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'assistant-starter-chatflow',
    copyKey: 'assistantStarter',
    fallbackTitle: 'Enterprise Assistant Starter',
    fallbackDescription: 'A clean chatflow for policy answers, service guidance, and internal Q&A.',
    kind: 'chatflow',
    complexity: 'starter',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('assistant-starter-chatflow.yml'),
    recommended: true,
    categories: ['starter', 'knowledge-service'],
    tags: ['assistant', 'support', 'conversation'],
    iconLabel: 'EA',
    recommendedPrompts: [
      {
        promptIdsByLocale: OFFICIAL_PROMPTS.enterpriseAssistant,
        fallbackTitle: 'Enterprise Assistant Answer',
      },
    ],
    defaultPromptBindings: [
      {
        nodeIds: ['llm_node'],
        promptIdsByLocale: OFFICIAL_PROMPTS.enterpriseAssistant,
        fallbackTitle: 'Enterprise Assistant Answer',
      },
    ],
  },
  {
    id: 'support-triage-chatflow',
    copyKey: 'supportTriage',
    fallbackTitle: 'Service Request Triage',
    fallbackDescription: 'Classify an incoming request and route it to the right response path.',
    kind: 'chatflow',
    complexity: 'starter',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('support-triage-chatflow.yml'),
    recommended: true,
    categories: ['starter', 'knowledge-service', 'governance'],
    tags: ['triage', 'service', 'routing'],
    iconLabel: 'ST',
    recommendedPrompts: [
      {
        promptIdsByLocale: OFFICIAL_PROMPTS.supportTriage,
        fallbackTitle: 'Service Request Triage Classifier',
      },
    ],
    defaultPromptBindings: [
      {
        nodeIds: ['route_llm'],
        promptIdsByLocale: OFFICIAL_PROMPTS.supportTriage,
        fallbackTitle: 'Service Request Triage Classifier',
      },
    ],
  },
  {
    id: 'meeting-summary-chatflow',
    copyKey: 'meetingSummary',
    fallbackTitle: 'Meeting Decisions and Follow-ups',
    fallbackDescription: 'Turn meeting notes into decisions, owners, risks, and next actions.',
    kind: 'chatflow',
    complexity: 'starter',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('meeting-summary-chatflow.yml'),
    recommended: true,
    categories: ['starter', 'document-intake'],
    tags: ['meeting', 'summary', 'actions'],
    iconLabel: 'MS',
    recommendedPrompts: [
      {
        promptIdsByLocale: OFFICIAL_PROMPTS.meetingSummary,
        fallbackTitle: 'Meeting Summary Action Items',
      },
    ],
    defaultPromptBindings: [
      {
        nodeIds: ['llm_node'],
        promptIdsByLocale: OFFICIAL_PROMPTS.meetingSummary,
        fallbackTitle: 'Meeting Summary Action Items',
      },
    ],
  },
  {
    id: 'file-translation-chatflow',
    copyKey: 'fileTranslation',
    fallbackTitle: 'Controlled File Translation',
    fallbackDescription: 'Translate file content with terminology control and review notes.',
    kind: 'chatflow',
    complexity: 'starter',
    runtimeStatus: 'ready',
    requirements: ['default-model', 'file-input'],
    ...templateYaml('file-translation-chatflow.yml'),
    categories: ['starter', 'document-intake'],
    tags: ['translation', 'documents', 'language'],
    iconLabel: 'FT',
  },
  {
    id: 'knowledge-retrieval-chatflow',
    copyKey: 'knowledgeRetrieval',
    fallbackTitle: 'Knowledge Base Answering',
    fallbackDescription:
      'Retrieve enterprise knowledge, answer with citations, and flag missing context.',
    kind: 'chatflow',
    complexity: 'standard',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'knowledge-base'],
    ...templateYaml('knowledge-retrieval-chatflow.yml'),
    recommended: true,
    categories: ['standard', 'knowledge-service'],
    tags: ['knowledge', 'retrieval', 'citation'],
    iconLabel: 'KR',
  },
  {
    id: 'document-intake-summary-workflow',
    copyKey: 'documentIntakeSummary',
    fallbackTitle: 'Document Intake Summary',
    fallbackDescription:
      'Extract uploaded files, summarize key facts, and return a structured intake note.',
    kind: 'workflow',
    complexity: 'standard',
    runtimeStatus: 'ready',
    requirements: ['default-model', 'file-input'],
    ...templateYaml('document-intake-summary-workflow.yml'),
    recommended: true,
    categories: ['standard', 'document-intake'],
    tags: ['document', 'extractor', 'summary'],
    iconLabel: 'DI',
  },
  {
    id: 'structured-json-extractor-workflow',
    copyKey: 'structuredJsonExtractor',
    fallbackTitle: 'Structured JSON Extractor',
    fallbackDescription: 'Convert unstructured text into typed JSON for downstream systems.',
    kind: 'workflow',
    complexity: 'standard',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('structured-json-extractor-workflow.yml'),
    categories: ['standard', 'data-systems', 'document-intake'],
    tags: ['json', 'extract', 'structure'],
    iconLabel: 'JS',
  },
  {
    id: 'parameter-capture-workflow',
    copyKey: 'parameterCapture',
    fallbackTitle: 'Parameter Capture',
    fallbackDescription:
      'Extract business parameters from a request before executing the next step.',
    kind: 'workflow',
    complexity: 'standard',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('parameter-capture-workflow.yml'),
    categories: ['standard', 'data-systems'],
    tags: ['parameter', 'extractor', 'form'],
    iconLabel: 'PC',
  },
  {
    id: 'customer-signal-triage-workflow',
    copyKey: 'customerSignalTriage',
    fallbackTitle: 'Customer Signal Triage',
    fallbackDescription:
      'Classify customer feedback, detect urgency, and generate a response brief.',
    kind: 'workflow',
    complexity: 'standard',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('customer-signal-triage-workflow.yml'),
    recommended: true,
    categories: ['standard', 'knowledge-service', 'governance'],
    tags: ['customer', 'sentiment', 'priority'],
    iconLabel: 'CS',
    recommendedPrompts: [
      {
        promptIdsByLocale: OFFICIAL_PROMPTS.supportTriage,
        fallbackTitle: 'Service Request Triage Classifier',
      },
    ],
    defaultPromptBindings: [
      {
        nodeIds: ['triage_llm', 'classify_llm', 'route_llm'],
        promptIdsByLocale: OFFICIAL_PROMPTS.supportTriage,
        fallbackTitle: 'Service Request Triage Classifier',
      },
    ],
  },
  {
    id: 'text-polishing-workflow',
    copyKey: 'textPolishing',
    fallbackTitle: 'Business Writing Polish',
    fallbackDescription: 'Rewrite text for clarity, tone, grammar, and stakeholder readiness.',
    kind: 'workflow',
    complexity: 'standard',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('text-polishing-workflow.yml'),
    categories: ['standard', 'document-intake'],
    tags: ['writing', 'rewrite', 'polish'],
    iconLabel: 'BW',
  },
  {
    id: 'data-analysis-workflow',
    copyKey: 'dataAnalysis',
    fallbackTitle: 'Operational Data Analyst',
    fallbackDescription:
      'Analyze a dataset or report and return insights, risks, and recommendations.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('data-analysis-workflow.yml'),
    recommended: true,
    categories: ['advanced', 'data-systems'],
    tags: ['data', 'analysis', 'insights'],
    iconLabel: 'DA',
  },
  {
    id: 'sql-insight-analyst-workflow',
    copyKey: 'sqlInsightAnalyst',
    fallbackTitle: 'SQL Insight Analyst',
    fallbackDescription:
      'Generate SQL against an approved schema, query records, and summarize results.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'database'],
    ...templateYaml('sql-insight-analyst-workflow.yml'),
    categories: ['advanced', 'data-systems'],
    tags: ['sql', 'database', 'analysis'],
    iconLabel: 'SQL',
  },
  {
    id: 'api-enrichment-workflow',
    copyKey: 'apiEnrichment',
    fallbackTitle: 'API Enrichment Workflow',
    fallbackDescription:
      'Call an HTTP endpoint, parse the response, and produce an enriched brief.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'ready',
    requirements: ['default-model', 'http-endpoint'],
    ...templateYaml('api-enrichment-workflow.yml'),
    recommended: true,
    categories: ['advanced', 'integration-automation', 'data-systems'],
    tags: ['http', 'api', 'json'],
    iconLabel: 'API',
  },
  {
    id: 'batch-record-review-workflow',
    copyKey: 'batchRecordReview',
    fallbackTitle: 'Batch Record Review',
    fallbackDescription:
      'Iterate over records, review each item, and aggregate the final assessment.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('batch-record-review-workflow.yml'),
    categories: ['advanced', 'data-systems', 'integration-automation'],
    tags: ['iteration', 'batch', 'aggregate'],
    iconLabel: 'BR',
  },
  {
    id: 'code-data-transform-workflow',
    copyKey: 'codeDataTransform',
    fallbackTitle: 'Code Data Transform',
    fallbackDescription: 'Normalize raw JSON with a code step before producing a clean output.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'requires-setup',
    requirements: ['code-sandbox'],
    ...templateYaml('code-data-transform-workflow.yml'),
    categories: ['advanced', 'data-systems'],
    tags: ['code', 'transform', 'json'],
    iconLabel: 'CT',
  },
  {
    id: 'daily-operations-digest-workflow',
    copyKey: 'dailyOperationsDigest',
    fallbackTitle: 'Daily Operations Digest',
    fallbackDescription:
      'Use the current time and topic context to create an executive daily brief.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('daily-operations-digest-workflow.yml'),
    categories: ['advanced', 'integration-automation', 'knowledge-service'],
    tags: ['time', 'brief', 'operations'],
    iconLabel: 'OD',
  },
  {
    id: 'quality-review-loop-workflow',
    copyKey: 'qualityReviewLoop',
    fallbackTitle: 'Quality Review Loop',
    fallbackDescription:
      'Run a bounded review loop that refines an answer until quality criteria are met.',
    kind: 'workflow',
    complexity: 'advanced',
    runtimeStatus: 'ready',
    requirements: ['default-model'],
    ...templateYaml('quality-review-loop-workflow.yml'),
    categories: ['advanced', 'integration-automation', 'governance'],
    tags: ['loop', 'quality', 'review'],
    iconLabel: 'QL',
  },
  {
    id: 'approval-gated-review-workflow',
    copyKey: 'approvalGatedReview',
    fallbackTitle: 'Approval-gated Case Review',
    fallbackDescription:
      'Draft a case summary, request approval, and branch on the approver decision.',
    kind: 'workflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'approval-review'],
    ...templateYaml('approval-gated-review-workflow.yml'),
    recommended: true,
    categories: ['enterprise', 'governance'],
    tags: ['approval', 'human review', 'governance'],
    iconLabel: 'AR',
  },
  {
    id: 'scheduled-follow-up-workflow',
    copyKey: 'scheduledFollowUp',
    fallbackTitle: 'Scheduled Follow-up',
    fallbackDescription: 'Create a scheduled notification task from a workflow decision.',
    kind: 'workflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'scheduled-notification'],
    ...templateYaml('scheduled-follow-up-workflow.yml'),
    categories: ['enterprise', 'integration-automation', 'governance'],
    tags: ['schedule', 'notification', 'follow-up'],
    iconLabel: 'SF',
  },
  {
    id: 'sms-alert-routing-workflow',
    copyKey: 'smsAlertRouting',
    fallbackTitle: 'SMS Alert Routing',
    fallbackDescription: 'Evaluate alert severity and send an SMS notification for urgent cases.',
    kind: 'workflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['sms-channel'],
    ...templateYaml('sms-alert-routing-workflow.yml'),
    categories: ['enterprise', 'integration-automation', 'governance'],
    tags: ['sms', 'alert', 'routing'],
    iconLabel: 'SA',
  },
  {
    id: 'visual-asset-request-workflow',
    copyKey: 'visualAssetRequest',
    fallbackTitle: 'Visual Asset Request',
    fallbackDescription:
      'Turn a campaign or product request into an image-generation prompt and asset.',
    kind: 'workflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'image-model'],
    ...templateYaml('visual-asset-request-workflow.yml'),
    categories: ['enterprise', 'document-intake', 'integration-automation'],
    tags: ['image', 'generation', 'asset'],
    iconLabel: 'VA',
  },
  {
    id: 'risk-intelligence-ops-chatflow',
    copyKey: 'riskIntelligenceOps',
    fallbackTitle: 'Risk Intelligence Operations',
    fallbackDescription:
      'Route intake, extract entities, consult knowledge, update records, and advise next steps.',
    kind: 'chatflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'file-input', 'knowledge-base', 'database'],
    ...templateYaml('risk-intelligence-ops-chatflow.yml'),
    recommended: true,
    categories: ['enterprise', 'knowledge-service', 'data-systems', 'governance'],
    tags: ['risk', 'records', 'knowledge', 'database'],
    iconLabel: 'RI',
  },
  {
    id: 'learning-plan-orchestrator-chatflow',
    copyKey: 'learningPlanOrchestrator',
    fallbackTitle: 'Learning Plan Orchestrator',
    fallbackDescription:
      'Classify intent, extract tasks, estimate workload, persist plans, and track check-ins.',
    kind: 'chatflow',
    complexity: 'enterprise',
    runtimeStatus: 'requires-setup',
    requirements: ['default-model', 'database', 'code-sandbox'],
    ...templateYaml('learning-plan-orchestrator-chatflow.yml'),
    recommended: true,
    categories: ['enterprise', 'data-systems', 'integration-automation'],
    tags: ['planning', 'iteration', 'database', 'tracking'],
    iconLabel: 'LP',
  },
];

export function findTemplatesByPromptId(promptId: string): AgentTemplate[] {
  return AGENT_TEMPLATES.filter(template =>
    (template.recommendedPrompts || []).some(reference =>
      Object.values(reference.promptIdsByLocale).includes(promptId)
    )
  );
}
