package baseline

var IdentityAccessSchema = File{
	Name: "10_identity_access",
	Statements: []string{
		`CREATE TABLE public.account_contexts (
    account_id uuid NOT NULL,
    current_organization_id uuid,
    current_workspace_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.account_integrates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    account_id uuid NOT NULL,
    provider character varying(16) NOT NULL,
    open_id character varying(255) NOT NULL,
    encrypted_token character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.account_plugin_installations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    marketplace_plugin_id uuid NOT NULL,
    marketplace_version_id uuid NOT NULL,
    installed_by uuid NOT NULL,
    installed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) DEFAULT 'active'::character varying
);`,
		`COMMENT ON TABLE public.account_plugin_installations IS 'Tenant to plugin installation relationships';`,
		`COMMENT ON COLUMN public.account_plugin_installations.tenant_id IS 'Organization/Tenant ID where the plugin is installed';`,
		`COMMENT ON COLUMN public.account_plugin_installations.marketplace_plugin_id IS 'Marketplace plugin ID for redundancy and easy querying';`,
		`COMMENT ON COLUMN public.account_plugin_installations.marketplace_version_id IS 'Marketplace version ID - lookup declaration via plugin_declarations table';`,
		`COMMENT ON COLUMN public.account_plugin_installations.installed_by IS 'User ID who installed this plugin';`,
		`COMMENT ON COLUMN public.account_plugin_installations.status IS 'Installation status: active, disabled';`,
		`CREATE TABLE public.accounts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) DEFAULT ''::character varying NOT NULL,
    password character varying(255),
    password_salt character varying(255),
    avatar character varying(255),
    interface_language character varying(255),
    interface_theme character varying(255),
    timezone character varying(255),
    last_login_at timestamp with time zone,
    last_login_ip character varying(255),
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    initialized_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_active_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    extensions jsonb,
    mobile_e164 character varying(32),
    deleted_at timestamp with time zone,
    is_super_admin boolean DEFAULT false NOT NULL
);`,
		`CREATE TABLE public.department_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    department_id uuid NOT NULL,
    account_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.department_members IS 'Department member association table';`,
		`COMMENT ON COLUMN public.department_members.department_id IS 'Department ID';`,
		`COMMENT ON COLUMN public.department_members.account_id IS 'Account ID';`,
		`CREATE TABLE public.departments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id uuid NOT NULL,
    parent_id uuid,
    name character varying(255) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by uuid
);`,
		`COMMENT ON TABLE public.departments IS 'Department table for contacts module';`,
		`COMMENT ON COLUMN public.departments.group_id IS 'Enterprise group ID';`,
		`COMMENT ON COLUMN public.departments.parent_id IS 'Parent department ID, NULL for root department';`,
		`COMMENT ON COLUMN public.departments.name IS 'Department name';`,
		`COMMENT ON COLUMN public.departments.sort_order IS 'Sort order within same parent';`,
		`COMMENT ON COLUMN public.departments.status IS 'Department status: active/archived';`,
		`CREATE TABLE public.end_users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid,
    type character varying(255) NOT NULL,
    external_user_id character varying(255),
    name character varying(255),
    is_anonymous boolean DEFAULT true NOT NULL,
    session_id character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.members (
    organization_id uuid NOT NULL,
    account_id uuid NOT NULL,
    role character varying(16) DEFAULT 'normal'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    name character varying(255)
);`,
		`COMMENT ON COLUMN public.members.status IS 'Member status: active/inactive';`,
		`CREATE TABLE public.roles (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    permissions jsonb DEFAULT '[]'::jsonb
);`,
		`CREATE TABLE public.organizations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    short_name character varying(100)
);`,
		`CREATE TABLE public.organization_invite_links (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id uuid NOT NULL,
    department_id uuid,
    tenant_id uuid,
    token character varying(255) NOT NULL,
    status character varying(32) NOT NULL,
    require_approval boolean DEFAULT true NOT NULL,
    default_group_role character varying(32) DEFAULT 'normal'::character varying NOT NULL,
    default_tenant_role character varying(32) DEFAULT 'normal'::character varying NOT NULL,
    expires_at timestamp with time zone,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.organization_invite_links IS 'Enterprise invite links for departments and tenants';`,
		`COMMENT ON COLUMN public.organization_invite_links.group_id IS 'Enterprise group ID';`,
		`COMMENT ON COLUMN public.organization_invite_links.department_id IS 'Target department ID (current phase only department invites are used)';`,
		`COMMENT ON COLUMN public.organization_invite_links.tenant_id IS 'Target tenant ID (reserved for future use)';`,
		`COMMENT ON COLUMN public.organization_invite_links.token IS 'Invite token, high entropy random string';`,
		`COMMENT ON COLUMN public.organization_invite_links.status IS 'Invite link status: enabled/disabled/expired/reset';`,
		`COMMENT ON COLUMN public.organization_invite_links.require_approval IS 'Whether join request requires admin approval';`,
		`COMMENT ON COLUMN public.organization_invite_links.default_group_role IS 'Default enterprise group role for joined member';`,
		`COMMENT ON COLUMN public.organization_invite_links.default_tenant_role IS 'Default tenant role for joined member (reserved)';`,
		`COMMENT ON COLUMN public.organization_invite_links.expires_at IS 'Expire time of the invite link, null means never expires';`,
		`CREATE TABLE public.organization_join_requests (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    group_id uuid NOT NULL,
    invite_link_id uuid,
    account_id uuid NOT NULL,
    department_id uuid,
    tenant_id uuid,
    default_group_role character varying(32) NOT NULL,
    default_tenant_role character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    reason text,
    reviewer_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_at timestamp with time zone,
    name character varying(255)
);`,
		`COMMENT ON TABLE public.organization_join_requests IS 'Enterprise join requests created by invite links or admin actions';`,
		`COMMENT ON COLUMN public.organization_join_requests.group_id IS 'Enterprise group ID';`,
		`COMMENT ON COLUMN public.organization_join_requests.invite_link_id IS 'Related invite link ID, null if created directly by admin';`,
		`COMMENT ON COLUMN public.organization_join_requests.account_id IS 'Applicant account ID';`,
		`COMMENT ON COLUMN public.organization_join_requests.department_id IS 'Target department ID';`,
		`COMMENT ON COLUMN public.organization_join_requests.tenant_id IS 'Target tenant ID (reserved for future use)';`,
		`COMMENT ON COLUMN public.organization_join_requests.default_group_role IS 'Default enterprise group role for applicant';`,
		`COMMENT ON COLUMN public.organization_join_requests.default_tenant_role IS 'Default tenant role for applicant (reserved)';`,
		`COMMENT ON COLUMN public.organization_join_requests.status IS 'Join request status: pending/approved/rejected/expired';`,
		`COMMENT ON COLUMN public.organization_join_requests.reason IS 'Additional reason or review comment';`,
		`COMMENT ON COLUMN public.organization_join_requests.reviewer_id IS 'Reviewer account ID';`,
		`CREATE TABLE public.gdpr_audit_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    action_type character varying(50) NOT NULL,
    actor_id uuid,
    actor_email character varying(255),
    subject_id uuid NOT NULL,
    subject_email character varying(255),
    tenant_id uuid,
    details jsonb DEFAULT '{}'::jsonb,
    ip_address character varying(45),
    user_agent text,
    status character varying(20) DEFAULT 'completed'::character varying NOT NULL,
    error_message text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.workspace_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    workspace_id uuid NOT NULL,
    account_id uuid NOT NULL,
    role character varying(16) DEFAULT 'normal'::character varying NOT NULL,
    invited_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    current boolean DEFAULT false NOT NULL,
    role_id uuid,
    extensions jsonb DEFAULT '{}'::jsonb
);`,
		`CREATE TABLE public.workspaces (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    encrypt_public_key text,
    plan character varying(255) DEFAULT 'basic'::character varying NOT NULL,
    status character varying(255) DEFAULT 'normal'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    custom_config text,
    organization_id uuid,
    department_id uuid,
    api_key_id uuid
);`,
		`CREATE TABLE public.user_consents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    consent_type character varying(50) NOT NULL,
    is_granted boolean NOT NULL,
    granted_at timestamp without time zone,
    revoked_at timestamp without time zone,
    ip_address character varying(45),
    user_agent text,
    version character varying(20) DEFAULT '1.0'::character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.zgi_bootstrap_locks (
    key character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.zgi_setups (
    version character varying(255) NOT NULL,
    setup_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
	},
}
