package baseline

var AppsWorkflowsSchema = File{
	Name: "20_apps_workflows",
	Statements: []string{
		`CREATE TABLE public.agent_api_key_usage_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    api_key_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    operation_log_id uuid,
    request_path character varying(500) NOT NULL,
    request_ip character varying(45) NOT NULL,
    user_agent text,
    request_headers json,
    request_body_size bigint DEFAULT 0,
    response_status_code integer NOT NULL,
    response_body_size bigint DEFAULT 0,
    response_time_ms integer NOT NULL,
    tokens_used integer DEFAULT 0,
    cost_amount numeric(10,6) DEFAULT 0,
    currency character varying(3) DEFAULT 'USD'::character varying,
    error_message text,
    metadata json,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tenant_id uuid
);`,
		`CREATE TABLE public.agent_api_keys (
    id character varying(36) NOT NULL,
    agent_id character varying(36) NOT NULL,
    tenant_id character varying(36) NOT NULL,
    key_hash character varying(64) NOT NULL,
    key_prefix character varying(12) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying,
    expires_at timestamp with time zone,
    usage_count bigint DEFAULT 0,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT agent_api_keys_status_check CHECK (((status)::text = ANY (ARRAY[('active'::character varying)::text, ('inactive'::character varying)::text, ('revoked'::character varying)::text])))
);`,
		`CREATE TABLE public.agent_extensions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    permission character varying(32),
    extended_properties jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.agents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    agent_type character varying(255) NOT NULL,
    icon_type character varying(255),
    icon text,
    agents_model_config_id uuid,
    workflow_id uuid,
    enable_api boolean NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    is_universal boolean DEFAULT false NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    workflow_config character varying,
    internal boolean DEFAULT false,
    web_app_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    web_app_status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    web_app_offlined_at timestamp with time zone,
    web_app_offlined_by uuid,
    web_app_offline_reason text DEFAULT ''::text NOT NULL
);`,
		`CREATE TABLE public.agents_configs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agents_id uuid NOT NULL,
    model_provider character varying(255),
    model_version_id character varying(255),
    configs json,
    created_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    greeting_message text,
    user_input_form text,
    dataset_query_variable character varying(255),
    pre_prompt text,
    agent_mode text,
    sensitive_word_avoidance text,
    retriever_resource text,
    prompt_type character varying(255) DEFAULT 'simple'::character varying NOT NULL,
    chat_prompt_config text,
    completion_prompt_config text,
    dataset_configs text,
    external_data_tools text,
    file_upload text
);`,
		`CREATE TABLE public.agents_conversations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    agent_config_id uuid,
    model_provider character varying(255),
    override_model_configs text,
    model_version_id character varying(255),
    mode character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    summary text,
    inputs json NOT NULL,
    introduction text,
    system_instruction text,
    system_instruction_tokens integer DEFAULT 0 NOT NULL,
    status character varying(255) NOT NULL,
    invoke_from character varying(255),
    from_source character varying(255) NOT NULL,
    from_end_user_id uuid,
    from_account_id uuid,
    read_at timestamp with time zone,
    read_account_id uuid,
    dialogue_count integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    workflow_version_uuid uuid,
    web_app_id uuid
);`,
		`CREATE TABLE public.agents_messages (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    model_provider character varying(255),
    model_version_id character varying(255),
    override_model_configs text,
    conversation_id uuid NOT NULL,
    inputs json NOT NULL,
    query text NOT NULL,
    message json NOT NULL,
    message_tokens integer DEFAULT 0 NOT NULL,
    message_unit_price numeric(10,4) NOT NULL,
    message_price_unit numeric(10,7) DEFAULT 0.001 NOT NULL,
    answer text NOT NULL,
    answer_tokens integer DEFAULT 0 NOT NULL,
    answer_unit_price numeric(10,4) NOT NULL,
    answer_price_unit numeric(10,7) DEFAULT 0.001 NOT NULL,
    parent_message_id uuid,
    provider_response_latency double precision DEFAULT 0 NOT NULL,
    total_price numeric(10,7),
    currency character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'normal'::character varying NOT NULL,
    error text,
    message_metadata text,
    invoke_from character varying(255),
    from_source character varying(255) NOT NULL,
    from_end_user_id uuid,
    from_account_id uuid,
    created_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    agent_based boolean DEFAULT false NOT NULL,
    workflow_run_id uuid,
    workflow_version_uuid uuid,
    web_app_id uuid
);`,
		`CREATE TABLE public.aichat_conversations (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    workspace_id uuid,
    account_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    status character varying(32) DEFAULT 'normal'::character varying NOT NULL,
    runtime_status character varying(32) DEFAULT 'idle'::character varying NOT NULL,
    current_leaf_message_id uuid,
    active_message_id uuid,
    dialogue_count integer DEFAULT 0 NOT NULL,
    source character varying(32) DEFAULT 'console'::character varying NOT NULL,
    source_conversation_id uuid,
    source_web_app_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
		`CREATE TABLE public.aichat_custom_skills (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    skill_id character varying(128) NOT NULL,
    name character varying(128) NOT NULL,
    description text NOT NULL,
    when_to_use text NOT NULL,
    runtime_type character varying(32) DEFAULT 'prompt'::character varying NOT NULL,
    display jsonb DEFAULT '{}'::jsonb NOT NULL,
    storage_path text NOT NULL,
    manifest jsonb DEFAULT '{}'::jsonb NOT NULL,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    validation_error text,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.aichat_messages (
    id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    parent_id uuid,
    query text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    error text,
    model_provider character varying(255),
    model_name character varying(255) NOT NULL,
    billing_reason_source character varying(64),
    model_parameters jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    source_message_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.aichat_organization_skill_configs (
    organization_id uuid NOT NULL,
    skill_id character varying(128) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.app_prompt_optimization_runs (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    workspace_id uuid,
    prompt_id uuid,
    account_id uuid NOT NULL,
    goal character varying(32) DEFAULT 'general'::character varying NOT NULL,
    provider character varying(128),
    model character varying(255),
    preserve_variables boolean DEFAULT true NOT NULL,
    detected_variables jsonb DEFAULT '[]'::jsonb NOT NULL,
    raw_prompt text NOT NULL,
    safe_output text NOT NULL,
    balanced_output text NOT NULL,
    advanced_output text NOT NULL,
    adopted_variant character varying(16),
    adopted_prompt_version_id uuid,
    adopted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.app_prompt_versions (
    id uuid NOT NULL,
    prompt_id uuid NOT NULL,
    version integer NOT NULL,
    prompt_type character varying(16) NOT NULL,
    content jsonb NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    labels jsonb DEFAULT '[]'::jsonb NOT NULL,
    commit_message text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.app_prompts (
    id uuid NOT NULL,
    organization_id uuid,
    workspace_id uuid,
    owner_account_id uuid,
    source character varying(32) NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    description text,
    locale character varying(32) DEFAULT 'zh-Hans'::character varying NOT NULL,
    category character varying(128),
    tags jsonb DEFAULT '[]'::jsonb NOT NULL,
    latest_version integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.automation_action_runs (
    id uuid NOT NULL,
    task_run_id uuid NOT NULL,
    task_action_id uuid NOT NULL,
    action_type character varying(32) NOT NULL,
    channel_type character varying(32),
    request_payload jsonb,
    response_payload jsonb,
    error_message text,
    status character varying(32) NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.automation_task_actions (
    id uuid NOT NULL,
    task_id uuid NOT NULL,
    action_type character varying(32) NOT NULL,
    action_order integer DEFAULT 1 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    config jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.automation_task_runs (
    id uuid NOT NULL,
    task_id uuid NOT NULL,
    trigger_source character varying(32) NOT NULL,
    scheduled_for timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    status character varying(32) NOT NULL,
    runtime_context jsonb,
    error_summary text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.automation_tasks (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    status character varying(32) NOT NULL,
    trigger_type character varying(32) DEFAULT 'schedule'::character varying NOT NULL,
    schedule_type character varying(32) NOT NULL,
    timezone character varying(64) NOT NULL,
    schedule_config jsonb NOT NULL,
    next_run_at timestamp with time zone,
    last_run_at timestamp with time zone,
    last_run_status character varying(32),
    source_type character varying(32) NOT NULL,
    source_ref character varying(255),
    source_snapshot jsonb,
    created_by uuid NOT NULL,
    updated_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.conversation_group (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    app_id character varying(36) NOT NULL,
    group_id character varying(36) NOT NULL,
    conversation_id character varying(36),
    from_account_id character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name character varying(255) DEFAULT ''::character varying NOT NULL
);`,
		`CREATE TABLE public.conversations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    app_id uuid NOT NULL,
    model_provider character varying(255),
    override_model_configs text,
    model_id character varying(255),
    mode character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    summary text,
    inputs json NOT NULL,
    introduction text,
    system_instruction text,
    system_instruction_tokens integer DEFAULT 0 NOT NULL,
    status character varying(255) NOT NULL,
    from_source character varying(255) NOT NULL,
    from_end_user_id uuid,
    from_account_id uuid,
    read_at timestamp with time zone,
    read_account_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    invoke_from character varying(255),
    dialogue_count integer DEFAULT 0 NOT NULL
);`,
		`CREATE TABLE public.enterprise_group_plugin_subscriptions (
    id integer NOT NULL,
    group_id uuid NOT NULL,
    plugin_id character varying(255) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    config text,
    subscribed_by uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    account_id uuid,
    installation_id uuid
);`,
		`COMMENT ON TABLE public.enterprise_group_plugin_subscriptions IS 'Plugin subscriptions at organization level';`,
		`COMMENT ON COLUMN public.enterprise_group_plugin_subscriptions.account_id IS 'Member account ID who subscribed to the plugin';`,
		`COMMENT ON COLUMN public.enterprise_group_plugin_subscriptions.installation_id IS 'Reference to account_plugin_installations.id';`,
		`CREATE SEQUENCE public.enterprise_group_plugin_subscriptions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;`,
		`ALTER SEQUENCE public.enterprise_group_plugin_subscriptions_id_seq OWNED BY public.enterprise_group_plugin_subscriptions.id;`,
		`CREATE TABLE public.installed_agents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    agent_owner_tenant_id uuid NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.installed_plugin_info (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    marketplace_plugin_id uuid,
    marketplace_version_id uuid NOT NULL,
    plugin_name character varying(100) NOT NULL,
    plugin_version character varying(50) NOT NULL,
    plugin_author character varying(100),
    declaration jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);`,
		`COMMENT ON TABLE public.installed_plugin_info IS 'Installed plugin info, one record per marketplace version';`,
		`COMMENT ON COLUMN public.installed_plugin_info.marketplace_plugin_id IS 'Marketplace plugin ID for redundancy';`,
		`COMMENT ON COLUMN public.installed_plugin_info.declaration IS 'JSONB containing provider and tools definition';`,
		`CREATE TABLE public.message_annotations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    app_id uuid NOT NULL,
    conversation_id uuid,
    message_id uuid,
    content text NOT NULL,
    account_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    question text,
    hit_count integer DEFAULT 0 NOT NULL
);`,
		`CREATE TABLE public.message_feedbacks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    app_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    message_id uuid NOT NULL,
    rating character varying(255) NOT NULL,
    content text,
    from_source character varying(255) NOT NULL,
    from_end_user_id uuid,
    from_account_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.message_files (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    message_id uuid NOT NULL,
    type character varying(255) NOT NULL,
    transfer_method character varying(255) NOT NULL,
    url text,
    upload_file_id uuid,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    belongs_to character varying(255)
);`,
		`CREATE TABLE public.messages (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    app_id uuid NOT NULL,
    model_provider character varying(255),
    model_id character varying(255),
    override_model_configs text,
    conversation_id uuid NOT NULL,
    inputs json NOT NULL,
    query text NOT NULL,
    message json NOT NULL,
    message_tokens integer DEFAULT 0 NOT NULL,
    message_unit_price numeric(10,4) NOT NULL,
    answer text NOT NULL,
    answer_tokens integer DEFAULT 0 NOT NULL,
    answer_unit_price numeric(10,4) NOT NULL,
    provider_response_latency double precision DEFAULT 0 NOT NULL,
    total_price numeric(10,7),
    currency character varying(255) NOT NULL,
    from_source character varying(255) NOT NULL,
    from_end_user_id uuid,
    from_account_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    agent_based boolean DEFAULT false NOT NULL,
    message_price_unit numeric(10,7) DEFAULT 0.001 NOT NULL,
    answer_price_unit numeric(10,7) DEFAULT 0.001 NOT NULL,
    workflow_run_id uuid,
    status character varying(255) DEFAULT 'normal'::character varying NOT NULL,
    error text,
    message_metadata text,
    invoke_from character varying(255),
    parent_message_id uuid
);`,
		`CREATE TABLE public.plugin_installations (
    id character varying(255) NOT NULL,
    tenant_id character varying(255) NOT NULL,
    plugin_unique_identifier character varying(255) NOT NULL,
    version character varying(100),
    source character varying(50) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    installed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);`,
		`CREATE TABLE public.workflow_app_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    workflow_id uuid NOT NULL,
    workflow_run_id uuid NOT NULL,
    created_from character varying(255) NOT NULL,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    agent_id uuid
);`,
		`CREATE TABLE public.workflow_approval_deliveries (
    id uuid NOT NULL,
    form_id uuid NOT NULL,
    delivery_method_type character varying(32) NOT NULL,
    delivery_config_id uuid,
    channel_payload text NOT NULL,
    last_error text,
    sent_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_approval_forms (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    workflow_run_id character varying(255) NOT NULL,
    node_id character varying(255) NOT NULL,
    node_title character varying(255),
    form_definition text NOT NULL,
    rendered_content text NOT NULL,
    status character varying(32) DEFAULT 'waiting'::character varying NOT NULL,
    expiration_time timestamp without time zone NOT NULL,
    selected_action_id character varying(200),
    submitted_data text,
    submitted_at timestamp without time zone,
    submission_user_id uuid,
    submission_end_user_id uuid,
    completed_by_recipient_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_approval_recipients (
    id uuid NOT NULL,
    form_id uuid NOT NULL,
    delivery_id uuid NOT NULL,
    recipient_type character varying(64) NOT NULL,
    recipient_payload text NOT NULL,
    access_token character varying(64) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_conversation_variables (
    id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    app_id uuid NOT NULL,
    data text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_node_executions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    workflow_id uuid NOT NULL,
    triggered_from character varying(255) NOT NULL,
    workflow_run_id uuid,
    index integer NOT NULL,
    predecessor_node_id character varying(255),
    node_id character varying(255) NOT NULL,
    node_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    inputs text,
    process_data text,
    outputs text,
    status character varying(255) NOT NULL,
    error text,
    elapsed_time double precision DEFAULT 0 NOT NULL,
    execution_metadata text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    finished_at timestamp with time zone,
    node_execution_id character varying(255),
    agent_id uuid
);`,
		`CREATE TABLE public.workflow_node_runtime_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    workflow_id uuid NOT NULL,
    triggered_from character varying(255) NOT NULL,
    workflow_run_id uuid,
    index integer NOT NULL,
    predecessor_node_id character varying(255),
    node_execution_id character varying(255),
    node_id character varying(255) NOT NULL,
    node_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    inputs text,
    process_data text,
    outputs text,
    status character varying(255) NOT NULL,
    error text,
    elapsed_time double precision DEFAULT 0 NOT NULL,
    execution_metadata text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    finished_at timestamp with time zone,
    graph jsonb,
    features jsonb,
    workflow_version_uuid uuid,
    web_app_id uuid,
    error_type character varying(64),
    error_stack text,
    diagnosis_result text,
    diagnosis_model character varying(128),
    diagnosis_tokens integer DEFAULT 0,
    diagnosis_latency_ms integer DEFAULT 0,
    is_llm_diagnosed boolean DEFAULT false,
    diagnosis_node_config jsonb,
    diagnosis_upstream_config jsonb,
    diagnosis_input_snapshot jsonb,
    diagnosis_upstream_outputs jsonb
);`,
		`CREATE TABLE public.workflow_run_events (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    workflow_run_id character varying(255) NOT NULL,
    sequence integer NOT NULL,
    event_type character varying(100) NOT NULL,
    event_data text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_run_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    sequence_number integer NOT NULL,
    workflow_id uuid NOT NULL,
    type character varying(255) NOT NULL,
    triggered_from character varying(255) NOT NULL,
    version character varying(255) NOT NULL,
    graph text,
    inputs text,
    status character varying(255) NOT NULL,
    outputs text DEFAULT '{}'::text,
    error text,
    elapsed_time double precision DEFAULT 0 NOT NULL,
    total_tokens bigint DEFAULT 0 NOT NULL,
    total_steps integer DEFAULT 0,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    exceptions_count integer DEFAULT 0,
    features jsonb,
    workflow_version_uuid uuid,
    web_app_id uuid
);`,
		`CREATE TABLE public.workflow_run_pause_reasons (
    id uuid NOT NULL,
    pause_id uuid NOT NULL,
    type character varying(64) NOT NULL,
    node_id character varying(255) DEFAULT ''::character varying NOT NULL,
    form_id character varying(255) DEFAULT ''::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_run_pauses (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    workflow_run_id character varying(255) NOT NULL,
    node_id character varying(255) NOT NULL,
    reason character varying(64) NOT NULL,
    state_json text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resumed_at timestamp without time zone,
    conversation_id uuid
);`,
		`CREATE TABLE public.workflow_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    sequence_number integer NOT NULL,
    workflow_id uuid NOT NULL,
    type character varying(255) NOT NULL,
    triggered_from character varying(255) NOT NULL,
    version character varying(255) NOT NULL,
    graph text,
    inputs text,
    status character varying(255) NOT NULL,
    outputs text,
    error text,
    elapsed_time double precision DEFAULT 0 NOT NULL,
    total_tokens bigint DEFAULT 0 NOT NULL,
    total_steps integer DEFAULT 0,
    created_by_role character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    exceptions_count integer DEFAULT 0
);`,
		`CREATE TABLE public.workflow_test_batch_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    case_id uuid NOT NULL,
    case_snapshot jsonb NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    workflow_run_id character varying(120) DEFAULT ''::character varying NOT NULL,
    outputs jsonb DEFAULT '{}'::jsonb NOT NULL,
    error text DEFAULT ''::text NOT NULL,
    judge_reason text DEFAULT ''::text NOT NULL,
    judge_suggestion text DEFAULT ''::text NOT NULL,
    judge_confidence numeric(5,4) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_test_batches (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    name character varying(160) NOT NULL,
    status character varying(32) DEFAULT 'queued'::character varying NOT NULL,
    case_count integer DEFAULT 0 NOT NULL,
    passed_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    review_count integer DEFAULT 0 NOT NULL,
    judge_prompt_snapshot text NOT NULL,
    summary text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    judge_model_provider_snapshot character varying(100) DEFAULT ''::character varying NOT NULL,
    judge_model_name_snapshot character varying(160) DEFAULT ''::character varying NOT NULL,
    workflow_version_mode character varying(40) DEFAULT 'draft'::character varying NOT NULL,
    workflow_version_uuid uuid,
    workflow_version_label character varying(160) DEFAULT 'current_draft'::character varying NOT NULL
);`,
		`CREATE TABLE public.workflow_test_cases (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    scenario_id uuid,
    content text NOT NULL,
    question_type character varying(32) DEFAULT 'core'::character varying NOT NULL,
    status character varying(32) DEFAULT 'enabled'::character varying NOT NULL,
    turns jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expected_result text DEFAULT ''::text NOT NULL
);`,
		`CREATE TABLE public.workflow_test_scenarios (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    name character varying(120) NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    source character varying(32) DEFAULT 'manual'::character varying NOT NULL,
    case_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.workflow_test_settings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_id uuid NOT NULL,
    judge_prompt_template text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    judge_model_provider character varying(100) DEFAULT ''::character varying NOT NULL,
    judge_model_name character varying(160) DEFAULT ''::character varying NOT NULL
);`,
		`CREATE TABLE public.workflows (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    app_id uuid NOT NULL,
    type character varying(255) NOT NULL,
    version character varying(255) NOT NULL,
    graph text NOT NULL,
    features text NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone NOT NULL,
    environment_variables text DEFAULT '{}'::text NOT NULL,
    conversation_variables text DEFAULT '{}'::text NOT NULL,
    marked_name character varying DEFAULT ''::character varying NOT NULL,
    marked_comment character varying DEFAULT ''::character varying NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    agent_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    version_uuid uuid,
    internal boolean DEFAULT false
);`,
	},
}
