package baseline

var ModelGatewaySchema = File{
	Name: "30_model_gateway",
	Statements: []string{
		`CREATE TABLE public.content_parse_artifacts (
    id uuid NOT NULL,
    source_content_hash character varying(255) NOT NULL,
    profile character varying(64) NOT NULL,
    canonical_ir_version character varying(64) NOT NULL,
    provider_signature character varying(128) NOT NULL,
    artifact_storage_key text,
    diagnostics_storage_key text,
    summary_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.content_parse_chunk_artifact_sets (
    id uuid NOT NULL,
    parse_artifact_id uuid,
    parse_run_id uuid,
    source_content_hash character varying(255) NOT NULL,
    use_case character varying(32) NOT NULL,
    planner_name character varying(64) NOT NULL,
    parent_mode character varying(64),
    segmentation character varying(64),
    chunker_version character varying(64) NOT NULL,
    signature character varying(255) NOT NULL,
    status character varying(32) DEFAULT 'succeeded'::character varying NOT NULL,
    unit_count integer DEFAULT 0 NOT NULL,
    content_hash character varying(255) NOT NULL,
    quality_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    summary_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    artifact_storage_key text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.content_parse_chunking_runs (
    id uuid NOT NULL,
    parse_run_id uuid NOT NULL,
    use_case character varying(32) NOT NULL,
    planner_name character varying(64) NOT NULL,
    parent_mode character varying(64),
    segmentation character varying(64),
    unit_count integer DEFAULT 0 NOT NULL,
    plan_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    artifact_storage_key text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    chunk_artifact_set_id uuid
);`,
		`CREATE TABLE public.content_parse_playground_runs (
    id uuid NOT NULL,
    workspace_id uuid,
    account_id uuid,
    file_name text NOT NULL,
    file_size bigint DEFAULT 0 NOT NULL,
    source_content_hash character varying(255) NOT NULL,
    requested_provider_key character varying(64) NOT NULL,
    final_provider_key character varying(64),
    adapter_name character varying(64),
    engine_name character varying(64),
    profile character varying(64) NOT NULL,
    ocr_engine character varying(64),
    status character varying(32) NOT NULL,
    quality_level character varying(32) NOT NULL,
    fallback_used boolean DEFAULT false NOT NULL,
    duration_ms integer,
    artifact_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    route_plan_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    chunk_source_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    chunk_plan_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    quality_summary_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    summary_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    share_token character varying(64) NOT NULL,
    is_share_enabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    source_storage_key text,
    source_storage_type character varying(64),
    source_mime_type character varying(128),
    source_file_ext character varying(32)
);`,
		`CREATE TABLE public.content_parse_provider_configs (
    id uuid NOT NULL,
    scope character varying(32) NOT NULL,
    workspace_id uuid,
    provider_key character varying(64) NOT NULL,
    provider_type character varying(32) NOT NULL,
    display_name character varying(128) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    adapter_name character varying(64) NOT NULL,
    engine_name character varying(64),
    base_url text,
    credentials_ciphertext jsonb DEFAULT '{}'::jsonb NOT NULL,
    timeout_sec integer DEFAULT 180 NOT NULL,
    supports_file_types jsonb DEFAULT '[]'::jsonb NOT NULL,
    supports_profiles jsonb DEFAULT '[]'::jsonb NOT NULL,
    cost_level character varying(32),
    privacy_level character varying(32),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by uuid,
    updated_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.content_parse_provider_health_checks (
    id uuid NOT NULL,
    provider_config_id uuid NOT NULL,
    status character varying(32) NOT NULL,
    latency_ms integer,
    error_message text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    checked_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.content_parse_route_policies (
    id uuid NOT NULL,
    scope character varying(32) NOT NULL,
    workspace_id uuid,
    policy_key character varying(64) NOT NULL,
    display_name character varying(128) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    allow_remote boolean DEFAULT true NOT NULL,
    allow_fallback boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by uuid,
    updated_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.content_parse_route_policy_rules (
    id uuid NOT NULL,
    policy_id uuid NOT NULL,
    match_file_types jsonb DEFAULT '[]'::jsonb NOT NULL,
    match_mime_prefix character varying(128),
    match_is_scanned boolean,
    preferred_provider_order jsonb DEFAULT '[]'::jsonb NOT NULL,
    fallback_provider_order jsonb DEFAULT '[]'::jsonb NOT NULL,
    require_local boolean DEFAULT false NOT NULL,
    allow_vlm boolean DEFAULT true NOT NULL,
    max_timeout_sec integer,
    sort_order integer DEFAULT 100 NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.content_parse_runs (
    id uuid NOT NULL,
    workspace_id uuid,
    dataset_id uuid,
    document_id uuid,
    file_id uuid,
    artifact_id uuid,
    source_type character varying(32) NOT NULL,
    source_ref text,
    file_name text,
    intent character varying(32) NOT NULL,
    profile character varying(64) NOT NULL,
    policy_key character varying(64),
    route_policy_id uuid,
    requested_provider_key character varying(64),
    planned_provider_order jsonb DEFAULT '[]'::jsonb NOT NULL,
    attempted_provider_order jsonb DEFAULT '[]'::jsonb NOT NULL,
    final_provider_key character varying(64),
    adapter_name character varying(64),
    engine_name character varying(64),
    status character varying(32) NOT NULL,
    quality_level character varying(32) NOT NULL,
    fallback_used boolean DEFAULT false NOT NULL,
    duration_ms integer,
    artifact_storage_key text,
    diagnostics_storage_key text,
    summary_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.llm_catalog_sync_states (
    sync_key character varying(50) NOT NULL,
    last_applied_version bigint DEFAULT 0 NOT NULL,
    last_applied_at timestamp with time zone,
    last_error text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.llm_credentials (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid,
    name character varying(100),
    provider character varying(50) NOT NULL,
    api_key_ciphertext text NOT NULL,
    api_key_hash character varying(64),
    api_base_url character varying(500),
    is_active boolean DEFAULT true,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    protocol character varying(50)
);`,
		`COMMENT ON TABLE public.llm_credentials IS 'Centralized credential storage for LLM API keys';`,
		`COMMENT ON COLUMN public.llm_credentials.organization_id IS 'NULL = system credential, otherwise user credential';`,
		`COMMENT ON COLUMN public.llm_credentials.api_key_ciphertext IS 'AES-256-GCM encrypted API key';`,
		`CREATE TABLE public.llm_custom_models (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    provider_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    display_name character varying(200) NOT NULL,
    context_window integer,
    max_output_tokens integer,
    input_price numeric(10,4) DEFAULT 0,
    output_price numeric(10,4) DEFAULT 0,
    supports_vision boolean DEFAULT false,
    supports_tool_call boolean DEFAULT false,
    supports_streaming boolean DEFAULT true,
    supports_reasoning boolean DEFAULT false,
    knowledge_cutoff character varying(20),
    description text,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    use_cases text[] DEFAULT '{}'::text[] NOT NULL,
    max_input_tokens integer DEFAULT 0,
    slug character varying(100),
    family character varying(100),
    family_slug character varying(100),
    status character varying(20) DEFAULT 'active'::character varying,
    tagline text,
    is_flagship boolean DEFAULT false,
    is_featured boolean DEFAULT false,
    is_new boolean DEFAULT false,
    access_type character varying(20) DEFAULT 'closed'::character varying,
    currency character varying(10) DEFAULT 'USD'::character varying,
    chat_completions boolean DEFAULT true,
    embeddings boolean DEFAULT false,
    streaming boolean DEFAULT true,
    structured_output boolean DEFAULT false,
    json_mode boolean DEFAULT false,
    input_modalities jsonb DEFAULT '["text"]'::jsonb,
    output_modalities jsonb DEFAULT '["text"]'::jsonb,
    supported_parameters jsonb DEFAULT '[]'::jsonb,
    legacy_function_call boolean DEFAULT false NOT NULL,
    provider character varying(100) DEFAULT ''::character varying,
    vision boolean DEFAULT false,
    function_calling boolean DEFAULT false,
    reasoning boolean DEFAULT false,
    audio boolean DEFAULT false,
    image_generation boolean DEFAULT false,
    speech_generation boolean DEFAULT false,
    transcription boolean DEFAULT false,
    translation boolean DEFAULT false,
    moderation boolean DEFAULT false,
    realtime boolean DEFAULT false,
    batch boolean DEFAULT false,
    fine_tuning boolean DEFAULT false,
    assistants boolean DEFAULT false,
    responses boolean DEFAULT false,
    distillation boolean DEFAULT false,
    system_prompt boolean DEFAULT true,
    logprobs boolean DEFAULT false,
    web_search boolean DEFAULT false,
    file_search boolean DEFAULT false,
    code_interpreter boolean DEFAULT false,
    computer_use boolean DEFAULT false,
    mcp boolean DEFAULT false,
    reasoning_effort boolean DEFAULT false,
    parallel_tool_calls boolean DEFAULT false,
    temperature boolean DEFAULT true,
    top_p boolean DEFAULT true,
    presence_penalty boolean DEFAULT false,
    frequency_penalty boolean DEFAULT false,
    logit_bias boolean DEFAULT false,
    seed boolean DEFAULT false,
    stop boolean DEFAULT true,
    max_stop_sequences integer DEFAULT 4,
    default_parameters jsonb DEFAULT '{}'::jsonb,
    config_parameters jsonb DEFAULT '[]'::jsonb NOT NULL
);`,
		`COMMENT ON COLUMN public.llm_custom_models.use_cases IS 'Usage scenarios for tenant custom models';`,
		`CREATE TABLE public.llm_custom_providers (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    provider character varying(50) NOT NULL,
    provider_name character varying(100) NOT NULL,
    api_base_url character varying(255),
    protocol character varying(50) DEFAULT 'openai'::character varying,
    logo_url character varying(255),
    documentation_url character varying(255),
    description text,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.llm_default_models (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    use_case character varying(50) NOT NULL,
    provider character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by uuid,
    updated_by uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone
);`,
		`CREATE TABLE public.llm_model_configs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    model_id uuid NOT NULL,
    is_enabled boolean DEFAULT true,
    custom_display_name character varying(200),
    input_price_override numeric(10,4),
    output_price_override numeric(10,4),
    access_scope character varying(20) DEFAULT 'all'::character varying,
    visible_groups jsonb DEFAULT '[]'::jsonb,
    visible_users jsonb DEFAULT '[]'::jsonb,
    sort_order integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT chk_access_scope CHECK (((access_scope)::text = ANY (ARRAY[('all'::character varying)::text, ('group'::character varying)::text, ('user'::character varying)::text])))
);`,
		`CREATE TABLE public.llm_models (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    provider character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    display_name character varying(200) NOT NULL,
    attachment boolean DEFAULT false,
    reasoning boolean DEFAULT false,
    function_calling boolean DEFAULT false,
    structured_output boolean DEFAULT false,
    temperature boolean DEFAULT true,
    knowledge_cutoff character varying(20),
    release_date date,
    last_updated date,
    input_modalities jsonb,
    output_modalities jsonb,
    open_weights boolean DEFAULT false,
    input_price numeric(10,6),
    output_price numeric(10,6),
    cost_cache_read numeric(10,4),
    cost_cache_write numeric(10,4),
    cost_context_over_200k jsonb,
    context_window integer,
    max_output_tokens integer,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    description text,
    tokenizer character varying(100),
    instruct_type character varying(100),
    cost_image numeric(10,4),
    cost_audio numeric(10,4),
    supported_parameters jsonb,
    default_parameters jsonb,
    is_moderated boolean DEFAULT false,
    is_finetuned boolean DEFAULT false,
    cost_rate jsonb DEFAULT '{"audio": 1, "image": 1, "input": 1, "output": 1}'::jsonb,
    is_system_enabled boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0,
    vision boolean DEFAULT false,
    model_tier character varying(20) DEFAULT NULL::character varying,
    is_recommended boolean DEFAULT false,
    temperature_min numeric(4,2) DEFAULT 0,
    temperature_max numeric(4,2) DEFAULT 2,
    temperature_default numeric(4,2) DEFAULT 1,
    audio boolean DEFAULT false NOT NULL,
    legacy_function_call boolean DEFAULT false NOT NULL,
    json_mode boolean DEFAULT false NOT NULL,
    streaming boolean DEFAULT true NOT NULL,
    use_cases text[] DEFAULT '{}'::text[] NOT NULL,
    max_input_tokens integer DEFAULT 0,
    slug character varying(100),
    family character varying(100),
    family_slug character varying(100),
    status character varying(20) DEFAULT 'active'::character varying,
    tagline text,
    is_flagship boolean DEFAULT false,
    is_featured boolean DEFAULT false,
    is_new boolean DEFAULT false,
    access_type character varying(20) DEFAULT 'closed'::character varying,
    currency character varying(10) DEFAULT 'USD'::character varying,
    chat_completions boolean DEFAULT true,
    embeddings boolean DEFAULT false,
    image_generation boolean DEFAULT false,
    speech_generation boolean DEFAULT false,
    transcription boolean DEFAULT false,
    moderation boolean DEFAULT false,
    realtime boolean DEFAULT false,
    batch boolean DEFAULT false,
    fine_tuning boolean DEFAULT false,
    assistants boolean DEFAULT false,
    responses boolean DEFAULT false,
    distillation boolean DEFAULT false,
    system_prompt boolean DEFAULT true,
    logprobs boolean DEFAULT false,
    web_search boolean DEFAULT false,
    file_search boolean DEFAULT false,
    code_interpreter boolean DEFAULT false,
    computer_use boolean DEFAULT false,
    mcp boolean DEFAULT false,
    seed boolean DEFAULT false,
    stop boolean DEFAULT true,
    max_stop_sequences integer DEFAULT 4,
    top_p boolean DEFAULT true,
    presence_penalty boolean DEFAULT false,
    frequency_penalty boolean DEFAULT false,
    logit_bias boolean DEFAULT false,
    parallel_tool_calls boolean DEFAULT true,
    reasoning_effort boolean DEFAULT false,
    protocol_config jsonb DEFAULT '[]'::jsonb,
    family_name character varying(200),
    parent_id uuid,
    family_default boolean DEFAULT false,
    cached_input_price numeric(10,6),
    videos boolean DEFAULT false,
    image_edit boolean DEFAULT false,
    translation boolean DEFAULT false,
    is_configured boolean DEFAULT false,
    image_prices jsonb DEFAULT '[]'::jsonb,
    pricing jsonb DEFAULT '{}'::jsonb NOT NULL,
    config_parameters jsonb DEFAULT '[]'::jsonb NOT NULL
);`,
		`COMMENT ON COLUMN public.llm_models.reasoning IS 'Has reasoning/thinking capabilities';`,
		`COMMENT ON COLUMN public.llm_models.function_calling IS 'Supports function/tool calling';`,
		`COMMENT ON COLUMN public.llm_models.input_price IS 'Input token price per million tokens (OpenAI naming)';`,
		`COMMENT ON COLUMN public.llm_models.output_price IS 'Output token price per million tokens (OpenAI naming)';`,
		`COMMENT ON COLUMN public.llm_models.context_window IS 'Maximum context window size in tokens (OpenAI naming)';`,
		`COMMENT ON COLUMN public.llm_models.max_output_tokens IS 'Maximum output tokens (OpenAI naming)';`,
		`COMMENT ON COLUMN public.llm_models.is_system_enabled IS 'System-level control: whether this model is available for tenants to use';`,
		`COMMENT ON COLUMN public.llm_models.vision IS 'Supports image/vision input';`,
		`COMMENT ON COLUMN public.llm_models.use_cases IS 'Usage scenarios: text-chat, agent, vision, image-gen, embedding, rerank, speech-to-text, text-to-speech, realtime-audio, video-gen, moderation, reasoning, function-calling';`,
		`COMMENT ON COLUMN public.llm_models.max_input_tokens IS 'Maximum input tokens (OpenAI naming)';`,
		`COMMENT ON COLUMN public.llm_models.slug IS 'URL-friendly model identifier';`,
		`COMMENT ON COLUMN public.llm_models.family IS 'Model family (e.g., GPT-4, Claude)';`,
		`COMMENT ON COLUMN public.llm_models.status IS 'Model status: active, deprecated';`,
		`COMMENT ON COLUMN public.llm_models.chat_completions IS 'Supports chat completions endpoint';`,
		`COMMENT ON COLUMN public.llm_models.protocol_config IS 'Protocol configuration array in JSONB format';`,
		`CREATE TABLE public.llm_official_model_snapshots (
    source_key character varying(50) NOT NULL,
    effective_models jsonb DEFAULT '[]'::jsonb NOT NULL,
    latest_models jsonb DEFAULT '[]'::jsonb NOT NULL,
    previous_models jsonb DEFAULT '[]'::jsonb NOT NULL,
    latest_event_version bigint DEFAULT 0 NOT NULL,
    latest_synced_at timestamp with time zone,
    effective_updated_at timestamp with time zone,
    last_check_status character varying(20) DEFAULT 'accepted'::character varying NOT NULL,
    last_reject_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.llm_organization_api_keys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    key character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    accessed_at timestamp with time zone,
    expires_at timestamp with time zone,
    deleted_at timestamp with time zone,
    used_quota bigint DEFAULT 0 NOT NULL,
    remain_quota bigint DEFAULT 0 NOT NULL,
    quota_limit bigint,
    model_limits_enabled boolean DEFAULT false NOT NULL,
    model_limits jsonb,
    allow_ips text DEFAULT ''::text NOT NULL,
    key_hash character varying(64),
    is_internal boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_llm_tenant_api_keys_quota CHECK (((used_quota >= 0) AND (remain_quota >= 0))),
    CONSTRAINT chk_llm_tenant_api_keys_quota_limit CHECK (((quota_limit IS NULL) OR (quota_limit > 0))),
    CONSTRAINT chk_llm_tenant_api_keys_status CHECK (((status)::text = ANY (ARRAY[('active'::character varying)::text, ('inactive'::character varying)::text, ('revoked'::character varying)::text])))
);`,
		`CREATE TABLE public.llm_provider_configs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    provider_id uuid NOT NULL,
    is_enabled boolean DEFAULT true,
    custom_display_name character varying(100),
    custom_api_base_url character varying(255),
    custom_logo_url character varying(255),
    sort_order integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone
);`,
		`CREATE TABLE public.llm_providers (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    provider character varying(50) NOT NULL,
    provider_name character varying(100) NOT NULL,
    api_base_url character varying(255),
    env_keys jsonb,
    npm_package character varying(100),
    documentation_url character varying(255),
    logo_url character varying(255),
    api_key text,
    balance numeric(15,4) DEFAULT 0.0000,
    currency character varying(10) DEFAULT 'USD'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    description text,
    openai_compatible boolean DEFAULT false,
    is_system_enabled boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    protocol character varying(50),
    fallback_protocol character varying(50),
    website character varying(255),
    pricing_url character varying(255),
    tagline character varying(500),
    country_code character varying(10),
    founded_year integer DEFAULT 0
);`,
		`COMMENT ON COLUMN public.llm_providers.is_system_enabled IS 'System-level control: whether this provider is available for tenants to use';`,
		`CREATE TABLE public.llm_routes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    type character varying(20) NOT NULL,
    user_credential_id uuid,
    name character varying(255),
    provider character varying(100),
    protocol character varying(50),
    models jsonb DEFAULT '[]'::jsonb,
    api_base_url character varying(500),
    model_maps jsonb DEFAULT '{}'::jsonb,
    param_override jsonb DEFAULT '{}'::jsonb,
    header_override jsonb DEFAULT '{}'::jsonb,
    priority integer DEFAULT 0 NOT NULL,
    weight integer DEFAULT 1 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    auto_ban boolean DEFAULT false,
    balance numeric(15,4) DEFAULT 0,
    currency character varying(10) DEFAULT 'USD'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    credential_id uuid,
    tags jsonb DEFAULT '[]'::jsonb,
    description text,
    match_models text[] DEFAULT '{}'::text[],
    route_type character varying(20) DEFAULT 'PRIVATE'::character varying,
    credential_ids uuid[] DEFAULT '{}'::uuid[],
    load_balance_strategy character varying(20) DEFAULT 'round_robin'::character varying,
    model_rewrite_map jsonb DEFAULT '{}'::jsonb,
    base_url character varying(255),
    is_official boolean DEFAULT false,
    status character varying(20) DEFAULT 'active'::character varying,
    status_reason text,
    status_changed_at timestamp with time zone,
    circuit_breaker_threshold integer DEFAULT 5,
    circuit_breaker_window_seconds integer DEFAULT 60,
    circuit_breaker_cooldown_seconds integer DEFAULT 30,
    rate_limit_rpm integer,
    rate_limit_tpm bigint,
    timeout_seconds integer DEFAULT 60,
    retry_count integer DEFAULT 3,
    retry_delay_ms integer DEFAULT 1000,
    created_by uuid,
    updated_by uuid,
    supported_protocols jsonb DEFAULT '[]'::jsonb,
    validation_report jsonb DEFAULT '{}'::jsonb,
    sync_mode character varying(20) DEFAULT 'snapshot'::character varying,
    last_synced_at timestamp without time zone,
    fallback_protocol character varying(50),
    protocol_source character varying(20) DEFAULT 'default'::character varying,
    success_count integer DEFAULT 0,
    failure_count integer DEFAULT 0,
    avg_latency_ms integer DEFAULT 0,
    last_health_check_at timestamp without time zone,
    native_protocols jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT chk_load_balance CHECK (((load_balance_strategy IS NULL) OR ((load_balance_strategy)::text = ANY (ARRAY[('round_robin'::character varying)::text, ('random'::character varying)::text, ('weighted'::character varying)::text])))),
    CONSTRAINT chk_route_status CHECK (((status IS NULL) OR ((status)::text = ANY (ARRAY[('active'::character varying)::text, ('disabled'::character varying)::text, ('banned'::character varying)::text, ('maintenance'::character varying)::text])))),
    CONSTRAINT chk_route_type CHECK (((type)::text = ANY (ARRAY[('ZGI_CLOUD'::character varying)::text, ('PRIVATE'::character varying)::text]))),
    CONSTRAINT chk_route_type_new CHECK (((route_type IS NULL) OR ((route_type)::text = ANY (ARRAY[('PRIVATE'::character varying)::text, ('ZGI_CLOUD'::character varying)::text])))),
    CONSTRAINT chk_system_ref CHECK (((((type)::text = 'ZGI_CLOUD'::text) AND (is_official = true)) OR (((type)::text = 'PRIVATE'::text) AND (user_credential_id IS NOT NULL))))
);`,
		`COMMENT ON TABLE public.llm_routes IS 'Tenant routing configuration for load balancing';`,
		`COMMENT ON COLUMN public.llm_routes.type IS 'ZGI_CLOUD = ZGI official cloud service channel, PRIVATE = user private channel';`,
		`CREATE TABLE public.llm_tenant_models (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    provider character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    is_enabled boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone
);`,
		`COMMENT ON TABLE public.llm_tenant_models IS 'DEPRECATED: Use llm_tenant_model_configs instead. This table will be removed in a future version.';`,
		`CREATE TABLE public.llm_usage_bills (
    id uuid NOT NULL,
    attempt_id character varying(120) NOT NULL,
    request_id character varying(100) NOT NULL,
    organization_id uuid NOT NULL,
    app_id uuid,
    app_type character varying(50),
    workspace_id character varying(255),
    api_key_id uuid NOT NULL,
    quota_subject_type character varying(20),
    quota_subject_id character varying(255),
    model_id uuid NOT NULL,
    model_name character varying(100) NOT NULL,
    provider_id uuid NOT NULL,
    provider_name character varying(100) NOT NULL,
    route_id uuid,
    channel_id uuid,
    use_system_provider boolean DEFAULT false NOT NULL,
    status character varying(20) NOT NULL,
    prompt_tokens bigint DEFAULT 0 NOT NULL,
    completion_tokens bigint DEFAULT 0 NOT NULL,
    total_tokens bigint DEFAULT 0 NOT NULL,
    official_points bigint DEFAULT 0 NOT NULL,
    private_points bigint DEFAULT 0 NOT NULL,
    total_points bigint DEFAULT 0 NOT NULL,
    response_time_ms bigint DEFAULT 0 NOT NULL,
    error_code character varying(100),
    error_message text,
    request_created_at timestamp with time zone NOT NULL,
    settled_at timestamp with time zone NOT NULL,
    billing_lane character varying(20) DEFAULT 'private'::character varying NOT NULL,
    remote_deduction_id character varying(120),
    CONSTRAINT ck_llm_usage_bills_app_pair CHECK ((((app_id IS NULL) AND (app_type IS NULL)) OR ((app_id IS NOT NULL) AND (app_type IS NOT NULL)))),
    CONSTRAINT ck_llm_usage_bills_billing_lane CHECK (((billing_lane)::text = ANY ((ARRAY['platform'::character varying, 'private'::character varying])::text[]))),
    CONSTRAINT ck_llm_usage_bills_non_negative CHECK (((prompt_tokens >= 0) AND (completion_tokens >= 0) AND (total_tokens >= 0) AND (official_points >= 0) AND (private_points >= 0) AND (total_points >= 0) AND (response_time_ms >= 0))),
    CONSTRAINT ck_llm_usage_bills_provider_points CHECK ((((use_system_provider = true) AND (private_points = 0)) OR ((use_system_provider = false) AND (official_points = 0)))),
    CONSTRAINT ck_llm_usage_bills_quota_pair CHECK ((((quota_subject_type IS NULL) AND (quota_subject_id IS NULL)) OR ((quota_subject_type IS NOT NULL) AND (quota_subject_id IS NOT NULL)))),
    CONSTRAINT ck_llm_usage_bills_status CHECK (((status)::text = ANY ((ARRAY['success'::character varying, 'failed'::character varying, 'partial'::character varying])::text[]))),
    CONSTRAINT ck_llm_usage_bills_time_order CHECK ((settled_at >= request_created_at)),
    CONSTRAINT ck_llm_usage_bills_total_points CHECK ((total_points = (official_points + private_points))),
    CONSTRAINT ck_llm_usage_bills_total_tokens CHECK ((total_tokens = (prompt_tokens + completion_tokens)))
);`,
		`CREATE TABLE public.llm_workspace_quotas (
    workspace_id character varying(255) NOT NULL,
    organization_id uuid NOT NULL,
    used_quota bigint DEFAULT 0 NOT NULL,
    remain_quota bigint DEFAULT 0 NOT NULL,
    quota_limit bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_llm_workspace_quotas_limit_positive CHECK (((quota_limit IS NULL) OR (quota_limit > 0))),
    CONSTRAINT chk_llm_workspace_quotas_used_non_negative CHECK ((used_quota >= 0))
);`,
	},
}
