package baseline

var DataKnowledgeSchema = File{
	Name: "40_data_knowledge",
	Statements: []string{
		`CREATE TABLE public.child_chunks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    document_id uuid NOT NULL,
    segment_id uuid NOT NULL,
    "position" integer NOT NULL,
    content text NOT NULL,
    word_count integer NOT NULL,
    index_node_id character varying(255),
    index_node_hash character varying(255),
    type character varying(255) DEFAULT 'automatic'::character varying NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    indexing_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text
);`,
		`CREATE TABLE public.data_library_database_asset_refs (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    data_source_id uuid NOT NULL,
    table_id uuid,
    asset_id uuid NOT NULL,
    version_id uuid NOT NULL,
    parse_artifact_id uuid,
    extraction_artifact_id uuid,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_document_assets (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    title text NOT NULL,
    source_file_id character varying(255) NOT NULL,
    current_version_id uuid,
    content_hash character varying(255),
    status character varying(32) DEFAULT 'archived'::character varying NOT NULL,
    processing_level character varying(32) DEFAULT 'archive'::character varying NOT NULL,
    quality_score double precision,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    permission_policy jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_document_versions (
    id uuid NOT NULL,
    asset_id uuid NOT NULL,
    version_no integer NOT NULL,
    source_file_id character varying(255) NOT NULL,
    content_hash character varying(255),
    file_name text,
    file_size bigint DEFAULT 0 NOT NULL,
    mime_type character varying(255),
    parse_artifact_id uuid,
    chunk_artifact_set_id uuid,
    status character varying(32) DEFAULT 'archived'::character varying NOT NULL,
    quality_score double precision,
    uploaded_by character varying(255),
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_extraction_artifacts (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    asset_id uuid NOT NULL,
    version_id uuid NOT NULL,
    parse_artifact_id uuid,
    data_source_id uuid,
    table_id uuid,
    schema_name character varying(255),
    schema_hash character varying(255),
    extractor_provider character varying(128),
    extractor_model character varying(255),
    record_count bigint DEFAULT 0 NOT NULL,
    field_count bigint DEFAULT 0 NOT NULL,
    evidence_count bigint DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    quality_score double precision,
    content_hash character varying(255),
    output_uri text,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_knowledge_base_asset_refs (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    dataset_id uuid NOT NULL,
    asset_id uuid NOT NULL,
    version_id uuid NOT NULL,
    chunk_artifact_set_id uuid,
    vector_artifact_id uuid,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_processing_requests (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    asset_id uuid NOT NULL,
    target_level character varying(32) NOT NULL,
    status character varying(32) DEFAULT 'planned'::character varying NOT NULL,
    requested_by character varying(255),
    force boolean DEFAULT false NOT NULL,
    plan_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    request_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    execution_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    executor_key character varying(255),
    error_code character varying(128),
    error_message text,
    attempt_count integer DEFAULT 0 NOT NULL,
    queued_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_reuse_events (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    asset_id uuid NOT NULL,
    version_id uuid,
    artifact_type character varying(64) NOT NULL,
    artifact_id uuid,
    consumer_type character varying(64) NOT NULL,
    consumer_id character varying(255) NOT NULL,
    consumer_version character varying(255),
    saved_seconds bigint DEFAULT 0 NOT NULL,
    saved_cost_micros bigint DEFAULT 0 NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_library_vector_artifacts (
    id uuid NOT NULL,
    organization_id character varying(255) NOT NULL,
    workspace_id character varying(255),
    asset_id uuid NOT NULL,
    version_id uuid NOT NULL,
    chunk_artifact_set_id uuid NOT NULL,
    embedding_provider character varying(128) NOT NULL,
    embedding_model character varying(255) NOT NULL,
    embedding_dimension integer DEFAULT 0 NOT NULL,
    vector_collection character varying(255) NOT NULL,
    vector_namespace character varying(255),
    vector_count bigint DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    content_hash character varying(255),
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.data_retention_policies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    data_type character varying(50) NOT NULL,
    description text,
    retention_days integer NOT NULL,
    anonymize_after_days integer,
    hard_delete_after_days integer,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.data_source_import_job_errors (
    id uuid NOT NULL,
    job_id uuid NOT NULL,
    row_index integer NOT NULL,
    column_name character varying(255),
    raw_value text,
    error_code character varying(64) NOT NULL,
    error_message text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.data_source_import_jobs (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    workspace_id uuid,
    data_source_id uuid NOT NULL,
    table_id uuid,
    upload_file_id uuid,
    source_type character varying(20) NOT NULL,
    source_file_name character varying(512) NOT NULL,
    status character varying(32) NOT NULL,
    total_rows integer DEFAULT 0 NOT NULL,
    valid_rows integer DEFAULT 0 NOT NULL,
    imported_rows integer DEFAULT 0 NOT NULL,
    failed_rows integer DEFAULT 0 NOT NULL,
    sheet_name character varying(255),
    header_row integer,
    start_row integer,
    schema_snapshot jsonb,
    preview_snapshot jsonb,
    error_summary jsonb,
    created_by character varying(36) NOT NULL,
    updated_by character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.data_source_sql_operations (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    data_source_id uuid NOT NULL,
    table_id uuid,
    data_source_name character varying(255),
    table_name character varying(255),
    sql_statement text NOT NULL,
    operation_type character varying(20) NOT NULL,
    start_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(10) NOT NULL,
    created_by character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.data_source_table_prompts (
    id uuid NOT NULL,
    table_id uuid NOT NULL,
    prompt text NOT NULL,
    created_by character varying(36) NOT NULL,
    updated_by character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.data_source_tables (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    data_source_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    table_id integer NOT NULL,
    table_name character varying(255) NOT NULL,
    description text,
    created_by character varying(36) NOT NULL,
    updated_by character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.data_sources (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    workspace_id uuid,
    name character varying(255) NOT NULL,
    schema_id integer DEFAULT 0 NOT NULL,
    schema_name character varying(255) NOT NULL,
    description text,
    permission character varying(50) DEFAULT 'only_me'::character varying NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying NOT NULL,
    icon_type character varying(255),
    icon text,
    icon_background character varying(255),
    created_by character varying(36) NOT NULL,
    updated_by character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.dataset_collection_bindings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    provider_name character varying(255) NOT NULL,
    model_name character varying(255) NOT NULL,
    collection_name character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    type character varying(40) DEFAULT 'dataset'::character varying NOT NULL
);`,
		`CREATE TABLE public.dataset_folder_joins (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    dataset_id uuid NOT NULL,
    folder_id uuid NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.dataset_folders (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    workspace_id uuid,
    name character varying(255) NOT NULL,
    description text,
    parent_id uuid,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    icon_type character varying(255),
    icon character varying(255),
    "position" integer DEFAULT 0 NOT NULL,
    permission character varying(255) DEFAULT 'only_me'::character varying NOT NULL,
    icon_background character varying(255),
    organization_id uuid
);`,
		`CREATE TABLE public.dataset_metadata_bindings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    metadata_id uuid NOT NULL,
    document_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by uuid NOT NULL
);`,
		`CREATE TABLE public.dataset_metadatas (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tenant_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by uuid NOT NULL,
    updated_by uuid
);`,
		`CREATE TABLE public.dataset_permissions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    dataset_id uuid NOT NULL,
    account_id uuid NOT NULL,
    has_permission boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tenant_id uuid NOT NULL
);`,
		`CREATE TABLE public.dataset_process_rules (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    dataset_id uuid NOT NULL,
    mode character varying(255) DEFAULT 'automatic'::character varying NOT NULL,
    rules text,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.dataset_queries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    dataset_id uuid NOT NULL,
    content text NOT NULL,
    source character varying(255) NOT NULL,
    source_app_id uuid,
    created_by_role character varying NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    results jsonb,
    elapsed_time numeric,
    hit_count integer,
    query_type character varying(50) DEFAULT 'single'::character varying NOT NULL,
    batch_task_id uuid,
    batch_name character varying(255)
);`,
		`CREATE TABLE public.datasets (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    workspace_id uuid,
    name character varying(255) NOT NULL,
    description text,
    provider character varying(255) DEFAULT 'vendor'::character varying NOT NULL,
    permission character varying(255) DEFAULT 'all_team'::character varying NOT NULL,
    data_source_type character varying(255),
    indexing_technique character varying(255),
    index_struct text,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    embedding_model character varying(255) DEFAULT 'text-embedding-ada-002'::character varying,
    embedding_model_provider character varying(255) DEFAULT 'openai'::character varying,
    collection_binding_id uuid,
    retrieval_config jsonb,
    owner uuid,
    icon text,
    icon_background character varying(255),
    built_in_field_enabled boolean DEFAULT false NOT NULL,
    icon_type character varying(255),
    enable_graph_flow boolean DEFAULT false,
    organization_id uuid,
    extraction_strategy character varying(20) DEFAULT 'openie'::character varying,
    segmentation_method character varying(50) DEFAULT 'parent_child'::character varying,
    process_rule jsonb,
    entity_model character varying(255) DEFAULT 'gpt-4o'::character varying,
    entity_model_provider character varying(255) DEFAULT 'openai'::character varying
);`,
		`CREATE TABLE public.document_segment_questions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    document_id uuid NOT NULL,
    segment_id uuid NOT NULL,
    question text NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(255) DEFAULT 'waiting'::character varying NOT NULL,
    indexing_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text
);`,
		`CREATE TABLE public.document_segments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    document_id uuid NOT NULL,
    "position" integer NOT NULL,
    content text NOT NULL,
    word_count integer NOT NULL,
    tokens integer NOT NULL,
    keywords json,
    index_node_id character varying(255),
    index_node_hash character varying(255),
    hit_count integer NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    disabled_at timestamp with time zone,
    disabled_by uuid,
    status character varying(255) DEFAULT 'waiting'::character varying NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    indexing_at timestamp with time zone,
    completed_at timestamp with time zone,
    error text,
    stopped_at timestamp with time zone,
    answer text,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    graph_indexing_status character varying(50) DEFAULT 'pending'::character varying,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.documents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    dataset_id uuid NOT NULL,
    "position" integer NOT NULL,
    data_source_type character varying(255) NOT NULL,
    data_source_info text,
    dataset_process_rule_id uuid,
    batch character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    created_from character varying(255) NOT NULL,
    created_by uuid NOT NULL,
    created_api_request_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processing_started_at timestamp with time zone,
    file_id text,
    word_count integer,
    parsing_completed_at timestamp with time zone,
    cleaning_completed_at timestamp with time zone,
    splitting_completed_at timestamp with time zone,
    tokens integer,
    indexing_latency double precision,
    completed_at timestamp with time zone,
    is_paused boolean DEFAULT false,
    paused_by uuid,
    paused_at timestamp with time zone,
    error text,
    stopped_at timestamp with time zone,
    indexing_status character varying(255) DEFAULT 'waiting'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    disabled_at timestamp with time zone,
    disabled_by uuid,
    archived boolean DEFAULT false NOT NULL,
    archived_reason character varying(255),
    archived_by uuid,
    archived_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    doc_type character varying(40),
    doc_metadata jsonb,
    doc_form character varying(255) DEFAULT 'text_model'::character varying NOT NULL,
    doc_language character varying(255)
);`,
		`CREATE TABLE public.file_favorites (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    file_id uuid NOT NULL,
    account_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.file_folder_joins (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    file_id uuid NOT NULL,
    folder_id uuid NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.file_folder_permissions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    folder_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.file_folders (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    parent_id uuid,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    icon_type character varying(255),
    icon character varying(255),
    icon_background character varying(255),
    "position" integer DEFAULT 0 NOT NULL,
    permission character varying(255) DEFAULT 'only_me'::character varying NOT NULL,
    workspace_id uuid
);`,
		`CREATE TABLE public.graphflow_tasks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    kb_id uuid NOT NULL,
    document_id uuid NOT NULL,
    segment_id uuid,
    extraction_strategy character varying(20) DEFAULT 'llm'::character varying,
    task_type character varying(50) NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    progress integer DEFAULT 0,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    error_message text,
    retry_count integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.kb_entities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kb_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    canonical_name character varying(255) NOT NULL,
    type character varying(100) NOT NULL,
    description text,
    source_count integer DEFAULT 1,
    merged_ids jsonb DEFAULT '[]'::jsonb,
    embedding_id character varying(255),
    graph_node_id character varying(255),
    vector_state character varying(20) DEFAULT 'pending'::character varying,
    graph_state character varying(20) DEFAULT 'pending'::character varying,
    sync_error_log text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.kb_entity_mentions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kb_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    segment_id uuid NOT NULL,
    raw_name character varying(255) NOT NULL,
    raw_type character varying(100),
    confidence double precision DEFAULT 1.0,
    entity_id uuid,
    status character varying(20) DEFAULT 'pending'::character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.kb_relationships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kb_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    head_entity_id uuid NOT NULL,
    tail_entity_id uuid NOT NULL,
    relation_type character varying(100) NOT NULL,
    weight integer DEFAULT 1,
    graph_state character varying(20) DEFAULT 'pending'::character varying,
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.kb_triple_mentions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kb_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    segment_id uuid NOT NULL,
    raw_subject character varying(255) NOT NULL,
    raw_predicate character varying(255) NOT NULL,
    raw_object character varying(255) NOT NULL,
    head_entity_id uuid,
    tail_entity_id uuid,
    status character varying(20) DEFAULT 'pending'::character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.kb_type_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    dataset_id uuid NOT NULL,
    type_key character varying(100) NOT NULL,
    label_zh character varying(100),
    label_en character varying(100),
    style_config jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.tool_files (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    conversation_id uuid,
    file_key character varying(255) NOT NULL,
    mimetype character varying(255) NOT NULL,
    original_url character varying(2048),
    name character varying NOT NULL,
    size integer NOT NULL,
    lifecycle character varying(32) DEFAULT 'persistent'::character varying NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone
);`,
		`CREATE TABLE public.upload_files (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid NOT NULL,
    storage_type character varying(255) NOT NULL,
    key character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    size integer NOT NULL,
    extension character varying(255) NOT NULL,
    mime_type character varying(255),
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    used boolean DEFAULT false NOT NULL,
    used_by uuid,
    used_at timestamp with time zone,
    hash character varying(255),
    created_by_role character varying(255) DEFAULT 'account'::character varying NOT NULL,
    source_url text DEFAULT ''::text NOT NULL,
    content_text text,
    is_archived boolean DEFAULT false,
    archived_at timestamp with time zone,
    archived_by uuid,
    workspace_id uuid,
    is_temporary boolean DEFAULT false NOT NULL
);`,
	},
}
