package baseline

var BillingCommerceSchema = File{
	Name: "50_billing_commerce",
	Statements: []string{
		`CREATE TABLE public.bank_transfer_requests (
    id character varying(255) NOT NULL,
    request_no character varying(50) NOT NULL,
    account_id uuid NOT NULL,
    group_id uuid NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(10) DEFAULT 'CNY'::character varying NOT NULL,
    voucher_key character varying(255) NOT NULL,
    remark text,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    reject_reason text,
    completed_at timestamp with time zone,
    canceled_at timestamp with time zone,
    cancel_reason text,
    client_ip character varying(45),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_btr_amount CHECK ((amount > (0)::numeric))
);`,
		`COMMENT ON TABLE public.bank_transfer_requests IS 'Bank transfer recharge requests table';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.request_no IS 'User-visible request number';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.voucher_key IS 'Voucher storage key (object storage path)';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.status IS 'Request status: pending/approved/rejected/canceled';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.reviewed_by IS 'Reviewer account ID';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.reviewed_at IS 'Review timestamp';`,
		`COMMENT ON COLUMN public.bank_transfer_requests.completed_at IS 'Completion timestamp (when balance is credited)';`,
		`CREATE TABLE public.billing_attempt_entries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    attempt_id character varying(120) NOT NULL,
    entry_type character varying(20) NOT NULL,
    ledger_type character varying(30) NOT NULL,
    ledger_ref_id character varying(120) NOT NULL,
    reserved_amount bigint DEFAULT 0 NOT NULL,
    actual_amount bigint DEFAULT 0 NOT NULL,
    refunded_amount bigint DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    error_code character varying(100),
    error_message text,
    idempotency_key character varying(160),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.billing_attempts (
    attempt_id character varying(120) NOT NULL,
    request_id character varying(100) NOT NULL,
    organization_id uuid NOT NULL,
    lane character varying(20) NOT NULL,
    route_id uuid,
    provider_id uuid,
    model_id uuid,
    quota_subject_type character varying(20) NOT NULL,
    quota_subject_id character varying(64) NOT NULL,
    status character varying(30) NOT NULL,
    invocation_result character varying(20),
    error_code character varying(100),
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    reconcile_attempts integer DEFAULT 0 NOT NULL,
    next_reconcile_at timestamp with time zone,
    last_reconcile_at timestamp with time zone
);`,
		`CREATE TABLE public.channel_wallet_transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    channel_id uuid NOT NULL,
    attempt_id character varying(120),
    type character varying(40) NOT NULL,
    amount bigint NOT NULL,
    balance_before bigint NOT NULL,
    balance_after bigint NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.channel_wallets (
    channel_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    balance bigint DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`,
		`CREATE TABLE public.group_ai_credit_accounts (
    id character varying(255) NOT NULL,
    account_id uuid NOT NULL,
    group_id uuid NOT NULL,
    purchased_credits bigint DEFAULT 0 NOT NULL,
    total_earned bigint DEFAULT 0 NOT NULL,
    total_spent bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.group_ai_credit_accounts IS 'Group AI credit accounts table';`,
		`COMMENT ON COLUMN public.group_ai_credit_accounts.account_id IS 'Account ID (redundant for query convenience)';`,
		`COMMENT ON COLUMN public.group_ai_credit_accounts.group_id IS 'Group ID, credit account is for a specific group';`,
		`COMMENT ON COLUMN public.group_ai_credit_accounts.purchased_credits IS 'Purchased credits balance (no reset)';`,
		`COMMENT ON COLUMN public.group_ai_credit_accounts.total_earned IS 'Total credits earned (cumulative)';`,
		`COMMENT ON COLUMN public.group_ai_credit_accounts.total_spent IS 'Total credits spent (cumulative)';`,
		`CREATE TABLE public.group_wallets (
    id character varying(255) NOT NULL,
    account_id uuid NOT NULL,
    group_id uuid NOT NULL,
    currency character varying(10) DEFAULT 'CNY'::character varying NOT NULL,
    balance numeric(12,2) DEFAULT 0 NOT NULL,
    frozen_balance numeric(12,2) DEFAULT 0 NOT NULL,
    total_recharged numeric(12,2) DEFAULT 0 NOT NULL,
    total_consumed numeric(12,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.group_wallets IS 'Group wallets table for cash balance management';`,
		`COMMENT ON COLUMN public.group_wallets.account_id IS 'Account ID (redundant for query convenience)';`,
		`COMMENT ON COLUMN public.group_wallets.currency IS 'Currency: CNY, USD';`,
		`COMMENT ON COLUMN public.group_wallets.balance IS 'Available balance';`,
		`COMMENT ON COLUMN public.group_wallets.frozen_balance IS 'Frozen balance (pending review, refund processing, etc.)';`,
		`COMMENT ON COLUMN public.group_wallets.total_recharged IS 'Total recharged amount (cumulative)';`,
		`COMMENT ON COLUMN public.group_wallets.total_consumed IS 'Total consumed amount (cumulative)';`,
		`CREATE TABLE public.orders (
    id character varying(255) NOT NULL,
    order_no character varying(50) NOT NULL,
    account_id uuid NOT NULL,
    group_id uuid NOT NULL,
    order_type character varying(30) NOT NULL,
    product_code character varying(50) NOT NULL,
    product_type character varying(30) NOT NULL,
    product_snapshot jsonb NOT NULL,
    original_amount numeric(10,2) NOT NULL,
    discount_amount numeric(10,2) DEFAULT 0 NOT NULL,
    final_amount numeric(10,2) NOT NULL,
    currency character varying(10) DEFAULT 'CNY'::character varying NOT NULL,
    discount_details jsonb,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    paid_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    failure_reason text,
    canceled_at timestamp with time zone,
    cancel_reason text,
    refunded_at timestamp with time zone,
    refund_reason text,
    subscription_id character varying(255),
    client_ip character varying(45),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.orders IS 'Orders table';`,
		`COMMENT ON COLUMN public.orders.group_id IS 'Group ID, order is for a specific group under the user';`,
		`COMMENT ON COLUMN public.orders.order_type IS 'Order type: subscription_new, subscription_renew, subscription_upgrade, credit_purchase';`,
		`COMMENT ON COLUMN public.orders.status IS 'Order status: pending, paid, completed, failed, canceled, refunded';`,
		`CREATE TABLE public.payment_callbacks (
    id character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    payment_method character varying(30) NOT NULL,
    callback_type character varying(20) NOT NULL,
    request_headers jsonb,
    request_body text,
    response_status integer,
    response_body text,
    is_verified boolean DEFAULT false NOT NULL,
    verification_error text,
    processed boolean DEFAULT false NOT NULL,
    processed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.payment_callbacks IS 'Payment callbacks log table';`,
		`COMMENT ON COLUMN public.payment_callbacks.callback_type IS 'Callback type: notify, return';`,
		`CREATE TABLE public.payment_transactions (
    id character varying(255) NOT NULL,
    transaction_no character varying(100) NOT NULL,
    order_id character varying(255) NOT NULL,
    account_id uuid NOT NULL,
    payment_method character varying(30) NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(10) DEFAULT 'CNY'::character varying NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    provider_transaction_id character varying(255),
    provider_response jsonb,
    paid_at timestamp with time zone,
    failed_at timestamp with time zone,
    failure_reason text,
    client_ip character varying(45),
    user_agent text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.payment_transactions IS 'Payment transactions table';`,
		`COMMENT ON COLUMN public.payment_transactions.status IS 'Status: pending, processing, success, failed, canceled';`,
		`CREATE TABLE public.quota_usage_history (
    id character varying(255) NOT NULL,
    group_id uuid NOT NULL,
    account_id uuid NOT NULL,
    tenant_id uuid,
    resource_type character varying(50) NOT NULL,
    operation_type character varying(20) NOT NULL,
    delta bigint NOT NULL,
    value_before bigint NOT NULL,
    value_after bigint NOT NULL,
    resource_id character varying(255),
    resource_name character varying(500),
    metadata jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.quota_usage_history IS '配额使用历史记录表';`,
		`COMMENT ON COLUMN public.quota_usage_history.group_id IS '组织ID';`,
		`COMMENT ON COLUMN public.quota_usage_history.account_id IS '操作账号ID';`,
		`COMMENT ON COLUMN public.quota_usage_history.tenant_id IS '部门ID(可选)';`,
		`COMMENT ON COLUMN public.quota_usage_history.resource_type IS '资源类型: seats, storage, db_rows, knowledge_bases, ai_agents, workflows, workflow_executions';`,
		`COMMENT ON COLUMN public.quota_usage_history.operation_type IS '操作类型: increase(增加), decrease(减少)';`,
		`COMMENT ON COLUMN public.quota_usage_history.delta IS '变化量,正数表示增加,负数表示减少';`,
		`COMMENT ON COLUMN public.quota_usage_history.value_before IS '变化前的值';`,
		`COMMENT ON COLUMN public.quota_usage_history.value_after IS '变化后的值';`,
		`COMMENT ON COLUMN public.quota_usage_history.resource_id IS '关联的资源ID(如文件ID、知识库ID等)';`,
		`COMMENT ON COLUMN public.quota_usage_history.resource_name IS '资源名称';`,
		`COMMENT ON COLUMN public.quota_usage_history.metadata IS '详细元数据,JSON格式,包含操作的详细信息';`,
		`CREATE TABLE public.refund_records (
    id character varying(255) NOT NULL,
    refund_no character varying(100) NOT NULL,
    order_id character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    account_id uuid NOT NULL,
    refund_amount numeric(10,2) NOT NULL,
    currency character varying(10) DEFAULT 'CNY'::character varying NOT NULL,
    refund_fee numeric(10,2) DEFAULT 0 NOT NULL,
    original_transaction_amount numeric(10,2) NOT NULL,
    refund_reason text NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    provider_refund_id character varying(255),
    provider_response jsonb,
    processing_at timestamp with time zone,
    success_at timestamp with time zone,
    failed_at timestamp with time zone,
    failure_reason text,
    operator_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.refund_records IS 'Refund records table';`,
		`COMMENT ON COLUMN public.refund_records.status IS 'Status: pending, processing, success, failed';`,
		`CREATE TABLE public.sales_contact_requests (
    id character varying(255) NOT NULL,
    account_id uuid,
    company_name character varying(255) NOT NULL,
    contact_name character varying(100) NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(255),
    extra_meta jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`CREATE TABLE public.transactions (
    id character varying(255) NOT NULL,
    batch_id character varying(255) NOT NULL,
    group_id uuid NOT NULL,
    tenant_id uuid,
    currency_type character varying(20) NOT NULL,
    transaction_type character varying(30) NOT NULL,
    amount numeric(20,4) NOT NULL,
    balance_before numeric(20,4) NOT NULL,
    balance_after numeric(20,4) NOT NULL,
    currency character varying(10),
    reference_type character varying(50),
    reference_id character varying(255),
    description character varying(500),
    transaction_detail jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);`,
		`COMMENT ON TABLE public.transactions IS 'Unified transaction records table for cash and credits';`,
		`COMMENT ON COLUMN public.transactions.batch_id IS 'Batch ID, multiple records from same business operation share this ID';`,
		`COMMENT ON COLUMN public.transactions.currency_type IS 'Currency type: cash / subscription_credits / purchased_credits';`,
		`COMMENT ON COLUMN public.transactions.transaction_type IS 'Transaction type: recharge, subscription_payment, ai_usage, etc.';`,
		`COMMENT ON COLUMN public.transactions.amount IS 'Amount change (positive for income, negative for expense)';`,
		`COMMENT ON COLUMN public.transactions.reference_type IS 'Reference type: order / subscription / refund';`,
	},
}
