package baseline

var IndexesSchema = File{
	Name: "90_indexes",
	Statements: []string{
		`CREATE INDEX account_email_idx ON public.accounts USING btree (email);`,
		`CREATE INDEX agents_agents_id_idx ON public.agents_configs USING btree (agents_id);`,
		`CREATE INDEX agents_conversations_agent_id_idx ON public.agents_conversations USING btree (agent_id);`,
		`CREATE INDEX agents_message_agents_id_idx ON public.agents_messages USING btree (agent_id, created_at);`,
		`CREATE INDEX agents_message_conversation_id_idx ON public.agents_messages USING btree (conversation_id, workflow_run_id);`,
		`CREATE INDEX agents_message_created_at_idx ON public.agents_messages USING btree (created_at);`,
		`CREATE INDEX agents_message_end_user_idx ON public.agents_messages USING btree (agent_id, from_source, from_end_user_id);`,
		`CREATE INDEX agents_message_workflow_run_id_idx ON public.agents_messages USING btree (conversation_id, workflow_run_id);`,
		`CREATE INDEX agents_messages_conversation_id_idx ON public.agents_messages USING btree (conversation_id);`,
		`CREATE INDEX agents_tenant_id_idx ON public.agents USING btree (tenant_id);`,
		`CREATE INDEX batch_hit_testing_tasks_dataset_id_idx ON public.batch_hit_testing_tasks USING btree (dataset_id);`,
		`CREATE INDEX child_chunk_organization_id_idx ON public.child_chunks USING btree (organization_id, dataset_id);`,
		`CREATE INDEX child_chunks_document_id_idx ON public.child_chunks USING btree (document_id);`,
		`CREATE INDEX child_chunks_segment_id_idx ON public.child_chunks USING btree (segment_id);`,
		`CREATE INDEX conversation_app_id_idx ON public.conversations USING btree (app_id);`,
		`CREATE INDEX conversation_from_user_idx ON public.agents_conversations USING btree (agent_id, from_source, from_end_user_id);`,
		`CREATE INDEX conversation_group_app_id_idx ON public.conversation_group USING btree (app_id);`,
		`CREATE INDEX dataset_folder_joins_dataset_id_idx ON public.dataset_folder_joins USING btree (dataset_id);`,
		`CREATE INDEX dataset_folder_joins_folder_id_idx ON public.dataset_folder_joins USING btree (folder_id);`,
		`CREATE INDEX dataset_folder_organization_id_idx ON public.dataset_folders USING btree (organization_id);`,
		`CREATE INDEX dataset_folders_tenant_id_idx ON public.dataset_folders USING btree (workspace_id);`,
		`CREATE INDEX dataset_metadata_bindings_dataset_id_idx ON public.dataset_metadata_bindings USING btree (dataset_id);`,
		`CREATE INDEX dataset_metadata_bindings_metadata_id_idx ON public.dataset_metadata_bindings USING btree (metadata_id);`,
		`CREATE INDEX dataset_metadatas_dataset_id_idx ON public.dataset_metadatas USING btree (dataset_id);`,
		`CREATE INDEX dataset_metadatas_tenant_id_idx ON public.dataset_metadatas USING btree (tenant_id);`,
		`CREATE INDEX dataset_organization_id_idx ON public.datasets USING btree (organization_id);`,
		`CREATE INDEX idx_datasets_organization_workspace_created ON public.datasets USING btree (organization_id, workspace_id, created_at DESC);`,
		`CREATE INDEX dataset_permissions_account_id_idx ON public.dataset_permissions USING btree (account_id);`,
		`CREATE INDEX dataset_permissions_dataset_id_idx ON public.dataset_permissions USING btree (dataset_id);`,
		`CREATE INDEX dataset_process_rules_dataset_id_idx ON public.dataset_process_rules USING btree (dataset_id);`,
		`CREATE INDEX dataset_queries_batch_task_id_idx ON public.dataset_queries USING btree (batch_task_id);`,
		`CREATE INDEX dataset_queries_dataset_id_idx ON public.dataset_queries USING btree (dataset_id);`,
		`CREATE INDEX dataset_tenant_id_idx ON public.datasets USING btree (workspace_id);`,
		`CREATE INDEX document_organization_id_idx ON public.documents USING btree (organization_id);`,
		`CREATE INDEX document_segment_organization_id_idx ON public.document_segments USING btree (organization_id);`,
		`CREATE INDEX document_segment_question_organization_id_idx ON public.document_segment_questions USING btree (organization_id);`,
		`CREATE INDEX document_segment_questions_dataset_id_idx ON public.document_segment_questions USING btree (dataset_id);`,
		`CREATE INDEX document_segment_questions_document_id_idx ON public.document_segment_questions USING btree (document_id);`,
		`CREATE INDEX document_segment_questions_segment_id_idx ON public.document_segment_questions USING btree (segment_id);`,
		`CREATE INDEX document_segment_questions_status_idx ON public.document_segment_questions USING btree (status);`,
		`CREATE INDEX document_segments_dataset_id_idx ON public.document_segments USING btree (dataset_id);`,
		`CREATE INDEX document_segments_document_id_idx ON public.document_segments USING btree (document_id);`,
		`CREATE INDEX documents_dataset_id_idx ON public.documents USING btree (dataset_id);`,
		`CREATE INDEX end_user_session_id_idx ON public.end_users USING btree (session_id, type);`,
		`CREATE INDEX end_user_tenant_session_id_idx ON public.end_users USING btree (tenant_id, session_id, type);`,
		`CREATE INDEX file_favorites_account_id_idx ON public.file_favorites USING btree (account_id);`,
		`CREATE INDEX file_favorites_file_id_idx ON public.file_favorites USING btree (file_id);`,
		`CREATE INDEX file_folder_assoc_file_idx ON public.file_folder_joins USING btree (file_id);`,
		`CREATE INDEX file_folder_assoc_folder_idx ON public.file_folder_joins USING btree (folder_id);`,
		`CREATE UNIQUE INDEX file_folder_joins_file_id_unique ON public.file_folder_joins USING btree (file_id);`,
		`CREATE INDEX file_folder_organization_idx ON public.file_folders USING btree (organization_id);`,
		`CREATE INDEX file_folder_parent_idx ON public.file_folders USING btree (parent_id);`,
		`CREATE INDEX file_folder_permission_folder_idx ON public.file_folder_permissions USING btree (folder_id);`,
		`CREATE INDEX file_folder_permission_workspace_idx ON public.file_folder_permissions USING btree (workspace_id);`,
		`CREATE INDEX file_folders_team_tenant_id_idx ON public.file_folders USING btree (workspace_id);`,
		`CREATE UNIQUE INDEX idx_account_group_credit ON public.group_ai_credit_accounts USING btree (account_id, group_id);`,
		`CREATE INDEX idx_account_plugin_installations_plugin ON public.account_plugin_installations USING btree (tenant_id, marketplace_plugin_id);`,
		`CREATE INDEX idx_account_plugin_installations_tenant ON public.account_plugin_installations USING btree (tenant_id);`,
		`CREATE INDEX idx_account_plugin_installations_version ON public.account_plugin_installations USING btree (marketplace_version_id);`,
		`CREATE INDEX idx_accounts_deleted_at ON public.accounts USING btree (deleted_at);`,
		`CREATE UNIQUE INDEX idx_accounts_email_unique_nonempty ON public.accounts USING btree (lower((email)::text)) WHERE (TRIM(BOTH FROM COALESCE(email, ''::character varying)) <> ''::text);`,
		`CREATE UNIQUE INDEX idx_accounts_mobile_e164_unique ON public.accounts USING btree (mobile_e164) WHERE (TRIM(BOTH FROM COALESCE(mobile_e164, ''::character varying)) <> ''::text);`,
		`CREATE INDEX idx_ae_agent_permission ON public.agent_extensions USING btree (agent_id, permission);`,
		`CREATE INDEX idx_agent_api_key_usage_logs_agent_id ON public.agent_api_key_usage_logs USING btree (agent_id);`,
		`CREATE INDEX idx_agent_api_key_usage_logs_api_key_created ON public.agent_api_key_usage_logs USING btree (api_key_id, created_at);`,
		`CREATE INDEX idx_agent_api_key_usage_logs_api_key_id ON public.agent_api_key_usage_logs USING btree (api_key_id);`,
		`CREATE INDEX idx_agent_api_key_usage_logs_created_at ON public.agent_api_key_usage_logs USING btree (created_at);`,
		`CREATE INDEX idx_agent_api_keys_agent_id ON public.agent_api_keys USING btree (agent_id);`,
		`CREATE INDEX idx_agent_api_keys_agent_tenant ON public.agent_api_keys USING btree (agent_id, tenant_id);`,
		`CREATE INDEX idx_agent_api_keys_expires_at ON public.agent_api_keys USING btree (expires_at);`,
		`CREATE INDEX idx_agent_api_keys_key_hash ON public.agent_api_keys USING btree (key_hash);`,
		`CREATE INDEX idx_agent_api_keys_status ON public.agent_api_keys USING btree (status);`,
		`CREATE INDEX idx_agent_api_keys_tenant_id ON public.agent_api_keys USING btree (tenant_id);`,
		`CREATE INDEX idx_agent_extensions_permission ON public.agent_extensions USING btree (permission);`,
		`CREATE INDEX idx_agents_conversations_web_app_id ON public.agents_conversations USING btree (web_app_id);`,
		`CREATE INDEX idx_agents_created_at_desc ON public.agents USING btree (created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_agents_created_by ON public.agents USING btree (created_by) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_agents_deleted_at ON public.agents USING btree (deleted_at);`,
		`CREATE INDEX idx_agents_internal ON public.agents USING btree (internal) WHERE (internal = true);`,
		`CREATE INDEX idx_agents_internal_tenant ON public.agents USING btree (internal, tenant_id) WHERE (internal = true);`,
		`CREATE INDEX idx_agents_messages_web_app_id ON public.agents_messages USING btree (web_app_id);`,
		`CREATE INDEX idx_agents_tenant ON public.agents USING btree (tenant_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_agents_tenant_created_at ON public.agents USING btree (tenant_id, created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE UNIQUE INDEX idx_agents_web_app_id ON public.agents USING btree (web_app_id);`,
		`CREATE INDEX idx_agents_web_app_status ON public.agents USING btree (web_app_status) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_conversations_active_message ON public.aichat_conversations USING btree (active_message_id) WHERE ((active_message_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_aichat_conversations_owner_updated ON public.aichat_conversations USING btree (organization_id, account_id, updated_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_conversations_runtime_status ON public.aichat_conversations USING btree (runtime_status) WHERE (deleted_at IS NULL);`,
		`CREATE UNIQUE INDEX idx_aichat_conversations_source_conversation ON public.aichat_conversations USING btree (source_conversation_id) WHERE ((source_conversation_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_aichat_conversations_source_web_app ON public.aichat_conversations USING btree (source_web_app_id) WHERE ((source_web_app_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_aichat_conversations_workspace ON public.aichat_conversations USING btree (workspace_id) WHERE (deleted_at IS NULL);`,
		`CREATE UNIQUE INDEX idx_aichat_custom_skills_org_skill_active ON public.aichat_custom_skills USING btree (organization_id, skill_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_custom_skills_org_status ON public.aichat_custom_skills USING btree (organization_id, status) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_messages_billing_reason_source ON public.aichat_messages USING btree (billing_reason_source) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_messages_conversation_created ON public.aichat_messages USING btree (conversation_id, created_at) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_aichat_messages_parent ON public.aichat_messages USING btree (parent_id) WHERE ((parent_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE UNIQUE INDEX idx_aichat_messages_source_message ON public.aichat_messages USING btree (source_message_id) WHERE ((source_message_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_aichat_organization_skill_configs_enabled ON public.aichat_organization_skill_configs USING btree (organization_id, enabled);`,
		`CREATE INDEX idx_app_prompt_versions_prompt ON public.app_prompt_versions USING btree (prompt_id, version DESC);`,
		`CREATE INDEX idx_app_prompts_org_workspace_source ON public.app_prompts USING btree (organization_id, workspace_id, source);`,
		`CREATE INDEX idx_app_prompts_slug_locale ON public.app_prompts USING btree (slug, locale);`,
		`CREATE INDEX idx_automation_action_runs_task_action_id_created_at ON public.automation_action_runs USING btree (task_action_id, created_at DESC);`,
		`CREATE INDEX idx_automation_action_runs_task_run_id_created_at ON public.automation_action_runs USING btree (task_run_id, created_at);`,
		`CREATE INDEX idx_automation_task_actions_task_id_action_order ON public.automation_task_actions USING btree (task_id, action_order);`,
		`CREATE INDEX idx_automation_task_runs_task_id_created_at ON public.automation_task_runs USING btree (task_id, created_at DESC);`,
		`CREATE INDEX idx_automation_task_runs_task_id_scheduled_for ON public.automation_task_runs USING btree (task_id, scheduled_for);`,
		`CREATE INDEX idx_automation_tasks_scope_next_run_at ON public.automation_tasks USING btree (organization_id, workspace_id, next_run_at);`,
		`CREATE INDEX idx_automation_tasks_scope_status_updated_at ON public.automation_tasks USING btree (organization_id, workspace_id, status, updated_at DESC);`,
		`CREATE INDEX idx_automation_tasks_status_next_run_at ON public.automation_tasks USING btree (status, next_run_at);`,
		`CREATE INDEX idx_batch_hit_testing_tasks_organization_id ON public.batch_hit_testing_tasks USING btree (organization_id);`,
		`CREATE INDEX idx_billing_attempt_entries_attempt ON public.billing_attempt_entries USING btree (attempt_id);`,
		`CREATE INDEX idx_billing_attempt_entries_status ON public.billing_attempt_entries USING btree (status);`,
		`CREATE INDEX idx_billing_attempts_org_created ON public.billing_attempts USING btree (organization_id, created_at DESC);`,
		`CREATE INDEX idx_billing_attempts_reconcile_queue ON public.billing_attempts USING btree (status, lane, next_reconcile_at, updated_at);`,
		`CREATE INDEX idx_billing_attempts_request_id ON public.billing_attempts USING btree (request_id);`,
		`CREATE INDEX idx_billing_attempts_status ON public.billing_attempts USING btree (status);`,
		`CREATE INDEX idx_btr_account ON public.bank_transfer_requests USING btree (account_id);`,
		`CREATE INDEX idx_btr_created_at ON public.bank_transfer_requests USING btree (created_at);`,
		`CREATE INDEX idx_btr_group ON public.bank_transfer_requests USING btree (group_id);`,
		`CREATE UNIQUE INDEX idx_btr_request_no ON public.bank_transfer_requests USING btree (request_no);`,
		`CREATE INDEX idx_btr_reviewed_by ON public.bank_transfer_requests USING btree (reviewed_by);`,
		`CREATE INDEX idx_btr_status ON public.bank_transfer_requests USING btree (status);`,
		`CREATE INDEX idx_callback_created_at ON public.payment_callbacks USING btree (created_at);`,
		`CREATE INDEX idx_callback_method ON public.payment_callbacks USING btree (payment_method);`,
		`CREATE INDEX idx_callback_processed ON public.payment_callbacks USING btree (processed);`,
		`CREATE INDEX idx_callback_transaction ON public.payment_callbacks USING btree (transaction_id);`,
		`CREATE INDEX idx_channel_wallet_transactions_attempt ON public.channel_wallet_transactions USING btree (attempt_id, created_at DESC);`,
		`CREATE INDEX idx_channel_wallet_transactions_channel ON public.channel_wallet_transactions USING btree (channel_id, created_at DESC);`,
		`CREATE INDEX idx_channel_wallets_org_status ON public.channel_wallets USING btree (organization_id, status);`,
		`CREATE INDEX idx_content_parse_artifacts_deleted_at ON public.content_parse_artifacts USING btree (deleted_at);`,
		`CREATE INDEX idx_content_parse_chunk_artifact_sets_deleted_at ON public.content_parse_chunk_artifact_sets USING btree (deleted_at);`,
		`CREATE INDEX idx_content_parse_chunk_artifact_sets_parse_artifact ON public.content_parse_chunk_artifact_sets USING btree (parse_artifact_id, created_at DESC);`,
		`CREATE INDEX idx_content_parse_chunk_artifact_sets_parse_run ON public.content_parse_chunk_artifact_sets USING btree (parse_run_id, created_at DESC);`,
		`CREATE INDEX idx_content_parse_chunk_artifact_sets_source_hash ON public.content_parse_chunk_artifact_sets USING btree (source_content_hash, use_case, created_at DESC);`,
		`CREATE INDEX idx_content_parse_chunking_artifact_set ON public.content_parse_chunking_runs USING btree (chunk_artifact_set_id);`,
		`CREATE INDEX idx_content_parse_chunking_runs_parse_created ON public.content_parse_chunking_runs USING btree (parse_run_id, created_at DESC);`,
		`CREATE INDEX idx_content_parse_chunking_runs_use_case_created ON public.content_parse_chunking_runs USING btree (use_case, created_at DESC);`,
		`CREATE INDEX idx_content_parse_playground_runs_deleted_at ON public.content_parse_playground_runs USING btree (deleted_at);`,
		`CREATE INDEX idx_content_parse_playground_runs_hash_created ON public.content_parse_playground_runs USING btree (source_content_hash, created_at DESC);`,
		`CREATE INDEX idx_content_parse_playground_runs_hash_provider_created ON public.content_parse_playground_runs USING btree (source_content_hash, final_provider_key, profile, created_at DESC);`,
		`CREATE INDEX idx_content_parse_playground_runs_source_storage ON public.content_parse_playground_runs USING btree (source_content_hash, source_storage_type) WHERE (source_storage_key IS NOT NULL);`,
		`CREATE INDEX idx_content_parse_playground_runs_workspace_created ON public.content_parse_playground_runs USING btree (workspace_id, created_at DESC);`,
		`CREATE INDEX idx_content_parse_provider_configs_deleted_at ON public.content_parse_provider_configs USING btree (deleted_at);`,
		`CREATE INDEX idx_content_parse_provider_configs_scope_enabled_priority ON public.content_parse_provider_configs USING btree (scope, workspace_id, enabled, priority);`,
		`CREATE INDEX idx_content_parse_provider_health_checks_provider_checked ON public.content_parse_provider_health_checks USING btree (provider_config_id, checked_at DESC);`,
		`CREATE INDEX idx_content_parse_provider_health_checks_status_checked ON public.content_parse_provider_health_checks USING btree (status, checked_at DESC);`,
		`CREATE INDEX idx_content_parse_route_policies_deleted_at ON public.content_parse_route_policies USING btree (deleted_at);`,
		`CREATE INDEX idx_content_parse_route_policy_rules_policy_order ON public.content_parse_route_policy_rules USING btree (policy_id, sort_order);`,
		`CREATE INDEX idx_content_parse_runs_dataset_document_created ON public.content_parse_runs USING btree (dataset_id, document_id, created_at DESC);`,
		`CREATE INDEX idx_content_parse_runs_provider_created ON public.content_parse_runs USING btree (final_provider_key, created_at DESC);`,
		`CREATE INDEX idx_content_parse_runs_status_quality_created ON public.content_parse_runs USING btree (status, quality_level, created_at DESC);`,
		`CREATE INDEX idx_content_parse_runs_workspace_created ON public.content_parse_runs USING btree (workspace_id, created_at DESC);`,
		`CREATE INDEX idx_credential_active ON public.llm_credentials USING btree (is_active);`,
		`CREATE INDEX idx_credential_deleted ON public.llm_credentials USING btree (deleted_at);`,
		`CREATE INDEX idx_credential_hash ON public.llm_credentials USING btree (api_key_hash);`,
		`CREATE INDEX idx_credential_protocol ON public.llm_credentials USING btree (protocol);`,
		`CREATE INDEX idx_credential_provider ON public.llm_credentials USING btree (provider);`,
		`CREATE INDEX idx_credential_tenant ON public.llm_credentials USING btree (organization_id);`,
		`CREATE INDEX idx_credit_account ON public.group_ai_credit_accounts USING btree (account_id);`,
		`CREATE INDEX idx_credit_group ON public.group_ai_credit_accounts USING btree (group_id);`,
		`CREATE INDEX idx_data_library_assets_content_hash ON public.data_library_document_assets USING btree (content_hash);`,
		`CREATE INDEX idx_data_library_assets_deleted_at ON public.data_library_document_assets USING btree (deleted_at);`,
		`CREATE INDEX idx_data_library_assets_org_workspace_status ON public.data_library_document_assets USING btree (organization_id, workspace_id, status, updated_at DESC);`,
		`CREATE INDEX idx_data_library_assets_source_file ON public.data_library_document_assets USING btree (source_file_id);`,
		`CREATE INDEX idx_data_library_db_asset_refs_asset ON public.data_library_database_asset_refs USING btree (asset_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_extraction ON public.data_library_database_asset_refs USING btree (extraction_artifact_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_org_source ON public.data_library_database_asset_refs USING btree (organization_id, data_source_id, status) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_parse ON public.data_library_database_asset_refs USING btree (parse_artifact_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_table ON public.data_library_database_asset_refs USING btree (table_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_version ON public.data_library_database_asset_refs USING btree (version_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_db_asset_refs_workspace ON public.data_library_database_asset_refs USING btree (workspace_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_asset_created ON public.data_library_extraction_artifacts USING btree (asset_id, created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_content_hash ON public.data_library_extraction_artifacts USING btree (content_hash) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_org_status ON public.data_library_extraction_artifacts USING btree (organization_id, status, created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_parse ON public.data_library_extraction_artifacts USING btree (parse_artifact_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_schema_hash ON public.data_library_extraction_artifacts USING btree (schema_hash) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_source ON public.data_library_extraction_artifacts USING btree (data_source_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_table ON public.data_library_extraction_artifacts USING btree (table_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_version ON public.data_library_extraction_artifacts USING btree (version_id, created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_extraction_artifacts_workspace ON public.data_library_extraction_artifacts USING btree (workspace_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_asset ON public.data_library_knowledge_base_asset_refs USING btree (asset_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_chunk_set ON public.data_library_knowledge_base_asset_refs USING btree (chunk_artifact_set_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_org_dataset ON public.data_library_knowledge_base_asset_refs USING btree (organization_id, dataset_id, status) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_vector ON public.data_library_knowledge_base_asset_refs USING btree (vector_artifact_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_version ON public.data_library_knowledge_base_asset_refs USING btree (version_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_kb_asset_refs_workspace ON public.data_library_knowledge_base_asset_refs USING btree (workspace_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_processing_requests_asset_created ON public.data_library_processing_requests USING btree (asset_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_processing_requests_deleted_at ON public.data_library_processing_requests USING btree (deleted_at);`,
		`CREATE INDEX idx_data_library_processing_requests_executor_status ON public.data_library_processing_requests USING btree (executor_key, status, created_at DESC) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_data_library_processing_requests_org_status ON public.data_library_processing_requests USING btree (organization_id, status, created_at DESC);`,
		`CREATE INDEX idx_data_library_processing_requests_workspace ON public.data_library_processing_requests USING btree (workspace_id);`,
		`CREATE INDEX idx_data_library_reuse_events_artifact ON public.data_library_reuse_events USING btree (artifact_type, artifact_id);`,
		`CREATE INDEX idx_data_library_reuse_events_asset_created ON public.data_library_reuse_events USING btree (asset_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_reuse_events_deleted_at ON public.data_library_reuse_events USING btree (deleted_at);`,
		`CREATE INDEX idx_data_library_reuse_events_org_consumer ON public.data_library_reuse_events USING btree (organization_id, consumer_type, consumer_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_reuse_events_version ON public.data_library_reuse_events USING btree (version_id);`,
		`CREATE INDEX idx_data_library_reuse_events_workspace ON public.data_library_reuse_events USING btree (workspace_id);`,
		`CREATE INDEX idx_data_library_vector_artifacts_asset_created ON public.data_library_vector_artifacts USING btree (asset_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_vector_artifacts_chunk_set ON public.data_library_vector_artifacts USING btree (chunk_artifact_set_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_vector_artifacts_content_hash ON public.data_library_vector_artifacts USING btree (content_hash);`,
		`CREATE INDEX idx_data_library_vector_artifacts_deleted_at ON public.data_library_vector_artifacts USING btree (deleted_at);`,
		`CREATE INDEX idx_data_library_vector_artifacts_org_status ON public.data_library_vector_artifacts USING btree (organization_id, status, created_at DESC);`,
		`CREATE INDEX idx_data_library_vector_artifacts_version ON public.data_library_vector_artifacts USING btree (version_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_vector_artifacts_workspace ON public.data_library_vector_artifacts USING btree (workspace_id);`,
		`CREATE INDEX idx_data_library_versions_asset_created ON public.data_library_document_versions USING btree (asset_id, created_at DESC);`,
		`CREATE INDEX idx_data_library_versions_chunk_artifact ON public.data_library_document_versions USING btree (chunk_artifact_set_id);`,
		`CREATE INDEX idx_data_library_versions_content_hash ON public.data_library_document_versions USING btree (content_hash);`,
		`CREATE INDEX idx_data_library_versions_deleted_at ON public.data_library_document_versions USING btree (deleted_at);`,
		`CREATE INDEX idx_data_library_versions_parse_artifact ON public.data_library_document_versions USING btree (parse_artifact_id);`,
		`CREATE INDEX idx_data_library_versions_source_file ON public.data_library_document_versions USING btree (source_file_id);`,
		`CREATE INDEX idx_data_source_import_job_errors_job_row ON public.data_source_import_job_errors USING btree (job_id, row_index);`,
		`CREATE INDEX idx_data_source_import_jobs_scope_created_at ON public.data_source_import_jobs USING btree (organization_id, data_source_id, created_at DESC);`,
		`CREATE INDEX idx_data_source_import_jobs_status_created_at ON public.data_source_import_jobs USING btree (status, created_at DESC);`,
		`CREATE INDEX idx_data_source_sql_operations_created_at ON public.data_source_sql_operations USING btree (created_at);`,
		`CREATE INDEX idx_data_source_sql_operations_data_source_id ON public.data_source_sql_operations USING btree (data_source_id);`,
		`CREATE INDEX idx_data_source_sql_operations_organization_id ON public.data_source_sql_operations USING btree (organization_id);`,
		`CREATE INDEX idx_data_source_sql_operations_table_id ON public.data_source_sql_operations USING btree (table_id);`,
		`CREATE INDEX idx_data_source_tables_data_source_id ON public.data_source_tables USING btree (data_source_id);`,
		`CREATE INDEX idx_data_source_tables_name ON public.data_source_tables USING btree (name);`,
		`CREATE INDEX idx_data_source_tables_organization_id ON public.data_source_tables USING btree (organization_id);`,
		`CREATE INDEX idx_data_sources_organization_id ON public.data_sources USING btree (organization_id);`,
		`CREATE INDEX idx_datasets_segmentation_method ON public.datasets USING btree (segmentation_method);`,
		`CREATE INDEX idx_dept_group_id ON public.departments USING btree (group_id);`,
		`CREATE INDEX idx_dept_parent_id ON public.departments USING btree (parent_id);`,
		`CREATE INDEX idx_dept_sort ON public.departments USING btree (group_id, parent_id, sort_order);`,
		`CREATE INDEX idx_dept_status ON public.departments USING btree (status);`,
		`CREATE INDEX idx_dm_account_id ON public.department_members USING btree (account_id);`,
		`CREATE INDEX idx_dm_department_id ON public.department_members USING btree (department_id);`,
		`CREATE INDEX idx_document_segments_deleted ON public.document_segments USING btree (is_deleted) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_document_segments_deleted_at ON public.document_segments USING btree (deleted_at);`,
		`CREATE INDEX idx_document_segments_graph_status ON public.document_segments USING btree (graph_indexing_status);`,
		`CREATE INDEX idx_document_segments_is_deleted ON public.document_segments USING btree (is_deleted) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_egaj_status ON public.members USING btree (status);`,
		`CREATE INDEX idx_egps_account_id ON public.enterprise_group_plugin_subscriptions USING btree (account_id);`,
		`CREATE INDEX idx_egps_enabled ON public.enterprise_group_plugin_subscriptions USING btree (group_id, enabled) WHERE (enabled = true);`,
		`CREATE INDEX idx_egps_group_id ON public.enterprise_group_plugin_subscriptions USING btree (group_id);`,
		`CREATE INDEX idx_egps_installation_id ON public.enterprise_group_plugin_subscriptions USING btree (installation_id);`,
		`CREATE INDEX idx_egps_plugin_id ON public.enterprise_group_plugin_subscriptions USING btree (plugin_id);`,
		`CREATE INDEX idx_eil_department_id ON public.organization_invite_links USING btree (department_id);`,
		`CREATE INDEX idx_eil_expires_at ON public.organization_invite_links USING btree (expires_at);`,
		`CREATE INDEX idx_eil_group_id ON public.organization_invite_links USING btree (group_id);`,
		`CREATE INDEX idx_eil_status ON public.organization_invite_links USING btree (status);`,
		`CREATE INDEX idx_ejr_account_id ON public.organization_join_requests USING btree (account_id);`,
		`CREATE INDEX idx_ejr_department_id ON public.organization_join_requests USING btree (department_id);`,
		`CREATE INDEX idx_ejr_group_id ON public.organization_join_requests USING btree (group_id);`,
		`CREATE INDEX idx_ejr_status ON public.organization_join_requests USING btree (status);`,
		`CREATE INDEX idx_entities_sync_check ON public.kb_entities USING btree (kb_id, vector_state, graph_state);`,
		`CREATE INDEX idx_entities_tenant ON public.kb_entities USING btree (tenant_id);`,
		`CREATE UNIQUE INDEX idx_entities_unique_identity ON public.kb_entities USING btree (kb_id, canonical_name) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_entity_mentions_deleted ON public.kb_entity_mentions USING btree (is_deleted) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_gdpr_audit_logs_action_type ON public.gdpr_audit_logs USING btree (action_type);`,
		`CREATE INDEX idx_gdpr_audit_logs_actor_id ON public.gdpr_audit_logs USING btree (actor_id);`,
		`CREATE INDEX idx_gdpr_audit_logs_created_at ON public.gdpr_audit_logs USING btree (created_at);`,
		`CREATE INDEX idx_gdpr_audit_logs_subject_id ON public.gdpr_audit_logs USING btree (subject_id);`,
		`CREATE INDEX idx_gdpr_audit_logs_tenant_id ON public.gdpr_audit_logs USING btree (tenant_id);`,
		`CREATE INDEX idx_graphflow_tasks_document ON public.graphflow_tasks USING btree (document_id, task_type);`,
		`CREATE INDEX idx_graphflow_tasks_pending ON public.graphflow_tasks USING btree (kb_id, status) WHERE ((status)::text = ANY (ARRAY[('pending'::character varying)::text, ('processing'::character varying)::text]));`,
		`CREATE INDEX idx_graphflow_tasks_tenant ON public.graphflow_tasks USING btree (tenant_id);`,
		`CREATE INDEX idx_installed_plugin_info_marketplace_plugin ON public.installed_plugin_info USING btree (marketplace_plugin_id);`,
		`CREATE INDEX idx_installed_plugin_info_plugin_name ON public.installed_plugin_info USING btree (plugin_name);`,
		`CREATE INDEX idx_kb_graph_flow ON public.datasets USING btree (enable_graph_flow) WHERE (enable_graph_flow = true);`,
		`CREATE INDEX idx_llm_credentials_org_hash ON public.llm_credentials USING btree (organization_id, api_key_hash) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_llm_credentials_organization_id ON public.llm_credentials USING btree (organization_id);`,
		`CREATE INDEX idx_llm_custom_models_organization_id ON public.llm_custom_models USING btree (organization_id);`,
		`CREATE INDEX idx_llm_custom_providers_organization_id ON public.llm_custom_providers USING btree (organization_id);`,
		`CREATE INDEX idx_llm_default_models_deleted_at ON public.llm_default_models USING btree (deleted_at);`,
		`CREATE UNIQUE INDEX idx_llm_default_models_org_use_case ON public.llm_default_models USING btree (organization_id, use_case);`,
		`CREATE INDEX idx_llm_default_models_organization_id ON public.llm_default_models USING btree (organization_id);`,
		`CREATE INDEX idx_llm_model_configs_organization_id ON public.llm_model_configs USING btree (organization_id);`,
		`CREATE INDEX idx_llm_models_audio ON public.llm_models USING btree (audio) WHERE (audio = true);`,
		`CREATE INDEX idx_llm_models_family ON public.llm_models USING btree (family);`,
		`CREATE INDEX idx_llm_models_finetuned ON public.llm_models USING btree (is_finetuned);`,
		`CREATE INDEX idx_llm_models_function_calling ON public.llm_models USING btree (function_calling) WHERE (function_calling = true);`,
		`CREATE INDEX idx_llm_models_is_configured ON public.llm_models USING btree (is_configured);`,
		`CREATE INDEX idx_llm_models_is_flagship ON public.llm_models USING btree (is_flagship);`,
		`CREATE INDEX idx_llm_models_reasoning ON public.llm_models USING btree (reasoning) WHERE (reasoning = true);`,
		`CREATE INDEX idx_llm_models_slug ON public.llm_models USING btree (slug);`,
		`CREATE INDEX idx_llm_models_status ON public.llm_models USING btree (status);`,
		`CREATE INDEX idx_llm_models_streaming ON public.llm_models USING btree (streaming) WHERE (streaming = true);`,
		`CREATE INDEX idx_llm_models_system_enabled ON public.llm_models USING btree (is_system_enabled);`,
		`CREATE INDEX idx_llm_models_use_cases ON public.llm_models USING gin (use_cases);`,
		`CREATE INDEX idx_llm_models_vision ON public.llm_models USING btree (vision) WHERE (vision = true);`,
		`CREATE UNIQUE INDEX idx_llm_organization_api_keys_key_hash ON public.llm_organization_api_keys USING btree (key_hash) WHERE ((deleted_at IS NULL) AND (key_hash IS NOT NULL));`,
		`CREATE INDEX idx_llm_organization_api_keys_organization_id ON public.llm_organization_api_keys USING btree (organization_id);`,
		`CREATE INDEX idx_llm_providers_country_code ON public.llm_providers USING btree (country_code);`,
		`CREATE INDEX idx_llm_providers_system_enabled ON public.llm_providers USING btree (is_system_enabled);`,
		`CREATE INDEX idx_llm_routes_organization_id ON public.llm_routes USING btree (organization_id);`,
		`CREATE INDEX idx_llm_tenant_api_keys_deleted_at ON public.llm_organization_api_keys USING btree (deleted_at);`,
		`CREATE INDEX idx_llm_tenant_api_keys_expires_at ON public.llm_organization_api_keys USING btree (expires_at) WHERE (expires_at IS NOT NULL);`,
		`CREATE UNIQUE INDEX idx_llm_tenant_api_keys_key ON public.llm_organization_api_keys USING btree (key) WHERE (deleted_at IS NULL);`,
		`CREATE UNIQUE INDEX idx_llm_tenant_api_keys_key_hash ON public.llm_organization_api_keys USING btree (key_hash);`,
		`CREATE INDEX idx_llm_tenant_api_keys_status ON public.llm_organization_api_keys USING btree (status);`,
		`CREATE INDEX idx_llm_tenant_api_keys_tenant_id ON public.llm_organization_api_keys USING btree (organization_id);`,
		`CREATE INDEX idx_llm_tenant_custom_models_use_cases ON public.llm_custom_models USING gin (use_cases);`,
		`CREATE INDEX idx_llm_workspace_quotas_org ON public.llm_workspace_quotas USING btree (organization_id);`,
		`CREATE INDEX idx_members_account_role ON public.members USING btree (account_id, role);`,
		`CREATE INDEX idx_mentions_entity_id ON public.kb_entity_mentions USING btree (entity_id);`,
		`CREATE INDEX idx_mentions_pending_task ON public.kb_entity_mentions USING btree (kb_id, status) WHERE ((status)::text = 'pending'::text);`,
		`CREATE INDEX idx_model_active ON public.llm_models USING btree (is_active);`,
		`CREATE INDEX idx_model_deleted_at ON public.llm_models USING btree (deleted_at);`,
		`CREATE INDEX idx_model_display_name ON public.llm_models USING btree (display_name);`,
		`CREATE INDEX idx_model_provider ON public.llm_models USING btree (provider);`,
		`CREATE UNIQUE INDEX idx_model_provider_name ON public.llm_models USING btree (provider, name);`,
		`CREATE INDEX idx_model_reasoning ON public.llm_models USING btree (reasoning);`,
		`CREATE INDEX idx_model_recommended ON public.llm_models USING btree (is_recommended) WHERE ((is_recommended = true) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_model_release_date ON public.llm_models USING btree (release_date);`,
		`CREATE INDEX idx_model_tier ON public.llm_models USING btree (model_tier) WHERE ((model_tier IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE INDEX idx_model_tool_call ON public.llm_models USING btree (function_calling);`,
		`CREATE INDEX idx_models_parent_id ON public.llm_models USING btree (parent_id);`,
		`CREATE INDEX idx_order_account ON public.orders USING btree (account_id);`,
		`CREATE INDEX idx_order_created_at ON public.orders USING btree (created_at);`,
		`CREATE INDEX idx_order_group ON public.orders USING btree (group_id);`,
		`CREATE UNIQUE INDEX idx_order_no ON public.orders USING btree (order_no);`,
		`CREATE INDEX idx_order_status ON public.orders USING btree (status);`,
		`CREATE INDEX idx_order_subscription ON public.orders USING btree (subscription_id);`,
		`CREATE INDEX idx_order_type ON public.orders USING btree (order_type);`,
		`CREATE INDEX idx_orders_pending_created_at ON public.orders USING btree (created_at) WHERE ((status)::text = 'pending'::text);`,
		`CREATE INDEX idx_payment_transaction_account ON public.payment_transactions USING btree (account_id);`,
		`CREATE INDEX idx_payment_transaction_created_at ON public.payment_transactions USING btree (created_at);`,
		`CREATE INDEX idx_payment_transaction_method ON public.payment_transactions USING btree (payment_method);`,
		`CREATE UNIQUE INDEX idx_payment_transaction_no ON public.payment_transactions USING btree (transaction_no);`,
		`CREATE INDEX idx_payment_transaction_order ON public.payment_transactions USING btree (order_id);`,
		`CREATE INDEX idx_payment_transaction_status ON public.payment_transactions USING btree (status);`,
		`CREATE INDEX idx_plugin_installations_tenant_id ON public.plugin_installations USING btree (tenant_id);`,
		`CREATE INDEX idx_plugin_installations_tenant_plugin ON public.plugin_installations USING btree (tenant_id, plugin_unique_identifier);`,
		`CREATE INDEX idx_prompt_opt_runs_account_prompt_created ON public.app_prompt_optimization_runs USING btree (account_id, prompt_id, created_at DESC);`,
		`CREATE INDEX idx_prompt_opt_runs_org_workspace_created ON public.app_prompt_optimization_runs USING btree (organization_id, workspace_id, created_at DESC);`,
		`CREATE INDEX idx_provider_active ON public.llm_providers USING btree (is_active);`,
		`CREATE INDEX idx_provider_currency ON public.llm_providers USING btree (currency);`,
		`CREATE INDEX idx_provider_deleted_at ON public.llm_providers USING btree (deleted_at);`,
		`CREATE INDEX idx_provider_display_name ON public.llm_providers USING btree (provider_name);`,
		`CREATE UNIQUE INDEX idx_provider_name ON public.llm_providers USING btree (provider);`,
		`CREATE INDEX idx_quota_history_account ON public.quota_usage_history USING btree (account_id);`,
		`CREATE INDEX idx_quota_history_created_at ON public.quota_usage_history USING btree (created_at);`,
		`CREATE INDEX idx_quota_history_group ON public.quota_usage_history USING btree (group_id);`,
		`CREATE INDEX idx_quota_history_group_created ON public.quota_usage_history USING btree (group_id, created_at);`,
		`CREATE INDEX idx_quota_history_group_resource ON public.quota_usage_history USING btree (group_id, resource_type);`,
		`CREATE INDEX idx_quota_history_resource_type ON public.quota_usage_history USING btree (resource_type);`,
		`CREATE INDEX idx_quota_history_tenant ON public.quota_usage_history USING btree (tenant_id);`,
		`CREATE INDEX idx_refund_account ON public.refund_records USING btree (account_id);`,
		`CREATE INDEX idx_refund_created_at ON public.refund_records USING btree (created_at);`,
		`CREATE UNIQUE INDEX idx_refund_no ON public.refund_records USING btree (refund_no);`,
		`CREATE INDEX idx_refund_order ON public.refund_records USING btree (order_id);`,
		`CREATE INDEX idx_refund_status ON public.refund_records USING btree (status);`,
		`CREATE INDEX idx_refund_transaction ON public.refund_records USING btree (transaction_id);`,
		`CREATE INDEX idx_relationships_deleted ON public.kb_relationships USING btree (is_deleted) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_roles_group_id ON public.roles USING btree (group_id);`,
		`CREATE UNIQUE INDEX uk_roles_group_system_key ON public.roles USING btree (group_id, system_key) WHERE (system_key IS NOT NULL);`,
		`CREATE INDEX idx_roles_status ON public.roles USING btree (status);`,
		`CREATE INDEX idx_route_credential ON public.llm_routes USING btree (credential_id);`,
		`CREATE INDEX idx_route_deleted ON public.llm_routes USING btree (deleted_at);`,
		`CREATE INDEX idx_route_enabled ON public.llm_routes USING btree (is_enabled);`,
		`CREATE INDEX idx_route_tenant ON public.llm_routes USING btree (organization_id);`,
		`CREATE INDEX idx_route_type ON public.llm_routes USING btree (type);`,
		`CREATE INDEX idx_route_usr_cred ON public.llm_routes USING btree (user_credential_id);`,
		`CREATE INDEX idx_routes_is_official ON public.llm_routes USING btree (is_official);`,
		`CREATE INDEX idx_routes_models ON public.llm_routes USING gin (match_models) WHERE (match_models IS NOT NULL);`,
		`CREATE INDEX idx_routes_query ON public.llm_routes USING btree (organization_id, is_enabled, priority DESC, weight DESC);`,
		`CREATE INDEX idx_routes_status ON public.llm_routes USING btree (status) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_routes_tenant_new ON public.llm_routes USING btree (organization_id) WHERE ((deleted_at IS NULL) AND (is_enabled = true));`,
		`CREATE INDEX idx_routes_tenant_priority ON public.llm_routes USING btree (organization_id, priority DESC) WHERE ((deleted_at IS NULL) AND (is_enabled = true));`,
		`CREATE INDEX idx_sales_contact_account ON public.sales_contact_requests USING btree (account_id);`,
		`CREATE UNIQUE INDEX idx_sales_contact_account_unique ON public.sales_contact_requests USING btree (account_id) WHERE (account_id IS NOT NULL);`,
		`CREATE INDEX idx_sales_contact_created_at ON public.sales_contact_requests USING btree (created_at);`,
		`CREATE INDEX idx_table_prompts_table_id ON public.data_source_table_prompts USING btree (table_id);`,
		`CREATE INDEX idx_taj_account_current ON public.workspace_members USING btree (account_id, current);`,
		`CREATE INDEX idx_taj_account_not_current ON public.workspace_members USING btree (account_id) WHERE (current = false);`,
		`CREATE INDEX idx_taj_account_tenant_role ON public.workspace_members USING btree (account_id, workspace_id, role);`,
		`CREATE INDEX idx_tenant_custom_model_active ON public.llm_custom_models USING btree (is_active);`,
		`CREATE INDEX idx_tenant_custom_model_deleted_at ON public.llm_custom_models USING btree (deleted_at);`,
		`CREATE INDEX idx_tenant_custom_model_provider ON public.llm_custom_models USING btree (provider_id);`,
		`CREATE INDEX idx_tenant_custom_model_tenant ON public.llm_custom_models USING btree (organization_id);`,
		`CREATE INDEX idx_tenant_custom_provider_active ON public.llm_custom_providers USING btree (is_active);`,
		`CREATE INDEX idx_tenant_custom_provider_deleted_at ON public.llm_custom_providers USING btree (deleted_at);`,
		`CREATE INDEX idx_tenant_custom_provider_tenant ON public.llm_custom_providers USING btree (organization_id);`,
		`CREATE INDEX idx_tenant_model_config_deleted_at ON public.llm_model_configs USING btree (deleted_at);`,
		`CREATE INDEX idx_tenant_model_config_enabled ON public.llm_model_configs USING btree (is_enabled);`,
		`CREATE INDEX idx_tenant_model_config_tenant ON public.llm_model_configs USING btree (organization_id);`,
		`CREATE UNIQUE INDEX idx_tenant_model_config_unique ON public.llm_model_configs USING btree (organization_id, model_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_tenant_model_deleted_at ON public.llm_tenant_models USING btree (deleted_at);`,
		`CREATE INDEX idx_tenant_model_enabled ON public.llm_tenant_models USING btree (is_enabled);`,
		`CREATE INDEX idx_tenant_model_model ON public.llm_tenant_models USING btree (model);`,
		`CREATE INDEX idx_tenant_model_provider ON public.llm_tenant_models USING btree (provider);`,
		`CREATE INDEX idx_tenant_model_tenant ON public.llm_tenant_models USING btree (tenant_id);`,
		`CREATE INDEX idx_tenant_model_tenant_provider ON public.llm_tenant_models USING btree (tenant_id, provider);`,
		`CREATE INDEX idx_tenant_provider_config_deleted_at ON public.llm_provider_configs USING btree (deleted_at);`,
		`CREATE INDEX idx_tenant_provider_config_enabled ON public.llm_provider_configs USING btree (is_enabled);`,
		`CREATE INDEX idx_tenant_provider_config_tenant ON public.llm_provider_configs USING btree (organization_id);`,
		`CREATE UNIQUE INDEX idx_tenant_provider_config_unique ON public.llm_provider_configs USING btree (organization_id, provider_id) WHERE (deleted_at IS NULL);`,
		`CREATE INDEX idx_tenant_routes_health ON public.llm_routes USING btree (success_count, failure_count) WHERE ((success_count > 0) OR (failure_count > 0));`,
		`CREATE INDEX idx_tenant_routes_protocol ON public.llm_routes USING btree (protocol) WHERE (protocol IS NOT NULL);`,
		`CREATE INDEX idx_tool_files_deleted_at ON public.tool_files USING btree (deleted_at);`,
		`CREATE INDEX idx_tool_files_lifecycle_expires_at ON public.tool_files USING btree (lifecycle, expires_at);`,
		`CREATE INDEX idx_triple_mentions_deleted ON public.kb_triple_mentions USING btree (is_deleted) WHERE (is_deleted = false);`,
		`CREATE INDEX idx_triple_mentions_task ON public.kb_triple_mentions USING btree (kb_id, status) WHERE ((status)::text = 'pending'::text);`,
		`CREATE INDEX idx_tx_batch ON public.transactions USING btree (batch_id);`,
		`CREATE INDEX idx_tx_created_at ON public.transactions USING btree (created_at);`,
		`CREATE INDEX idx_tx_group ON public.transactions USING btree (group_id);`,
		`CREATE INDEX idx_tx_group_currency ON public.transactions USING btree (group_id, currency_type);`,
		`CREATE INDEX idx_tx_reference ON public.transactions USING btree (reference_type, reference_id);`,
		`CREATE INDEX idx_tx_tenant ON public.transactions USING btree (tenant_id);`,
		`CREATE INDEX idx_tx_type ON public.transactions USING btree (transaction_type);`,
		`CREATE INDEX idx_type_definitions_dataset ON public.kb_type_definitions USING btree (dataset_id);`,
		`CREATE UNIQUE INDEX idx_unique_relationship_fact ON public.kb_relationships USING btree (kb_id, head_entity_id, tail_entity_id, relation_type);`,
		`CREATE INDEX idx_upload_files_organization_archived ON public.upload_files USING btree (organization_id, is_archived);`,
		`CREATE INDEX idx_upload_files_organization_archived_created ON public.upload_files USING btree (organization_id, is_archived, created_at);`,
		`CREATE INDEX idx_usage_bills_org_app_created ON public.llm_usage_bills USING btree (organization_id, app_id, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_org_app_type_created ON public.llm_usage_bills USING btree (organization_id, app_type, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_org_created ON public.llm_usage_bills USING btree (organization_id, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_org_lane_created ON public.llm_usage_bills USING btree (organization_id, billing_lane, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_org_model_created ON public.llm_usage_bills USING btree (organization_id, model_name, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_org_source_created ON public.llm_usage_bills USING btree (organization_id, use_system_provider, request_created_at DESC);`,
		`CREATE INDEX idx_usage_bills_remote_deduction ON public.llm_usage_bills USING btree (remote_deduction_id) WHERE (remote_deduction_id IS NOT NULL);`,
		`CREATE INDEX idx_usage_bills_request_id ON public.llm_usage_bills USING btree (request_id);`,
		`CREATE INDEX idx_user_consents_account_id ON public.user_consents USING btree (account_id);`,
		`CREATE UNIQUE INDEX idx_user_consents_account_type ON public.user_consents USING btree (account_id, consent_type);`,
		`CREATE INDEX idx_user_consents_consent_type ON public.user_consents USING btree (consent_type);`,
		`CREATE INDEX idx_wallet_account ON public.group_wallets USING btree (account_id);`,
		`CREATE UNIQUE INDEX idx_wallet_account_group_currency ON public.group_wallets USING btree (account_id, group_id, currency);`,
		`CREATE INDEX idx_wallet_group ON public.group_wallets USING btree (group_id);`,
		`CREATE INDEX idx_wf_node_logs_error_type ON public.workflow_node_runtime_logs USING btree (error_type);`,
		`CREATE INDEX idx_workflow_approval_deliveries_form_id ON public.workflow_approval_deliveries USING btree (form_id);`,
		`CREATE INDEX idx_workflow_approval_forms_app_id ON public.workflow_approval_forms USING btree (app_id);`,
		`CREATE INDEX idx_workflow_approval_forms_node_id ON public.workflow_approval_forms USING btree (node_id);`,
		`CREATE UNIQUE INDEX idx_workflow_approval_forms_run_node ON public.workflow_approval_forms USING btree (workflow_run_id, node_id);`,
		`CREATE INDEX idx_workflow_approval_forms_status_expiration_time ON public.workflow_approval_forms USING btree (status, expiration_time);`,
		`CREATE INDEX idx_workflow_approval_forms_tenant_id ON public.workflow_approval_forms USING btree (tenant_id);`,
		`CREATE INDEX idx_workflow_approval_forms_workflow_run_id ON public.workflow_approval_forms USING btree (workflow_run_id);`,
		`CREATE INDEX idx_workflow_approval_recipients_delivery_id ON public.workflow_approval_recipients USING btree (delivery_id);`,
		`CREATE INDEX idx_workflow_approval_recipients_form_id ON public.workflow_approval_recipients USING btree (form_id);`,
		`CREATE INDEX idx_workflow_run_events_tenant_run_sequence ON public.workflow_run_events USING btree (tenant_id, workflow_run_id, sequence);`,
		`CREATE INDEX idx_workflow_run_pause_reasons_pause_id ON public.workflow_run_pause_reasons USING btree (pause_id);`,
		`CREATE INDEX idx_workflow_run_pauses_active_conversation_reason ON public.workflow_run_pauses USING btree (conversation_id, app_id, reason) WHERE ((resumed_at IS NULL) AND (conversation_id IS NOT NULL));`,
		`CREATE UNIQUE INDEX idx_workflow_run_pauses_active_run ON public.workflow_run_pauses USING btree (workflow_run_id) WHERE (resumed_at IS NULL);`,
		`CREATE INDEX idx_workflow_run_pauses_app_id ON public.workflow_run_pauses USING btree (app_id);`,
		`CREATE INDEX idx_workflow_run_pauses_conversation_id ON public.workflow_run_pauses USING btree (conversation_id);`,
		`CREATE INDEX idx_workflow_run_pauses_tenant_id ON public.workflow_run_pauses USING btree (tenant_id);`,
		`CREATE INDEX idx_workflow_run_pauses_workflow_run_id ON public.workflow_run_pauses USING btree (workflow_run_id);`,
		`CREATE INDEX idx_workflow_test_batch_items_agent ON public.workflow_test_batch_items USING btree (agent_id, status);`,
		`CREATE INDEX idx_workflow_test_batch_items_batch ON public.workflow_test_batch_items USING btree (batch_id, created_at);`,
		`CREATE INDEX idx_workflow_test_batch_items_case ON public.workflow_test_batch_items USING btree (case_id);`,
		`CREATE INDEX idx_workflow_test_batches_agent_status ON public.workflow_test_batches USING btree (agent_id, status, created_at DESC);`,
		`CREATE INDEX idx_workflow_test_cases_agent_status ON public.workflow_test_cases USING btree (agent_id, status, created_at DESC);`,
		`CREATE INDEX idx_workflow_test_cases_scenario ON public.workflow_test_cases USING btree (scenario_id);`,
		`CREATE INDEX idx_workflow_test_scenarios_agent ON public.workflow_test_scenarios USING btree (agent_id, created_at DESC);`,
		`CREATE INDEX idx_workflows_internal ON public.workflows USING btree (internal) WHERE (internal = true);`,
		`CREATE INDEX idx_workflows_internal_tenant ON public.workflows USING btree (internal, tenant_id) WHERE (internal = true);`,
		`CREATE INDEX idx_workspace_members_account_current ON public.workspace_members USING btree (account_id, current);`,
		`CREATE INDEX idx_workspace_members_account_id ON public.workspace_members USING btree (account_id);`,
		`CREATE INDEX idx_workspace_members_role_id ON public.workspace_members USING btree (role_id);`,
		`CREATE INDEX idx_workspace_members_workspace_id ON public.workspace_members USING btree (workspace_id);`,
		`CREATE INDEX idx_workspaces_organization_id ON public.workspaces USING btree (organization_id);`,
		`CREATE INDEX installed_agents_tenant_id_idx ON public.installed_agents USING btree (tenant_id);`,
		`CREATE INDEX members_account_id_idx ON public.members USING btree (account_id);`,
		`CREATE INDEX members_organization_id_idx ON public.members USING btree (organization_id);`,
		`CREATE INDEX message_annotations_app_id_idx ON public.message_annotations USING btree (app_id);`,
		`CREATE INDEX message_annotations_conversation_id_idx ON public.message_annotations USING btree (conversation_id);`,
		`CREATE INDEX message_annotations_message_id_idx ON public.message_annotations USING btree (message_id);`,
		`CREATE INDEX message_feedbacks_app_id_idx ON public.message_feedbacks USING btree (app_id);`,
		`CREATE INDEX message_feedbacks_conversation_id_idx ON public.message_feedbacks USING btree (conversation_id);`,
		`CREATE INDEX message_feedbacks_message_id_idx ON public.message_feedbacks USING btree (message_id);`,
		`CREATE INDEX message_files_created_by_idx ON public.message_files USING btree (created_by);`,
		`CREATE INDEX message_files_message_id_idx ON public.message_files USING btree (message_id);`,
		`CREATE INDEX messages_app_id_idx ON public.messages USING btree (app_id);`,
		`CREATE INDEX messages_conversation_id_idx ON public.messages USING btree (conversation_id);`,
		`CREATE INDEX messages_created_at_idx ON public.messages USING btree (created_at);`,
		`CREATE INDEX messages_end_user_idx ON public.messages USING btree (app_id, from_source, from_end_user_id);`,
		`CREATE INDEX messages_workflow_run_id_idx ON public.messages USING btree (conversation_id, workflow_run_id);`,
		`CREATE INDEX tool_file_conversation_id_idx ON public.tool_files USING btree (conversation_id);`,
		`CREATE UNIQUE INDEX uniq_data_library_db_asset_refs_active_source ON public.data_library_database_asset_refs USING btree (organization_id, data_source_id, asset_id, version_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'active'::text) AND (table_id IS NULL));`,
		`CREATE UNIQUE INDEX uniq_data_library_db_asset_refs_active_table ON public.data_library_database_asset_refs USING btree (organization_id, data_source_id, table_id, asset_id, version_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'active'::text) AND (table_id IS NOT NULL));`,
		`CREATE UNIQUE INDEX uniq_data_library_kb_asset_refs_active ON public.data_library_knowledge_base_asset_refs USING btree (organization_id, dataset_id, asset_id, version_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'active'::text));`,
		`CREATE INDEX upload_file_organization_idx ON public.upload_files USING btree (organization_id);`,
		`CREATE INDEX upload_files_created_by_idx ON public.upload_files USING btree (created_by);`,
		`CREATE INDEX upload_files_organization_id_idx ON public.upload_files USING btree (organization_id);`,
		`CREATE INDEX upload_files_workspace_id_idx ON public.upload_files USING btree (workspace_id);`,
		`CREATE UNIQUE INDEX uq_automation_task_runs_task_id_scheduled_for_trigger_source ON public.automation_task_runs USING btree (task_id, scheduled_for, trigger_source);`,
		`CREATE UNIQUE INDEX uq_content_parse_artifacts_signature ON public.content_parse_artifacts USING btree (source_content_hash, profile, canonical_ir_version, provider_signature);`,
		`CREATE UNIQUE INDEX uq_content_parse_chunk_artifact_sets_signature ON public.content_parse_chunk_artifact_sets USING btree (signature);`,
		`CREATE UNIQUE INDEX uq_content_parse_playground_runs_share_token ON public.content_parse_playground_runs USING btree (share_token);`,
		`CREATE UNIQUE INDEX uq_content_parse_provider_configs_system_provider ON public.content_parse_provider_configs USING btree (scope, provider_key) WHERE ((workspace_id IS NULL) AND (deleted_at IS NULL));`,
		`CREATE UNIQUE INDEX uq_content_parse_provider_configs_workspace_provider ON public.content_parse_provider_configs USING btree (scope, workspace_id, provider_key) WHERE ((workspace_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE UNIQUE INDEX uq_content_parse_route_policies_system_policy ON public.content_parse_route_policies USING btree (scope, policy_key) WHERE ((workspace_id IS NULL) AND (deleted_at IS NULL));`,
		`CREATE UNIQUE INDEX uq_content_parse_route_policies_workspace_policy ON public.content_parse_route_policies USING btree (scope, workspace_id, policy_key) WHERE ((workspace_id IS NOT NULL) AND (deleted_at IS NULL));`,
		`CREATE UNIQUE INDEX uq_data_library_assets_org_source_file_active ON public.data_library_document_assets USING btree (organization_id, source_file_id) WHERE (deleted_at IS NULL);`,
		`CREATE UNIQUE INDEX uq_data_library_document_versions_asset_version ON public.data_library_document_versions USING btree (asset_id, version_no);`,
		`CREATE UNIQUE INDEX uq_data_library_vector_artifacts_active_model ON public.data_library_vector_artifacts USING btree (organization_id, chunk_artifact_set_id, embedding_provider, embedding_model, vector_collection, COALESCE(vector_namespace, ''::character varying)) WHERE ((deleted_at IS NULL) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'ready'::character varying])::text[])));`,
		`CREATE UNIQUE INDEX uq_workflow_test_scenarios_agent_name ON public.workflow_test_scenarios USING btree (agent_id, name);`,
		`CREATE INDEX workflow_node_executions_workflow_run_id_idx ON public.workflow_node_executions USING btree (workflow_run_id);`,
		`CREATE INDEX workflow_node_runtime_logs_workflow_run_id_idx ON public.workflow_node_runtime_logs USING btree (workflow_run_id);`,
		`CREATE INDEX workflow_run_logs_agent_id_idx ON public.workflow_run_logs USING btree (agent_id);`,
		`CREATE INDEX workflow_runs_app_id_idx ON public.workflow_runs USING btree (app_id);`,
		`CREATE INDEX workflows_app_id_idx ON public.workflows USING btree (app_id);`,
		`CREATE INDEX workflows_tenant_id_idx ON public.workflows USING btree (tenant_id);`,
	},
}
