version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./api:/app
    ports:
      - '8088:8088'
      - '7001:7001'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # OpenAI API Key
      - WEAVIATE_URL=${WEAVIATE_URL} # Weaviate URL
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY} # Weaviate API Key
      - WEAVIATE_LOCAL_URL=weaviate # Weaviate Local URL
      - WEAVIATE_LOCAL_API_KEY=${WEAVIATE_LOCAL_API_KEY} # Weaviate Local API Key
      - OPENAI_BASE_URL=${OPENAI_BASE_URL} # OpenAI Base URL
      - OPENAI_API_BASE=${OPENAI_API_BASE} # OpenAI API Base URL
      - ENVIRONMENT=${ENVIRONMENT} # Environment Setting
      - MYSQL_MIN_CONNECTIONS=${MYSQL_MIN_CONNECTIONS} # MySQL Min Connections
      - MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS} # MySQL Max Connections
      - QINIU_BASEURL=${QINIU_BASEURL}
      - QINIU_SK=${QINIU_SK}
      - QINIU_AK=${QINIU_AK}
      - QINIU_BUCKET=${QINIU_BUCKET}
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - db
      - weaviate

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} # Database root password
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Database name
      MYSQL_USER: ${MYSQL_USER} # Database username
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Database password
    volumes:
      - db_data:/var/lib/mysql # Use volume for data persistence
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init script

  weaviate:
    image: semitechnologies/weaviate
    ports:
      - '8080:8080'
      - '50051:50051'
    volumes:
      - weaviate_data:/var/lib/weaviate # Use Docker volume for data persistence
    environment:
      - QUERY_DEFAULTS_LIMIT=25 # Set default query limit
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true' # Enable anonymous access
      - ENABLE_MODULES='text2vec-openai' # Enable OpenAI module

  # web:
  #   image: e-web:latest
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.web
  #     args:
  #       - HTTP_PROXY=${DOCKER_HTTP_PROXY}
  #       - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
  #   ports:
  #     - "${WEB_PORT:-80}:80"
  #   environment:
  #     - PORT=80
  #     - HTTP_PROXY=${DOCKER_HTTP_PROXY}
  #     - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}

volumes:
  db_data: {} # Define db_data volume
  weaviate_data: {} # Define weaviate_data volume

