# 使用 Python 官方镜像
FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc \
  g++ \
  python3-dev \
  && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

COPY ../api /app

# Create virtual environment and install dependencies
RUN python -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --upgrade pip && \
  pip install -r requirements.txt

# # 启动应用程序
CMD ["python", "/app/main.py"]