$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Template = Join-Path $ScriptDir 'docker-compose.template.yaml'
$Output = Join-Path $ScriptDir 'docker-compose.yaml'

if (-not (Test-Path -LiteralPath $Template)) {
  Write-Error "[generate] missing template: $Template"
}

$header = @(
  '# =================================================================='
  '# WARNING: This file is auto-generated by docker/generate_docker_compose'
  '# Do not modify this file directly. Update docker-compose.template.yaml'
  '# and regenerate this file instead.'
  '# =================================================================='
  ''
)

$content = Get-Content -LiteralPath $Template
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($Output, ($header + $content), $utf8NoBom)

Write-Host "[generate] wrote $Output"
