import {
  BookOpenCheck,
  Bot,
  Brain,
  Calculator,
  CalendarDays,
  ChartNoAxesCombined,
  Clock,
  ClipboardList,
  Compass,
  Database,
  FilePlus,
  FilePlus2,
  FileSearch,
  FileText,
  Files,
  FolderCog,
  GitFork,
  ImagePlus,
  Library,
  ListChecks,
  ListCollapse,
  MessageCircleHeart,
  Network,
  Presentation,
  Route,
  Scale,
  Send,
  ShieldAlert,
  Sparkles,
  TableProperties,
  Tickets,
  UserSearch,
  WandSparkles,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const AI_CHAT_SKILL_ICON_BY_KEY: Record<string, LucideIcon> = {
  'book-open-check': BookOpenCheck,
  bot: Bot,
  brain: Brain,
  calculator: Calculator,
  'calendar-days': CalendarDays,
  'chart-no-axes-combined': ChartNoAxesCombined,
  clock: Clock,
  'clipboard-list': ClipboardList,
  compass: Compass,
  database: Database,
  file: FileText,
  'file-generator': FileText,
  'file-manager': FolderCog,
  'file-plus': FilePlus,
  'file-plus-2': FilePlus2,
  'file-search': FileSearch,
  'file-text': FileText,
  files: Files,
  'folder-cog': FolderCog,
  'git-fork': GitFork,
  'image-plus': ImagePlus,
  library: Library,
  'list-checks': ListChecks,
  'list-collapse': ListCollapse,
  'message-circle-heart': MessageCircleHeart,
  network: Network,
  presentation: Presentation,
  route: Route,
  scale: Scale,
  send: Send,
  'shield-alert': ShieldAlert,
  sparkles: Sparkles,
  'table-properties': TableProperties,
  tickets: Tickets,
  time: Clock,
  tools: Wrench,
  'user-search': UserSearch,
  'wand-sparkles': WandSparkles,
  workflow: Workflow,
  wrench: Wrench,
};
