providers:
  openai:
    name: OpenAI
    class: OpenAIProvider
    models:
      - gpt-4
      - gpt-4-32k
      - gpt-4-turbo-preview
      - gpt-3.5-turbo

  anthropic:
    name: Anthropic
    class: AnthropicProvider
    models:
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
      - claude-2.1
      - claude-2.0
      - claude-instant-1.2

  deepseek:
    name: DeepSeek
    class: DeepSeekProvider
    models:
      - deepseek-chat
      - deepseek-coder
      - deepseek-math
