root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  bin = "./tmp/main start"
  full_bin = "./tmp/main start"
  include_ext = ["go", "yaml", "yml", "json"]
  exclude_dir = ["assets", "tmp", "vendor", "tests", "docs", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
