// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: pkg/rpc/v1/billing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreDeductQuotaRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId   string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EstimatedCredits int64                  `protobuf:"varint,2,opt,name=estimated_credits,json=estimatedCredits,proto3" json:"estimated_credits,omitempty"`
	ModelId          string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName        string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ProviderId       string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName     string                 `protobuf:"bytes,6,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreDeductQuotaRequest) Reset() {
	*x = PreDeductQuotaRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductQuotaRequest) ProtoMessage() {}

func (x *PreDeductQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductQuotaRequest.ProtoReflect.Descriptor instead.
func (*PreDeductQuotaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *PreDeductQuotaRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetEstimatedCredits() int64 {
	if x != nil {
		return x.EstimatedCredits
	}
	return 0
}

func (x *PreDeductQuotaRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PreDeductQuotaRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type PreDeductQuotaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RemainingQuota int64                  `protobuf:"varint,4,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`
	DeductionId    string                 `protobuf:"bytes,5,opt,name=deduction_id,json=deductionId,proto3" json:"deduction_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreDeductQuotaResponse) Reset() {
	*x = PreDeductQuotaResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductQuotaResponse) ProtoMessage() {}

func (x *PreDeductQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductQuotaResponse.ProtoReflect.Descriptor instead.
func (*PreDeductQuotaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *PreDeductQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreDeductQuotaResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PreDeductQuotaResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PreDeductQuotaResponse) GetRemainingQuota() int64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *PreDeductQuotaResponse) GetDeductionId() string {
	if x != nil {
		return x.DeductionId
	}
	return ""
}

type SettleQuotaRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DeductionId       string                 `protobuf:"bytes,2,opt,name=deduction_id,json=deductionId,proto3" json:"deduction_id,omitempty"`
	EstimatedCredits  int64                  `protobuf:"varint,3,opt,name=estimated_credits,json=estimatedCredits,proto3" json:"estimated_credits,omitempty"`
	ActualCredits     int64                  `protobuf:"varint,4,opt,name=actual_credits,json=actualCredits,proto3" json:"actual_credits,omitempty"`
	PromptTokens      int32                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens  int32                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens       int32                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	InputCost         float64                `protobuf:"fixed64,8,opt,name=input_cost,json=inputCost,proto3" json:"input_cost,omitempty"`
	OutputCost        float64                `protobuf:"fixed64,9,opt,name=output_cost,json=outputCost,proto3" json:"output_cost,omitempty"`
	TotalCost         float64                `protobuf:"fixed64,10,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	ModelId           string                 `protobuf:"bytes,11,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName         string                 `protobuf:"bytes,12,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ProviderId        string                 `protobuf:"bytes,13,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName      string                 `protobuf:"bytes,14,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ChannelId         string                 `protobuf:"bytes,15,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,16,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseTime      int64                  `protobuf:"varint,17,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Status            string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,19,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AccountId         string                 `protobuf:"bytes,20,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AppId             string                 `protobuf:"bytes,21,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppType           string                 `protobuf:"bytes,22,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	IpAddress         string                 `protobuf:"bytes,23,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent         string                 `protobuf:"bytes,24,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IsStreaming       bool                   `protobuf:"varint,25,opt,name=is_streaming,json=isStreaming,proto3" json:"is_streaming,omitempty"`
	UseSystemProvider bool                   `protobuf:"varint,26,opt,name=use_system_provider,json=useSystemProvider,proto3" json:"use_system_provider,omitempty"`
	AttemptId         string                 `protobuf:"bytes,27,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SettleQuotaRequest) Reset() {
	*x = SettleQuotaRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleQuotaRequest) ProtoMessage() {}

func (x *SettleQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleQuotaRequest.ProtoReflect.Descriptor instead.
func (*SettleQuotaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *SettleQuotaRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SettleQuotaRequest) GetDeductionId() string {
	if x != nil {
		return x.DeductionId
	}
	return ""
}

func (x *SettleQuotaRequest) GetEstimatedCredits() int64 {
	if x != nil {
		return x.EstimatedCredits
	}
	return 0
}

func (x *SettleQuotaRequest) GetActualCredits() int64 {
	if x != nil {
		return x.ActualCredits
	}
	return 0
}

func (x *SettleQuotaRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SettleQuotaRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SettleQuotaRequest) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *SettleQuotaRequest) GetInputCost() float64 {
	if x != nil {
		return x.InputCost
	}
	return 0
}

func (x *SettleQuotaRequest) GetOutputCost() float64 {
	if x != nil {
		return x.OutputCost
	}
	return 0
}

func (x *SettleQuotaRequest) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *SettleQuotaRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SettleQuotaRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SettleQuotaRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SettleQuotaRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SettleQuotaRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SettleQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettleQuotaRequest) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *SettleQuotaRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettleQuotaRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SettleQuotaRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SettleQuotaRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SettleQuotaRequest) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *SettleQuotaRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SettleQuotaRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SettleQuotaRequest) GetIsStreaming() bool {
	if x != nil {
		return x.IsStreaming
	}
	return false
}

func (x *SettleQuotaRequest) GetUseSystemProvider() bool {
	if x != nil {
		return x.UseSystemProvider
	}
	return false
}

func (x *SettleQuotaRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type SettleQuotaResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RemainingQuota  int64                  `protobuf:"varint,3,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`
	UsedQuota       int64                  `protobuf:"varint,4,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	RefundedCredits int64                  `protobuf:"varint,5,opt,name=refunded_credits,json=refundedCredits,proto3" json:"refunded_credits,omitempty"`
	SettledCredits  int64                  `protobuf:"varint,6,opt,name=settled_credits,json=settledCredits,proto3" json:"settled_credits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettleQuotaResponse) Reset() {
	*x = SettleQuotaResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleQuotaResponse) ProtoMessage() {}

func (x *SettleQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleQuotaResponse.ProtoReflect.Descriptor instead.
func (*SettleQuotaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *SettleQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SettleQuotaResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SettleQuotaResponse) GetRemainingQuota() int64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *SettleQuotaResponse) GetUsedQuota() int64 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *SettleQuotaResponse) GetRefundedCredits() int64 {
	if x != nil {
		return x.RefundedCredits
	}
	return 0
}

func (x *SettleQuotaResponse) GetSettledCredits() int64 {
	if x != nil {
		return x.SettledCredits
	}
	return 0
}

type CalculateDualCostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ModelId          string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateDualCostRequest) Reset() {
	*x = CalculateDualCostRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDualCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDualCostRequest) ProtoMessage() {}

func (x *CalculateDualCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDualCostRequest.ProtoReflect.Descriptor instead.
func (*CalculateDualCostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateDualCostRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *CalculateDualCostRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *CalculateDualCostRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CalculateDualCostRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DualCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	InputCredits  int64                  `protobuf:"varint,3,opt,name=input_credits,json=inputCredits,proto3" json:"input_credits,omitempty"`
	OutputCredits int64                  `protobuf:"varint,4,opt,name=output_credits,json=outputCredits,proto3" json:"output_credits,omitempty"`
	TotalCredits  int64                  `protobuf:"varint,5,opt,name=total_credits,json=totalCredits,proto3" json:"total_credits,omitempty"`
	InputUsd      float64                `protobuf:"fixed64,6,opt,name=input_usd,json=inputUsd,proto3" json:"input_usd,omitempty"`
	OutputUsd     float64                `protobuf:"fixed64,7,opt,name=output_usd,json=outputUsd,proto3" json:"output_usd,omitempty"`
	TotalUsd      float64                `protobuf:"fixed64,8,opt,name=total_usd,json=totalUsd,proto3" json:"total_usd,omitempty"`
	BillingMode   string                 `protobuf:"bytes,9,opt,name=billing_mode,json=billingMode,proto3" json:"billing_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DualCostResponse) Reset() {
	*x = DualCostResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DualCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DualCostResponse) ProtoMessage() {}

func (x *DualCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DualCostResponse.ProtoReflect.Descriptor instead.
func (*DualCostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *DualCostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DualCostResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DualCostResponse) GetInputCredits() int64 {
	if x != nil {
		return x.InputCredits
	}
	return 0
}

func (x *DualCostResponse) GetOutputCredits() int64 {
	if x != nil {
		return x.OutputCredits
	}
	return 0
}

func (x *DualCostResponse) GetTotalCredits() int64 {
	if x != nil {
		return x.TotalCredits
	}
	return 0
}

func (x *DualCostResponse) GetInputUsd() float64 {
	if x != nil {
		return x.InputUsd
	}
	return 0
}

func (x *DualCostResponse) GetOutputUsd() float64 {
	if x != nil {
		return x.OutputUsd
	}
	return 0
}

func (x *DualCostResponse) GetTotalUsd() float64 {
	if x != nil {
		return x.TotalUsd
	}
	return 0
}

func (x *DualCostResponse) GetBillingMode() string {
	if x != nil {
		return x.BillingMode
	}
	return ""
}

type SettleUsageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId    string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ModelId           string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName         string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ProviderId        string                 `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName      string                 `protobuf:"bytes,5,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ChannelId         string                 `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PromptTokens      int32                  `protobuf:"varint,8,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens  int32                  `protobuf:"varint,9,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens       int32                  `protobuf:"varint,10,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ResponseTime      int64                  `protobuf:"varint,11,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	Status            string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AccountId         string                 `protobuf:"bytes,14,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AppId             string                 `protobuf:"bytes,15,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppType           string                 `protobuf:"bytes,16,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	IpAddress         string                 `protobuf:"bytes,17,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent         string                 `protobuf:"bytes,18,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IsStreaming       bool                   `protobuf:"varint,19,opt,name=is_streaming,json=isStreaming,proto3" json:"is_streaming,omitempty"`
	UseSystemProvider bool                   `protobuf:"varint,20,opt,name=use_system_provider,json=useSystemProvider,proto3" json:"use_system_provider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SettleUsageRequest) Reset() {
	*x = SettleUsageRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleUsageRequest) ProtoMessage() {}

func (x *SettleUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleUsageRequest.ProtoReflect.Descriptor instead.
func (*SettleUsageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *SettleUsageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SettleUsageRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SettleUsageRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SettleUsageRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SettleUsageRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SettleUsageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SettleUsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettleUsageRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SettleUsageRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SettleUsageRequest) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *SettleUsageRequest) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *SettleUsageRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettleUsageRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SettleUsageRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SettleUsageRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SettleUsageRequest) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *SettleUsageRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SettleUsageRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SettleUsageRequest) GetIsStreaming() bool {
	if x != nil {
		return x.IsStreaming
	}
	return false
}

func (x *SettleUsageRequest) GetUseSystemProvider() bool {
	if x != nil {
		return x.UseSystemProvider
	}
	return false
}

type SettleUsageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreditsDeducted int64                  `protobuf:"varint,3,opt,name=credits_deducted,json=creditsDeducted,proto3" json:"credits_deducted,omitempty"`
	UsdCost         float64                `protobuf:"fixed64,4,opt,name=usd_cost,json=usdCost,proto3" json:"usd_cost,omitempty"`
	BillingMode     string                 `protobuf:"bytes,5,opt,name=billing_mode,json=billingMode,proto3" json:"billing_mode,omitempty"`
	IsSelfPaid      bool                   `protobuf:"varint,6,opt,name=is_self_paid,json=isSelfPaid,proto3" json:"is_self_paid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettleUsageResponse) Reset() {
	*x = SettleUsageResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleUsageResponse) ProtoMessage() {}

func (x *SettleUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleUsageResponse.ProtoReflect.Descriptor instead.
func (*SettleUsageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *SettleUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SettleUsageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SettleUsageResponse) GetCreditsDeducted() int64 {
	if x != nil {
		return x.CreditsDeducted
	}
	return 0
}

func (x *SettleUsageResponse) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

func (x *SettleUsageResponse) GetBillingMode() string {
	if x != nil {
		return x.BillingMode
	}
	return ""
}

func (x *SettleUsageResponse) GetIsSelfPaid() bool {
	if x != nil {
		return x.IsSelfPaid
	}
	return false
}

type GetBillingModeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBillingModeRequest) Reset() {
	*x = GetBillingModeRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingModeRequest) ProtoMessage() {}

func (x *GetBillingModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingModeRequest.ProtoReflect.Descriptor instead.
func (*GetBillingModeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetBillingModeRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type BillingModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	BillingMode   string                 `protobuf:"bytes,3,opt,name=billing_mode,json=billingMode,proto3" json:"billing_mode,omitempty"`
	IsSelfPaid    bool                   `protobuf:"varint,4,opt,name=is_self_paid,json=isSelfPaid,proto3" json:"is_self_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingModeResponse) Reset() {
	*x = BillingModeResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingModeResponse) ProtoMessage() {}

func (x *BillingModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingModeResponse.ProtoReflect.Descriptor instead.
func (*BillingModeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *BillingModeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BillingModeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BillingModeResponse) GetBillingMode() string {
	if x != nil {
		return x.BillingMode
	}
	return ""
}

func (x *BillingModeResponse) GetIsSelfPaid() bool {
	if x != nil {
		return x.IsSelfPaid
	}
	return false
}

type CheckCreditBalanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId   string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EstimatedCredits int64                  `protobuf:"varint,2,opt,name=estimated_credits,json=estimatedCredits,proto3" json:"estimated_credits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckCreditBalanceRequest) Reset() {
	*x = CheckCreditBalanceRequest{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCreditBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCreditBalanceRequest) ProtoMessage() {}

func (x *CheckCreditBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCreditBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckCreditBalanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *CheckCreditBalanceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CheckCreditBalanceRequest) GetEstimatedCredits() int64 {
	if x != nil {
		return x.EstimatedCredits
	}
	return 0
}

type CheckCreditBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Sufficient    bool                   `protobuf:"varint,3,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCreditBalanceResponse) Reset() {
	*x = CheckCreditBalanceResponse{}
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCreditBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCreditBalanceResponse) ProtoMessage() {}

func (x *CheckCreditBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCreditBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckCreditBalanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *CheckCreditBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckCreditBalanceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CheckCreditBalanceResponse) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

func (x *CheckCreditBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_pkg_rpc_v1_billing_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/rpc/v1/billing.proto\x12\n" +
	"zgi.rpc.v1\"\xab\x02\n" +
	"\x15PreDeductQuotaRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11estimated_credits\x18\x02 \x01(\x03R\x10estimatedCredits\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x06 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tR\tattemptId\"\xc2\x01\n" +
	"\x16PreDeductQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fremaining_quota\x18\x04 \x01(\x03R\x0eremainingQuota\x12!\n" +
	"\fdeduction_id\x18\x05 \x01(\tR\vdeductionId\"\xa9\a\n" +
	"\x12SettleQuotaRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fdeduction_id\x18\x02 \x01(\tR\vdeductionId\x12+\n" +
	"\x11estimated_credits\x18\x03 \x01(\x03R\x10estimatedCredits\x12%\n" +
	"\x0eactual_credits\x18\x04 \x01(\x03R\ractualCredits\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"input_cost\x18\b \x01(\x01R\tinputCost\x12\x1f\n" +
	"\voutput_cost\x18\t \x01(\x01R\n" +
	"outputCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\n" +
	" \x01(\x01R\ttotalCost\x12\x19\n" +
	"\bmodel_id\x18\v \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\f \x01(\tR\tmodelName\x12\x1f\n" +
	"\vprovider_id\x18\r \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x0e \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x0f \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x10 \x01(\tR\trequestId\x12#\n" +
	"\rresponse_time\x18\x11 \x01(\x03R\fresponseTime\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x13 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x14 \x01(\tR\taccountId\x12\x15\n" +
	"\x06app_id\x18\x15 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_type\x18\x16 \x01(\tR\aappType\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x17 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x18 \x01(\tR\tuserAgent\x12!\n" +
	"\fis_streaming\x18\x19 \x01(\bR\visStreaming\x12.\n" +
	"\x13use_system_provider\x18\x1a \x01(\bR\x11useSystemProvider\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x1b \x01(\tR\tattemptId\"\xf0\x01\n" +
	"\x13SettleQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fremaining_quota\x18\x03 \x01(\x03R\x0eremainingQuota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x04 \x01(\x03R\tusedQuota\x12)\n" +
	"\x10refunded_credits\x18\x05 \x01(\x03R\x0frefundedCredits\x12'\n" +
	"\x0fsettled_credits\x18\x06 \x01(\x03R\x0esettledCredits\"\xb0\x01\n" +
	"\x18CalculateDualCostRequest\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\"\xbe\x02\n" +
	"\x10DualCostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rinput_credits\x18\x03 \x01(\x03R\finputCredits\x12%\n" +
	"\x0eoutput_credits\x18\x04 \x01(\x03R\routputCredits\x12#\n" +
	"\rtotal_credits\x18\x05 \x01(\x03R\ftotalCredits\x12\x1b\n" +
	"\tinput_usd\x18\x06 \x01(\x01R\binputUsd\x12\x1d\n" +
	"\n" +
	"output_usd\x18\a \x01(\x01R\toutputUsd\x12\x1b\n" +
	"\ttotal_usd\x18\b \x01(\x01R\btotalUsd\x12!\n" +
	"\fbilling_mode\x18\t \x01(\tR\vbillingMode\"\xb4\x05\n" +
	"\x12SettleUsageRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x05 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12#\n" +
	"\rprompt_tokens\x18\b \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\t \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\n" +
	" \x01(\x05R\vtotalTokens\x12#\n" +
	"\rresponse_time\x18\v \x01(\x03R\fresponseTime\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x0e \x01(\tR\taccountId\x12\x15\n" +
	"\x06app_id\x18\x0f \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_type\x18\x10 \x01(\tR\aappType\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x11 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x12 \x01(\tR\tuserAgent\x12!\n" +
	"\fis_streaming\x18\x13 \x01(\bR\visStreaming\x12.\n" +
	"\x13use_system_provider\x18\x14 \x01(\bR\x11useSystemProvider\"\xdf\x01\n" +
	"\x13SettleUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10credits_deducted\x18\x03 \x01(\x03R\x0fcreditsDeducted\x12\x19\n" +
	"\busd_cost\x18\x04 \x01(\x01R\ausdCost\x12!\n" +
	"\fbilling_mode\x18\x05 \x01(\tR\vbillingMode\x12 \n" +
	"\fis_self_paid\x18\x06 \x01(\bR\n" +
	"isSelfPaid\"@\n" +
	"\x15GetBillingModeRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\x99\x01\n" +
	"\x13BillingModeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\fbilling_mode\x18\x03 \x01(\tR\vbillingMode\x12 \n" +
	"\fis_self_paid\x18\x04 \x01(\bR\n" +
	"isSelfPaid\"q\n" +
	"\x19CheckCreditBalanceRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11estimated_credits\x18\x02 \x01(\x03R\x10estimatedCredits\"\x95\x01\n" +
	"\x1aCheckCreditBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x03 \x01(\bR\n" +
	"sufficient\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance2\xaa\x04\n" +
	"\x0eBillingService\x12W\n" +
	"\x0ePreDeductQuota\x12!.zgi.rpc.v1.PreDeductQuotaRequest\x1a\".zgi.rpc.v1.PreDeductQuotaResponse\x12N\n" +
	"\vSettleQuota\x12\x1e.zgi.rpc.v1.SettleQuotaRequest\x1a\x1f.zgi.rpc.v1.SettleQuotaResponse\x12W\n" +
	"\x11CalculateDualCost\x12$.zgi.rpc.v1.CalculateDualCostRequest\x1a\x1c.zgi.rpc.v1.DualCostResponse\x12[\n" +
	"\x18SettleUsageWithDualTrack\x12\x1e.zgi.rpc.v1.SettleUsageRequest\x1a\x1f.zgi.rpc.v1.SettleUsageResponse\x12T\n" +
	"\x0eGetBillingMode\x12!.zgi.rpc.v1.GetBillingModeRequest\x1a\x1f.zgi.rpc.v1.BillingModeResponse\x12c\n" +
	"\x12CheckCreditBalance\x12%.zgi.rpc.v1.CheckCreditBalanceRequest\x1a&.zgi.rpc.v1.CheckCreditBalanceResponseB'Z%github.com/zgiai/ginext/pkg/rpc/v1;v1b\x06proto3"

var (
	file_pkg_rpc_v1_billing_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_billing_proto_rawDescData []byte
)

func file_pkg_rpc_v1_billing_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_billing_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_billing_proto_rawDesc), len(file_pkg_rpc_v1_billing_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_billing_proto_rawDescData
}

var file_pkg_rpc_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_rpc_v1_billing_proto_goTypes = []any{
	(*PreDeductQuotaRequest)(nil),      // 0: zgi.rpc.v1.PreDeductQuotaRequest
	(*PreDeductQuotaResponse)(nil),     // 1: zgi.rpc.v1.PreDeductQuotaResponse
	(*SettleQuotaRequest)(nil),         // 2: zgi.rpc.v1.SettleQuotaRequest
	(*SettleQuotaResponse)(nil),        // 3: zgi.rpc.v1.SettleQuotaResponse
	(*CalculateDualCostRequest)(nil),   // 4: zgi.rpc.v1.CalculateDualCostRequest
	(*DualCostResponse)(nil),           // 5: zgi.rpc.v1.DualCostResponse
	(*SettleUsageRequest)(nil),         // 6: zgi.rpc.v1.SettleUsageRequest
	(*SettleUsageResponse)(nil),        // 7: zgi.rpc.v1.SettleUsageResponse
	(*GetBillingModeRequest)(nil),      // 8: zgi.rpc.v1.GetBillingModeRequest
	(*BillingModeResponse)(nil),        // 9: zgi.rpc.v1.BillingModeResponse
	(*CheckCreditBalanceRequest)(nil),  // 10: zgi.rpc.v1.CheckCreditBalanceRequest
	(*CheckCreditBalanceResponse)(nil), // 11: zgi.rpc.v1.CheckCreditBalanceResponse
}
var file_pkg_rpc_v1_billing_proto_depIdxs = []int32{
	0,  // 0: zgi.rpc.v1.BillingService.PreDeductQuota:input_type -> zgi.rpc.v1.PreDeductQuotaRequest
	2,  // 1: zgi.rpc.v1.BillingService.SettleQuota:input_type -> zgi.rpc.v1.SettleQuotaRequest
	4,  // 2: zgi.rpc.v1.BillingService.CalculateDualCost:input_type -> zgi.rpc.v1.CalculateDualCostRequest
	6,  // 3: zgi.rpc.v1.BillingService.SettleUsageWithDualTrack:input_type -> zgi.rpc.v1.SettleUsageRequest
	8,  // 4: zgi.rpc.v1.BillingService.GetBillingMode:input_type -> zgi.rpc.v1.GetBillingModeRequest
	10, // 5: zgi.rpc.v1.BillingService.CheckCreditBalance:input_type -> zgi.rpc.v1.CheckCreditBalanceRequest
	1,  // 6: zgi.rpc.v1.BillingService.PreDeductQuota:output_type -> zgi.rpc.v1.PreDeductQuotaResponse
	3,  // 7: zgi.rpc.v1.BillingService.SettleQuota:output_type -> zgi.rpc.v1.SettleQuotaResponse
	5,  // 8: zgi.rpc.v1.BillingService.CalculateDualCost:output_type -> zgi.rpc.v1.DualCostResponse
	7,  // 9: zgi.rpc.v1.BillingService.SettleUsageWithDualTrack:output_type -> zgi.rpc.v1.SettleUsageResponse
	9,  // 10: zgi.rpc.v1.BillingService.GetBillingMode:output_type -> zgi.rpc.v1.BillingModeResponse
	11, // 11: zgi.rpc.v1.BillingService.CheckCreditBalance:output_type -> zgi.rpc.v1.CheckCreditBalanceResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_billing_proto_init() }
func file_pkg_rpc_v1_billing_proto_init() {
	if File_pkg_rpc_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_billing_proto_rawDesc), len(file_pkg_rpc_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_billing_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_billing_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_billing_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_billing_proto = out.File
	file_pkg_rpc_v1_billing_proto_goTypes = nil
	file_pkg_rpc_v1_billing_proto_depIdxs = nil
}
