// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/rpc/v1/billing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_PreDeductQuota_FullMethodName           = "/zgi.rpc.v1.BillingService/PreDeductQuota"
	BillingService_SettleQuota_FullMethodName              = "/zgi.rpc.v1.BillingService/SettleQuota"
	BillingService_CalculateDualCost_FullMethodName        = "/zgi.rpc.v1.BillingService/CalculateDualCost"
	BillingService_SettleUsageWithDualTrack_FullMethodName = "/zgi.rpc.v1.BillingService/SettleUsageWithDualTrack"
	BillingService_GetBillingMode_FullMethodName           = "/zgi.rpc.v1.BillingService/GetBillingMode"
	BillingService_CheckCreditBalance_FullMethodName       = "/zgi.rpc.v1.BillingService/CheckCreditBalance"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	PreDeductQuota(ctx context.Context, in *PreDeductQuotaRequest, opts ...grpc.CallOption) (*PreDeductQuotaResponse, error)
	SettleQuota(ctx context.Context, in *SettleQuotaRequest, opts ...grpc.CallOption) (*SettleQuotaResponse, error)
	CalculateDualCost(ctx context.Context, in *CalculateDualCostRequest, opts ...grpc.CallOption) (*DualCostResponse, error)
	SettleUsageWithDualTrack(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*SettleUsageResponse, error)
	GetBillingMode(ctx context.Context, in *GetBillingModeRequest, opts ...grpc.CallOption) (*BillingModeResponse, error)
	CheckCreditBalance(ctx context.Context, in *CheckCreditBalanceRequest, opts ...grpc.CallOption) (*CheckCreditBalanceResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) PreDeductQuota(ctx context.Context, in *PreDeductQuotaRequest, opts ...grpc.CallOption) (*PreDeductQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreDeductQuotaResponse)
	err := c.cc.Invoke(ctx, BillingService_PreDeductQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) SettleQuota(ctx context.Context, in *SettleQuotaRequest, opts ...grpc.CallOption) (*SettleQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleQuotaResponse)
	err := c.cc.Invoke(ctx, BillingService_SettleQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CalculateDualCost(ctx context.Context, in *CalculateDualCostRequest, opts ...grpc.CallOption) (*DualCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DualCostResponse)
	err := c.cc.Invoke(ctx, BillingService_CalculateDualCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) SettleUsageWithDualTrack(ctx context.Context, in *SettleUsageRequest, opts ...grpc.CallOption) (*SettleUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleUsageResponse)
	err := c.cc.Invoke(ctx, BillingService_SettleUsageWithDualTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBillingMode(ctx context.Context, in *GetBillingModeRequest, opts ...grpc.CallOption) (*BillingModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillingModeResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBillingMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CheckCreditBalance(ctx context.Context, in *CheckCreditBalanceRequest, opts ...grpc.CallOption) (*CheckCreditBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCreditBalanceResponse)
	err := c.cc.Invoke(ctx, BillingService_CheckCreditBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	PreDeductQuota(context.Context, *PreDeductQuotaRequest) (*PreDeductQuotaResponse, error)
	SettleQuota(context.Context, *SettleQuotaRequest) (*SettleQuotaResponse, error)
	CalculateDualCost(context.Context, *CalculateDualCostRequest) (*DualCostResponse, error)
	SettleUsageWithDualTrack(context.Context, *SettleUsageRequest) (*SettleUsageResponse, error)
	GetBillingMode(context.Context, *GetBillingModeRequest) (*BillingModeResponse, error)
	CheckCreditBalance(context.Context, *CheckCreditBalanceRequest) (*CheckCreditBalanceResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) PreDeductQuota(context.Context, *PreDeductQuotaRequest) (*PreDeductQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreDeductQuota not implemented")
}
func (UnimplementedBillingServiceServer) SettleQuota(context.Context, *SettleQuotaRequest) (*SettleQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleQuota not implemented")
}
func (UnimplementedBillingServiceServer) CalculateDualCost(context.Context, *CalculateDualCostRequest) (*DualCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDualCost not implemented")
}
func (UnimplementedBillingServiceServer) SettleUsageWithDualTrack(context.Context, *SettleUsageRequest) (*SettleUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleUsageWithDualTrack not implemented")
}
func (UnimplementedBillingServiceServer) GetBillingMode(context.Context, *GetBillingModeRequest) (*BillingModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillingMode not implemented")
}
func (UnimplementedBillingServiceServer) CheckCreditBalance(context.Context, *CheckCreditBalanceRequest) (*CheckCreditBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCreditBalance not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_PreDeductQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreDeductQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).PreDeductQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_PreDeductQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).PreDeductQuota(ctx, req.(*PreDeductQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_SettleQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).SettleQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_SettleQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).SettleQuota(ctx, req.(*SettleQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CalculateDualCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDualCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CalculateDualCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CalculateDualCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CalculateDualCost(ctx, req.(*CalculateDualCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_SettleUsageWithDualTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).SettleUsageWithDualTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_SettleUsageWithDualTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).SettleUsageWithDualTrack(ctx, req.(*SettleUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBillingMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillingModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBillingMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBillingMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBillingMode(ctx, req.(*GetBillingModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CheckCreditBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCreditBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CheckCreditBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CheckCreditBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CheckCreditBalance(ctx, req.(*CheckCreditBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zgi.rpc.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreDeductQuota",
			Handler:    _BillingService_PreDeductQuota_Handler,
		},
		{
			MethodName: "SettleQuota",
			Handler:    _BillingService_SettleQuota_Handler,
		},
		{
			MethodName: "CalculateDualCost",
			Handler:    _BillingService_CalculateDualCost_Handler,
		},
		{
			MethodName: "SettleUsageWithDualTrack",
			Handler:    _BillingService_SettleUsageWithDualTrack_Handler,
		},
		{
			MethodName: "GetBillingMode",
			Handler:    _BillingService_GetBillingMode_Handler,
		},
		{
			MethodName: "CheckCreditBalance",
			Handler:    _BillingService_CheckCreditBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/v1/billing.proto",
}
