// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/rpc/v1/catalog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetPublishedCatalog_FullMethodName   = "/zgi.rpc.v1.CatalogService/GetPublishedCatalog"
	CatalogService_WatchCatalogPublishes_FullMethodName = "/zgi.rpc.v1.CatalogService/WatchCatalogPublishes"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetPublishedCatalog(ctx context.Context, in *GetPublishedCatalogRequest, opts ...grpc.CallOption) (*GetPublishedCatalogResponse, error)
	WatchCatalogPublishes(ctx context.Context, in *WatchCatalogPublishesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatalogPublishEvent], error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetPublishedCatalog(ctx context.Context, in *GetPublishedCatalogRequest, opts ...grpc.CallOption) (*GetPublishedCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishedCatalogResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetPublishedCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) WatchCatalogPublishes(ctx context.Context, in *WatchCatalogPublishesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatalogPublishEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CatalogService_ServiceDesc.Streams[0], CatalogService_WatchCatalogPublishes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCatalogPublishesRequest, CatalogPublishEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CatalogService_WatchCatalogPublishesClient = grpc.ServerStreamingClient[CatalogPublishEvent]

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	GetPublishedCatalog(context.Context, *GetPublishedCatalogRequest) (*GetPublishedCatalogResponse, error)
	WatchCatalogPublishes(*WatchCatalogPublishesRequest, grpc.ServerStreamingServer[CatalogPublishEvent]) error
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetPublishedCatalog(context.Context, *GetPublishedCatalogRequest) (*GetPublishedCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedCatalog not implemented")
}
func (UnimplementedCatalogServiceServer) WatchCatalogPublishes(*WatchCatalogPublishesRequest, grpc.ServerStreamingServer[CatalogPublishEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchCatalogPublishes not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetPublishedCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetPublishedCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetPublishedCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetPublishedCatalog(ctx, req.(*GetPublishedCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_WatchCatalogPublishes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCatalogPublishesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServiceServer).WatchCatalogPublishes(m, &grpc.GenericServerStream[WatchCatalogPublishesRequest, CatalogPublishEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CatalogService_WatchCatalogPublishesServer = grpc.ServerStreamingServer[CatalogPublishEvent]

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zgi.rpc.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublishedCatalog",
			Handler:    _CatalogService_GetPublishedCatalog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCatalogPublishes",
			Handler:       _CatalogService_WatchCatalogPublishes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/rpc/v1/catalog.proto",
}
