// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: pkg/rpc/v1/catalog.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchCatalogPublishesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastSeenVersion int64                  `protobuf:"varint,1,opt,name=last_seen_version,json=lastSeenVersion,proto3" json:"last_seen_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchCatalogPublishesRequest) Reset() {
	*x = WatchCatalogPublishesRequest{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCatalogPublishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCatalogPublishesRequest) ProtoMessage() {}

func (x *WatchCatalogPublishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCatalogPublishesRequest.ProtoReflect.Descriptor instead.
func (*WatchCatalogPublishesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *WatchCatalogPublishesRequest) GetLastSeenVersion() int64 {
	if x != nil {
		return x.LastSeenVersion
	}
	return 0
}

type CatalogPublishEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,2,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogPublishEvent) Reset() {
	*x = CatalogPublishEvent{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogPublishEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogPublishEvent) ProtoMessage() {}

func (x *CatalogPublishEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogPublishEvent.ProtoReflect.Descriptor instead.
func (*CatalogPublishEvent) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogPublishEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CatalogPublishEvent) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

type GetPublishedCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedCatalogRequest) Reset() {
	*x = GetPublishedCatalogRequest{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedCatalogRequest) ProtoMessage() {}

func (x *GetPublishedCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedCatalogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedCatalogRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetPublishedCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,2,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Providers     []*CatalogProvider     `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	Models        []*CatalogModel        `protobuf:"bytes,4,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedCatalogResponse) Reset() {
	*x = GetPublishedCatalogResponse{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedCatalogResponse) ProtoMessage() {}

func (x *GetPublishedCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetPublishedCatalogResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublishedCatalogResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetPublishedCatalogResponse) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *GetPublishedCatalogResponse) GetProviders() []*CatalogProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *GetPublishedCatalogResponse) GetModels() []*CatalogModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type CatalogProvider struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderName    string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tagline         string                 `protobuf:"bytes,4,opt,name=tagline,proto3" json:"tagline,omitempty"`
	LogoUrl         string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Website         string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	ApiDocsUrl      string                 `protobuf:"bytes,7,opt,name=api_docs_url,json=apiDocsUrl,proto3" json:"api_docs_url,omitempty"`
	PricingUrl      string                 `protobuf:"bytes,8,opt,name=pricing_url,json=pricingUrl,proto3" json:"pricing_url,omitempty"`
	CountryCode     string                 `protobuf:"bytes,9,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	FoundedYear     int32                  `protobuf:"varint,10,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	IsActive        bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsSystemEnabled bool                   `protobuf:"varint,13,opt,name=is_system_enabled,json=isSystemEnabled,proto3" json:"is_system_enabled,omitempty"`
	MetadataJson    string                 `protobuf:"bytes,14,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CatalogProvider) Reset() {
	*x = CatalogProvider{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogProvider) ProtoMessage() {}

func (x *CatalogProvider) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogProvider.ProtoReflect.Descriptor instead.
func (*CatalogProvider) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *CatalogProvider) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CatalogProvider) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CatalogProvider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogProvider) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *CatalogProvider) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CatalogProvider) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CatalogProvider) GetApiDocsUrl() string {
	if x != nil {
		return x.ApiDocsUrl
	}
	return ""
}

func (x *CatalogProvider) GetPricingUrl() string {
	if x != nil {
		return x.PricingUrl
	}
	return ""
}

func (x *CatalogProvider) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CatalogProvider) GetFoundedYear() int32 {
	if x != nil {
		return x.FoundedYear
	}
	return 0
}

func (x *CatalogProvider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CatalogProvider) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CatalogProvider) GetIsSystemEnabled() bool {
	if x != nil {
		return x.IsSystemEnabled
	}
	return false
}

func (x *CatalogProvider) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type CatalogModel struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Provider                string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model                   string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ModelName               string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Type                    string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Family                  string                 `protobuf:"bytes,5,opt,name=family,proto3" json:"family,omitempty"`
	FamilyName              string                 `protobuf:"bytes,6,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Status                  string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Tagline                 string                 `protobuf:"bytes,8,opt,name=tagline,proto3" json:"tagline,omitempty"`
	IsFlagship              bool                   `protobuf:"varint,9,opt,name=is_flagship,json=isFlagship,proto3" json:"is_flagship,omitempty"`
	IsRecommended           bool                   `protobuf:"varint,10,opt,name=is_recommended,json=isRecommended,proto3" json:"is_recommended,omitempty"`
	IsFeatured              bool                   `protobuf:"varint,11,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsNew                   bool                   `protobuf:"varint,12,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	AccessType              string                 `protobuf:"bytes,13,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	Currency                string                 `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	ContextWindow           int32                  `protobuf:"varint,15,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxOutputTokens         int32                  `protobuf:"varint,16,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	InputPrice              float64                `protobuf:"fixed64,17,opt,name=input_price,json=inputPrice,proto3" json:"input_price,omitempty"`
	OutputPrice             float64                `protobuf:"fixed64,18,opt,name=output_price,json=outputPrice,proto3" json:"output_price,omitempty"`
	CachedInputPrice        float64                `protobuf:"fixed64,19,opt,name=cached_input_price,json=cachedInputPrice,proto3" json:"cached_input_price,omitempty"`
	UseCases                []string               `protobuf:"bytes,20,rep,name=use_cases,json=useCases,proto3" json:"use_cases,omitempty"`
	InputModalities         []string               `protobuf:"bytes,21,rep,name=input_modalities,json=inputModalities,proto3" json:"input_modalities,omitempty"`
	OutputModalities        []string               `protobuf:"bytes,22,rep,name=output_modalities,json=outputModalities,proto3" json:"output_modalities,omitempty"`
	KnowledgeCutoff         string                 `protobuf:"bytes,23,opt,name=knowledge_cutoff,json=knowledgeCutoff,proto3" json:"knowledge_cutoff,omitempty"`
	IsActive                bool                   `protobuf:"varint,24,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsSystemEnabled         bool                   `protobuf:"varint,25,opt,name=is_system_enabled,json=isSystemEnabled,proto3" json:"is_system_enabled,omitempty"`
	SupportedParametersJson string                 `protobuf:"bytes,26,opt,name=supported_parameters_json,json=supportedParametersJson,proto3" json:"supported_parameters_json,omitempty"`
	ConfigParametersJson    string                 `protobuf:"bytes,27,opt,name=config_parameters_json,json=configParametersJson,proto3" json:"config_parameters_json,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CatalogModel) Reset() {
	*x = CatalogModel{}
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogModel) ProtoMessage() {}

func (x *CatalogModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogModel.ProtoReflect.Descriptor instead.
func (*CatalogModel) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *CatalogModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CatalogModel) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CatalogModel) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CatalogModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CatalogModel) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *CatalogModel) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *CatalogModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CatalogModel) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *CatalogModel) GetIsFlagship() bool {
	if x != nil {
		return x.IsFlagship
	}
	return false
}

func (x *CatalogModel) GetIsRecommended() bool {
	if x != nil {
		return x.IsRecommended
	}
	return false
}

func (x *CatalogModel) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *CatalogModel) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CatalogModel) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *CatalogModel) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CatalogModel) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *CatalogModel) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *CatalogModel) GetInputPrice() float64 {
	if x != nil {
		return x.InputPrice
	}
	return 0
}

func (x *CatalogModel) GetOutputPrice() float64 {
	if x != nil {
		return x.OutputPrice
	}
	return 0
}

func (x *CatalogModel) GetCachedInputPrice() float64 {
	if x != nil {
		return x.CachedInputPrice
	}
	return 0
}

func (x *CatalogModel) GetUseCases() []string {
	if x != nil {
		return x.UseCases
	}
	return nil
}

func (x *CatalogModel) GetInputModalities() []string {
	if x != nil {
		return x.InputModalities
	}
	return nil
}

func (x *CatalogModel) GetOutputModalities() []string {
	if x != nil {
		return x.OutputModalities
	}
	return nil
}

func (x *CatalogModel) GetKnowledgeCutoff() string {
	if x != nil {
		return x.KnowledgeCutoff
	}
	return ""
}

func (x *CatalogModel) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CatalogModel) GetIsSystemEnabled() bool {
	if x != nil {
		return x.IsSystemEnabled
	}
	return false
}

func (x *CatalogModel) GetSupportedParametersJson() string {
	if x != nil {
		return x.SupportedParametersJson
	}
	return ""
}

func (x *CatalogModel) GetConfigParametersJson() string {
	if x != nil {
		return x.ConfigParametersJson
	}
	return ""
}

var File_pkg_rpc_v1_catalog_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/rpc/v1/catalog.proto\x12\n" +
	"zgi.rpc.v1\"J\n" +
	"\x1cWatchCatalogPublishesRequest\x12*\n" +
	"\x11last_seen_version\x18\x01 \x01(\x03R\x0flastSeenVersion\"R\n" +
	"\x13CatalogPublishEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12!\n" +
	"\fpublished_at\x18\x02 \x01(\x03R\vpublishedAt\"6\n" +
	"\x1aGetPublishedCatalogRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\xc7\x01\n" +
	"\x1bGetPublishedCatalogResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12!\n" +
	"\fpublished_at\x18\x02 \x01(\x03R\vpublishedAt\x129\n" +
	"\tproviders\x18\x03 \x03(\v2\x1b.zgi.rpc.v1.CatalogProviderR\tproviders\x120\n" +
	"\x06models\x18\x04 \x03(\v2\x18.zgi.rpc.v1.CatalogModelR\x06models\"\xd2\x03\n" +
	"\x0fCatalogProvider\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\atagline\x18\x04 \x01(\tR\atagline\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12 \n" +
	"\fapi_docs_url\x18\a \x01(\tR\n" +
	"apiDocsUrl\x12\x1f\n" +
	"\vpricing_url\x18\b \x01(\tR\n" +
	"pricingUrl\x12!\n" +
	"\fcountry_code\x18\t \x01(\tR\vcountryCode\x12!\n" +
	"\ffounded_year\x18\n" +
	" \x01(\x05R\vfoundedYear\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12*\n" +
	"\x11is_system_enabled\x18\r \x01(\bR\x0fisSystemEnabled\x12#\n" +
	"\rmetadata_json\x18\x0e \x01(\tR\fmetadataJson\"\xbb\a\n" +
	"\fCatalogModel\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06family\x18\x05 \x01(\tR\x06family\x12\x1f\n" +
	"\vfamily_name\x18\x06 \x01(\tR\n" +
	"familyName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\atagline\x18\b \x01(\tR\atagline\x12\x1f\n" +
	"\vis_flagship\x18\t \x01(\bR\n" +
	"isFlagship\x12%\n" +
	"\x0eis_recommended\x18\n" +
	" \x01(\bR\risRecommended\x12\x1f\n" +
	"\vis_featured\x18\v \x01(\bR\n" +
	"isFeatured\x12\x15\n" +
	"\x06is_new\x18\f \x01(\bR\x05isNew\x12\x1f\n" +
	"\vaccess_type\x18\r \x01(\tR\n" +
	"accessType\x12\x1a\n" +
	"\bcurrency\x18\x0e \x01(\tR\bcurrency\x12%\n" +
	"\x0econtext_window\x18\x0f \x01(\x05R\rcontextWindow\x12*\n" +
	"\x11max_output_tokens\x18\x10 \x01(\x05R\x0fmaxOutputTokens\x12\x1f\n" +
	"\vinput_price\x18\x11 \x01(\x01R\n" +
	"inputPrice\x12!\n" +
	"\foutput_price\x18\x12 \x01(\x01R\voutputPrice\x12,\n" +
	"\x12cached_input_price\x18\x13 \x01(\x01R\x10cachedInputPrice\x12\x1b\n" +
	"\tuse_cases\x18\x14 \x03(\tR\buseCases\x12)\n" +
	"\x10input_modalities\x18\x15 \x03(\tR\x0finputModalities\x12+\n" +
	"\x11output_modalities\x18\x16 \x03(\tR\x10outputModalities\x12)\n" +
	"\x10knowledge_cutoff\x18\x17 \x01(\tR\x0fknowledgeCutoff\x12\x1b\n" +
	"\tis_active\x18\x18 \x01(\bR\bisActive\x12*\n" +
	"\x11is_system_enabled\x18\x19 \x01(\bR\x0fisSystemEnabled\x12:\n" +
	"\x19supported_parameters_json\x18\x1a \x01(\tR\x17supportedParametersJson\x124\n" +
	"\x16config_parameters_json\x18\x1b \x01(\tR\x14configParametersJson2\xde\x01\n" +
	"\x0eCatalogService\x12f\n" +
	"\x13GetPublishedCatalog\x12&.zgi.rpc.v1.GetPublishedCatalogRequest\x1a'.zgi.rpc.v1.GetPublishedCatalogResponse\x12d\n" +
	"\x15WatchCatalogPublishes\x12(.zgi.rpc.v1.WatchCatalogPublishesRequest\x1a\x1f.zgi.rpc.v1.CatalogPublishEvent0\x01B'Z%github.com/zgiai/ginext/pkg/rpc/v1;v1b\x06proto3"

var (
	file_pkg_rpc_v1_catalog_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_catalog_proto_rawDescData []byte
)

func file_pkg_rpc_v1_catalog_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_catalog_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_catalog_proto_rawDesc), len(file_pkg_rpc_v1_catalog_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_catalog_proto_rawDescData
}

var file_pkg_rpc_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_rpc_v1_catalog_proto_goTypes = []any{
	(*WatchCatalogPublishesRequest)(nil), // 0: zgi.rpc.v1.WatchCatalogPublishesRequest
	(*CatalogPublishEvent)(nil),          // 1: zgi.rpc.v1.CatalogPublishEvent
	(*GetPublishedCatalogRequest)(nil),   // 2: zgi.rpc.v1.GetPublishedCatalogRequest
	(*GetPublishedCatalogResponse)(nil),  // 3: zgi.rpc.v1.GetPublishedCatalogResponse
	(*CatalogProvider)(nil),              // 4: zgi.rpc.v1.CatalogProvider
	(*CatalogModel)(nil),                 // 5: zgi.rpc.v1.CatalogModel
}
var file_pkg_rpc_v1_catalog_proto_depIdxs = []int32{
	4, // 0: zgi.rpc.v1.GetPublishedCatalogResponse.providers:type_name -> zgi.rpc.v1.CatalogProvider
	5, // 1: zgi.rpc.v1.GetPublishedCatalogResponse.models:type_name -> zgi.rpc.v1.CatalogModel
	2, // 2: zgi.rpc.v1.CatalogService.GetPublishedCatalog:input_type -> zgi.rpc.v1.GetPublishedCatalogRequest
	0, // 3: zgi.rpc.v1.CatalogService.WatchCatalogPublishes:input_type -> zgi.rpc.v1.WatchCatalogPublishesRequest
	3, // 4: zgi.rpc.v1.CatalogService.GetPublishedCatalog:output_type -> zgi.rpc.v1.GetPublishedCatalogResponse
	1, // 5: zgi.rpc.v1.CatalogService.WatchCatalogPublishes:output_type -> zgi.rpc.v1.CatalogPublishEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_catalog_proto_init() }
func file_pkg_rpc_v1_catalog_proto_init() {
	if File_pkg_rpc_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_catalog_proto_rawDesc), len(file_pkg_rpc_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_catalog_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_catalog_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_catalog_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_catalog_proto = out.File
	file_pkg_rpc_v1_catalog_proto_goTypes = nil
	file_pkg_rpc_v1_catalog_proto_depIdxs = nil
}
