// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: pkg/rpc/v1/channel.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelService_ListOfficialChannels_FullMethodName = "/zgi.rpc.v1.ChannelService/ListOfficialChannels"
	ChannelService_WatchChannels_FullMethodName        = "/zgi.rpc.v1.ChannelService/WatchChannels"
)

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChannelService provides access to official LLM channels.
type ChannelServiceClient interface {
	// ListOfficialChannels returns all platform-provided channels.
	ListOfficialChannels(ctx context.Context, in *ListOfficialChannelsRequest, opts ...grpc.CallOption) (*ListOfficialChannelsResponse, error)
	// WatchChannels streams real-time channel updates to subscribers.
	// Gateway instances subscribe to this stream to receive instant notifications
	// when channels are created, updated, enabled, or disabled.
	WatchChannels(ctx context.Context, in *WatchChannelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChannelEvent], error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) ListOfficialChannels(ctx context.Context, in *ListOfficialChannelsRequest, opts ...grpc.CallOption) (*ListOfficialChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfficialChannelsResponse)
	err := c.cc.Invoke(ctx, ChannelService_ListOfficialChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) WatchChannels(ctx context.Context, in *WatchChannelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChannelEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[0], ChannelService_WatchChannels_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchChannelsRequest, ChannelEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_WatchChannelsClient = grpc.ServerStreamingClient[ChannelEvent]

// ChannelServiceServer is the server API for ChannelService service.
// All implementations must embed UnimplementedChannelServiceServer
// for forward compatibility.
//
// ChannelService provides access to official LLM channels.
type ChannelServiceServer interface {
	// ListOfficialChannels returns all platform-provided channels.
	ListOfficialChannels(context.Context, *ListOfficialChannelsRequest) (*ListOfficialChannelsResponse, error)
	// WatchChannels streams real-time channel updates to subscribers.
	// Gateway instances subscribe to this stream to receive instant notifications
	// when channels are created, updated, enabled, or disabled.
	WatchChannels(*WatchChannelsRequest, grpc.ServerStreamingServer[ChannelEvent]) error
	mustEmbedUnimplementedChannelServiceServer()
}

// UnimplementedChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServiceServer struct{}

func (UnimplementedChannelServiceServer) ListOfficialChannels(context.Context, *ListOfficialChannelsRequest) (*ListOfficialChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOfficialChannels not implemented")
}
func (UnimplementedChannelServiceServer) WatchChannels(*WatchChannelsRequest, grpc.ServerStreamingServer[ChannelEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchChannels not implemented")
}
func (UnimplementedChannelServiceServer) mustEmbedUnimplementedChannelServiceServer() {}
func (UnimplementedChannelServiceServer) testEmbeddedByValue()                        {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_ListOfficialChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfficialChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ListOfficialChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ListOfficialChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ListOfficialChannels(ctx, req.(*ListOfficialChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_WatchChannels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchChannelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChannelServiceServer).WatchChannels(m, &grpc.GenericServerStream[WatchChannelsRequest, ChannelEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_WatchChannelsServer = grpc.ServerStreamingServer[ChannelEvent]

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zgi.rpc.v1.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOfficialChannels",
			Handler:    _ChannelService_ListOfficialChannels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchChannels",
			Handler:       _ChannelService_WatchChannels_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/rpc/v1/channel.proto",
}
