// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/rpc/v1/channel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType defines the type of change that occurred.
type ChannelEvent_EventType int32

const (
	ChannelEvent_SNAPSHOT ChannelEvent_EventType = 0 // Full snapshot (sent on initial connection)
	ChannelEvent_CREATED  ChannelEvent_EventType = 1 // New channel created
	ChannelEvent_UPDATED  ChannelEvent_EventType = 2 // Existing channel modified
	ChannelEvent_DELETED  ChannelEvent_EventType = 3 // Channel deleted
	ChannelEvent_ENABLED  ChannelEvent_EventType = 4 // Channel enabled (is_enabled = true)
	ChannelEvent_DISABLED ChannelEvent_EventType = 5 // Channel disabled (is_enabled = false)
)

// Enum value maps for ChannelEvent_EventType.
var (
	ChannelEvent_EventType_name = map[int32]string{
		0: "SNAPSHOT",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
		4: "ENABLED",
		5: "DISABLED",
	}
	ChannelEvent_EventType_value = map[string]int32{
		"SNAPSHOT": 0,
		"CREATED":  1,
		"UPDATED":  2,
		"DELETED":  3,
		"ENABLED":  4,
		"DISABLED": 5,
	}
)

func (x ChannelEvent_EventType) Enum() *ChannelEvent_EventType {
	p := new(ChannelEvent_EventType)
	*p = x
	return p
}

func (x ChannelEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_rpc_v1_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelEvent_EventType) Type() protoreflect.EnumType {
	return &file_pkg_rpc_v1_channel_proto_enumTypes[0]
}

func (x ChannelEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelEvent_EventType.Descriptor instead.
func (ChannelEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{4, 0}
}

type ListOfficialChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfficialChannelsRequest) Reset() {
	*x = ListOfficialChannelsRequest{}
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfficialChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialChannelsRequest) ProtoMessage() {}

func (x *ListOfficialChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListOfficialChannelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{0}
}

type ListOfficialChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*OfficialChannel     `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfficialChannelsResponse) Reset() {
	*x = ListOfficialChannelsResponse{}
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfficialChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialChannelsResponse) ProtoMessage() {}

func (x *ListOfficialChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListOfficialChannelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ListOfficialChannelsResponse) GetChannels() []*OfficialChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type OfficialChannel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ApiBaseUrl      string                 `protobuf:"bytes,5,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	ApiKeyEncrypted string                 `protobuf:"bytes,6,opt,name=api_key_encrypted,json=apiKeyEncrypted,proto3" json:"api_key_encrypted,omitempty"`
	Models          []string               `protobuf:"bytes,7,rep,name=models,proto3" json:"models,omitempty"`
	Priority        int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight          int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	ModelMaps       map[string]string      `protobuf:"bytes,10,rep,name=model_maps,json=modelMaps,proto3" json:"model_maps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParamOverride   string                 `protobuf:"bytes,11,opt,name=param_override,json=paramOverride,proto3" json:"param_override,omitempty"`    // JSON string
	HeaderOverride  string                 `protobuf:"bytes,12,opt,name=header_override,json=headerOverride,proto3" json:"header_override,omitempty"` // JSON string
	Tags            []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfficialChannel) Reset() {
	*x = OfficialChannel{}
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficialChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficialChannel) ProtoMessage() {}

func (x *OfficialChannel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficialChannel.ProtoReflect.Descriptor instead.
func (*OfficialChannel) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *OfficialChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OfficialChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OfficialChannel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OfficialChannel) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OfficialChannel) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

func (x *OfficialChannel) GetApiKeyEncrypted() string {
	if x != nil {
		return x.ApiKeyEncrypted
	}
	return ""
}

func (x *OfficialChannel) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *OfficialChannel) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *OfficialChannel) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *OfficialChannel) GetModelMaps() map[string]string {
	if x != nil {
		return x.ModelMaps
	}
	return nil
}

func (x *OfficialChannel) GetParamOverride() string {
	if x != nil {
		return x.ParamOverride
	}
	return ""
}

func (x *OfficialChannel) GetHeaderOverride() string {
	if x != nil {
		return x.HeaderOverride
	}
	return ""
}

func (x *OfficialChannel) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *OfficialChannel) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WatchChannelsRequest initiates a streaming subscription to channel updates.
type WatchChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_version allows clients to resume from a specific version after reconnection.
	// If 0 or omitted, server sends full snapshot first.
	FromVersion   int64 `protobuf:"varint,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChannelsRequest) Reset() {
	*x = WatchChannelsRequest{}
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChannelsRequest) ProtoMessage() {}

func (x *WatchChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChannelsRequest.ProtoReflect.Descriptor instead.
func (*WatchChannelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *WatchChannelsRequest) GetFromVersion() int64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

// ChannelEvent represents a change to a platform channel.
type ChannelEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type indicates what kind of change occurred
	Type ChannelEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=zgi.rpc.v1.ChannelEvent_EventType" json:"type,omitempty"`
	// channel contains the full channel data after the change
	Channel *OfficialChannel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// version is a globally incrementing counter for event ordering.
	// Clients can detect missed events by checking for gaps in version numbers.
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// timestamp is when the event was generated (Unix milliseconds)
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelEvent) Reset() {
	*x = ChannelEvent{}
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEvent) ProtoMessage() {}

func (x *ChannelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEvent.ProtoReflect.Descriptor instead.
func (*ChannelEvent) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelEvent) GetType() ChannelEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ChannelEvent_SNAPSHOT
}

func (x *ChannelEvent) GetChannel() *OfficialChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ChannelEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChannelEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_rpc_v1_channel_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/rpc/v1/channel.proto\x12\n" +
	"zgi.rpc.v1\"\x1d\n" +
	"\x1bListOfficialChannelsRequest\"W\n" +
	"\x1cListOfficialChannelsResponse\x127\n" +
	"\bchannels\x18\x01 \x03(\v2\x1b.zgi.rpc.v1.OfficialChannelR\bchannels\"\xf8\x04\n" +
	"\x0fOfficialChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12 \n" +
	"\fapi_base_url\x18\x05 \x01(\tR\n" +
	"apiBaseUrl\x12*\n" +
	"\x11api_key_encrypted\x18\x06 \x01(\tR\x0fapiKeyEncrypted\x12\x16\n" +
	"\x06models\x18\a \x03(\tR\x06models\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12I\n" +
	"\n" +
	"model_maps\x18\n" +
	" \x03(\v2*.zgi.rpc.v1.OfficialChannel.ModelMapsEntryR\tmodelMaps\x12%\n" +
	"\x0eparam_override\x18\v \x01(\tR\rparamOverride\x12'\n" +
	"\x0fheader_override\x18\f \x01(\tR\x0eheaderOverride\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x12E\n" +
	"\bmetadata\x18\x0e \x03(\v2).zgi.rpc.v1.OfficialChannel.MetadataEntryR\bmetadata\x1a<\n" +
	"\x0eModelMapsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x14WatchChannelsRequest\x12!\n" +
	"\ffrom_version\x18\x01 \x01(\x03R\vfromVersion\"\x92\x02\n" +
	"\fChannelEvent\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".zgi.rpc.v1.ChannelEvent.EventTypeR\x04type\x125\n" +
	"\achannel\x18\x02 \x01(\v2\x1b.zgi.rpc.v1.OfficialChannelR\achannel\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"[\n" +
	"\tEventType\x12\f\n" +
	"\bSNAPSHOT\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\v\n" +
	"\aENABLED\x10\x04\x12\f\n" +
	"\bDISABLED\x10\x052\xca\x01\n" +
	"\x0eChannelService\x12i\n" +
	"\x14ListOfficialChannels\x12'.zgi.rpc.v1.ListOfficialChannelsRequest\x1a(.zgi.rpc.v1.ListOfficialChannelsResponse\x12M\n" +
	"\rWatchChannels\x12 .zgi.rpc.v1.WatchChannelsRequest\x1a\x18.zgi.rpc.v1.ChannelEvent0\x01B'Z%github.com/zgiai/zgi/api/pkg/rpc/v1;v1b\x06proto3"

var (
	file_pkg_rpc_v1_channel_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_channel_proto_rawDescData []byte
)

func file_pkg_rpc_v1_channel_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_channel_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_channel_proto_rawDesc), len(file_pkg_rpc_v1_channel_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_channel_proto_rawDescData
}

var file_pkg_rpc_v1_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_rpc_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_rpc_v1_channel_proto_goTypes = []any{
	(ChannelEvent_EventType)(0),          // 0: zgi.rpc.v1.ChannelEvent.EventType
	(*ListOfficialChannelsRequest)(nil),  // 1: zgi.rpc.v1.ListOfficialChannelsRequest
	(*ListOfficialChannelsResponse)(nil), // 2: zgi.rpc.v1.ListOfficialChannelsResponse
	(*OfficialChannel)(nil),              // 3: zgi.rpc.v1.OfficialChannel
	(*WatchChannelsRequest)(nil),         // 4: zgi.rpc.v1.WatchChannelsRequest
	(*ChannelEvent)(nil),                 // 5: zgi.rpc.v1.ChannelEvent
	nil,                                  // 6: zgi.rpc.v1.OfficialChannel.ModelMapsEntry
	nil,                                  // 7: zgi.rpc.v1.OfficialChannel.MetadataEntry
}
var file_pkg_rpc_v1_channel_proto_depIdxs = []int32{
	3, // 0: zgi.rpc.v1.ListOfficialChannelsResponse.channels:type_name -> zgi.rpc.v1.OfficialChannel
	6, // 1: zgi.rpc.v1.OfficialChannel.model_maps:type_name -> zgi.rpc.v1.OfficialChannel.ModelMapsEntry
	7, // 2: zgi.rpc.v1.OfficialChannel.metadata:type_name -> zgi.rpc.v1.OfficialChannel.MetadataEntry
	0, // 3: zgi.rpc.v1.ChannelEvent.type:type_name -> zgi.rpc.v1.ChannelEvent.EventType
	3, // 4: zgi.rpc.v1.ChannelEvent.channel:type_name -> zgi.rpc.v1.OfficialChannel
	1, // 5: zgi.rpc.v1.ChannelService.ListOfficialChannels:input_type -> zgi.rpc.v1.ListOfficialChannelsRequest
	4, // 6: zgi.rpc.v1.ChannelService.WatchChannels:input_type -> zgi.rpc.v1.WatchChannelsRequest
	2, // 7: zgi.rpc.v1.ChannelService.ListOfficialChannels:output_type -> zgi.rpc.v1.ListOfficialChannelsResponse
	5, // 8: zgi.rpc.v1.ChannelService.WatchChannels:output_type -> zgi.rpc.v1.ChannelEvent
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_channel_proto_init() }
func file_pkg_rpc_v1_channel_proto_init() {
	if File_pkg_rpc_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_channel_proto_rawDesc), len(file_pkg_rpc_v1_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_channel_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_channel_proto_depIdxs,
		EnumInfos:         file_pkg_rpc_v1_channel_proto_enumTypes,
		MessageInfos:      file_pkg_rpc_v1_channel_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_channel_proto = out.File
	file_pkg_rpc_v1_channel_proto_goTypes = nil
	file_pkg_rpc_v1_channel_proto_depIdxs = nil
}
