// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/rpc/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                  // Filter by provider (e.g., "openai", "anthropic")
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`                  // Filter by protocol (e.g., "openai", "anthropic")
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // Filter by active status
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                         // Page number (1-indexed)
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ListModelsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListModelsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListModelsRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Model ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelInfo             `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelResponse) GetModel() *ModelInfo {
	if x != nil {
		return x.Model
	}
	return nil
}

type SyncModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // Provider to sync (empty = all providers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncModelsRequest) Reset() {
	*x = SyncModelsRequest{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncModelsRequest) ProtoMessage() {}

func (x *SyncModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncModelsRequest.ProtoReflect.Descriptor instead.
func (*SyncModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *SyncModelsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type SyncModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	UpdatedCount  int32                  `protobuf:"varint,2,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncModelsResponse) Reset() {
	*x = SyncModelsResponse{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncModelsResponse) ProtoMessage() {}

func (x *SyncModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncModelsResponse.ProtoReflect.Descriptor instead.
func (*SyncModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *SyncModelsResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncModelsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *SyncModelsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SyncModelsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ModelInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelName            string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	DisplayName          string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Provider             string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Protocol             string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	UseCases             []string               `protobuf:"bytes,6,rep,name=use_cases,json=useCases,proto3" json:"use_cases,omitempty"`
	MaxTokens            int32                  `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxOutputTokens      int32                  `protobuf:"varint,8,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	SupportsStreaming    bool                   `protobuf:"varint,9,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsFunctionCall bool                   `protobuf:"varint,10,opt,name=supports_function_call,json=supportsFunctionCall,proto3" json:"supports_function_call,omitempty"`
	SupportsVision       bool                   `protobuf:"varint,11,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	IsActive             bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PricingInput         string                 `protobuf:"bytes,13,opt,name=pricing_input,json=pricingInput,proto3" json:"pricing_input,omitempty"`    // JSON string for pricing
	PricingOutput        string                 `protobuf:"bytes,14,opt,name=pricing_output,json=pricingOutput,proto3" json:"pricing_output,omitempty"` // JSON string for pricing
	Metadata             map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt            string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ModelInfo) GetUseCases() []string {
	if x != nil {
		return x.UseCases
	}
	return nil
}

func (x *ModelInfo) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelInfo) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ModelInfo) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *ModelInfo) GetSupportsFunctionCall() bool {
	if x != nil {
		return x.SupportsFunctionCall
	}
	return false
}

func (x *ModelInfo) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

func (x *ModelInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ModelInfo) GetPricingInput() string {
	if x != nil {
		return x.PricingInput
	}
	return ""
}

func (x *ModelInfo) GetPricingOutput() string {
	if x != nil {
		return x.PricingOutput
	}
	return ""
}

func (x *ModelInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ModelInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ModelInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_pkg_rpc_v1_model_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/rpc/v1/model.proto\x12\n" +
	"zgi.rpc.v1\"\x99\x01\n" +
	"\x11ListModelsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"Y\n" +
	"\x12ListModelsResponse\x12-\n" +
	"\x06models\x18\x01 \x03(\v2\x15.zgi.rpc.v1.ModelInfoR\x06models\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"!\n" +
	"\x0fGetModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x10GetModelResponse\x12+\n" +
	"\x05model\x18\x01 \x01(\v2\x15.zgi.rpc.v1.ModelInfoR\x05model\"/\n" +
	"\x11SyncModelsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\x97\x01\n" +
	"\x12SyncModelsResponse\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12#\n" +
	"\rupdated_count\x18\x02 \x01(\x05R\fupdatedCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\xb0\x05\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tuse_cases\x18\x06 \x03(\tR\buseCases\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\a \x01(\x05R\tmaxTokens\x12*\n" +
	"\x11max_output_tokens\x18\b \x01(\x05R\x0fmaxOutputTokens\x12-\n" +
	"\x12supports_streaming\x18\t \x01(\bR\x11supportsStreaming\x124\n" +
	"\x16supports_function_call\x18\n" +
	" \x01(\bR\x14supportsFunctionCall\x12'\n" +
	"\x0fsupports_vision\x18\v \x01(\bR\x0esupportsVision\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12#\n" +
	"\rpricing_input\x18\r \x01(\tR\fpricingInput\x12%\n" +
	"\x0epricing_output\x18\x0e \x01(\tR\rpricingOutput\x12?\n" +
	"\bmetadata\x18\x0f \x03(\v2#.zgi.rpc.v1.ModelInfo.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xef\x01\n" +
	"\fModelService\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.zgi.rpc.v1.ListModelsRequest\x1a\x1e.zgi.rpc.v1.ListModelsResponse\x12E\n" +
	"\bGetModel\x12\x1b.zgi.rpc.v1.GetModelRequest\x1a\x1c.zgi.rpc.v1.GetModelResponse\x12K\n" +
	"\n" +
	"SyncModels\x12\x1d.zgi.rpc.v1.SyncModelsRequest\x1a\x1e.zgi.rpc.v1.SyncModelsResponseB'Z%github.com/zgiai/ginext/pkg/rpc/v1;v1b\x06proto3"

var (
	file_pkg_rpc_v1_model_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_model_proto_rawDescData []byte
)

func file_pkg_rpc_v1_model_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_model_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_model_proto_rawDesc), len(file_pkg_rpc_v1_model_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_model_proto_rawDescData
}

var file_pkg_rpc_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_rpc_v1_model_proto_goTypes = []any{
	(*ListModelsRequest)(nil),  // 0: zgi.rpc.v1.ListModelsRequest
	(*ListModelsResponse)(nil), // 1: zgi.rpc.v1.ListModelsResponse
	(*GetModelRequest)(nil),    // 2: zgi.rpc.v1.GetModelRequest
	(*GetModelResponse)(nil),   // 3: zgi.rpc.v1.GetModelResponse
	(*SyncModelsRequest)(nil),  // 4: zgi.rpc.v1.SyncModelsRequest
	(*SyncModelsResponse)(nil), // 5: zgi.rpc.v1.SyncModelsResponse
	(*ModelInfo)(nil),          // 6: zgi.rpc.v1.ModelInfo
	nil,                        // 7: zgi.rpc.v1.ModelInfo.MetadataEntry
}
var file_pkg_rpc_v1_model_proto_depIdxs = []int32{
	6, // 0: zgi.rpc.v1.ListModelsResponse.models:type_name -> zgi.rpc.v1.ModelInfo
	6, // 1: zgi.rpc.v1.GetModelResponse.model:type_name -> zgi.rpc.v1.ModelInfo
	7, // 2: zgi.rpc.v1.ModelInfo.metadata:type_name -> zgi.rpc.v1.ModelInfo.MetadataEntry
	0, // 3: zgi.rpc.v1.ModelService.ListModels:input_type -> zgi.rpc.v1.ListModelsRequest
	2, // 4: zgi.rpc.v1.ModelService.GetModel:input_type -> zgi.rpc.v1.GetModelRequest
	4, // 5: zgi.rpc.v1.ModelService.SyncModels:input_type -> zgi.rpc.v1.SyncModelsRequest
	1, // 6: zgi.rpc.v1.ModelService.ListModels:output_type -> zgi.rpc.v1.ListModelsResponse
	3, // 7: zgi.rpc.v1.ModelService.GetModel:output_type -> zgi.rpc.v1.GetModelResponse
	5, // 8: zgi.rpc.v1.ModelService.SyncModels:output_type -> zgi.rpc.v1.SyncModelsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_model_proto_init() }
func file_pkg_rpc_v1_model_proto_init() {
	if File_pkg_rpc_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_model_proto_rawDesc), len(file_pkg_rpc_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_model_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_model_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_model_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_model_proto = out.File
	file_pkg_rpc_v1_model_proto_goTypes = nil
	file_pkg_rpc_v1_model_proto_depIdxs = nil
}
