// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/rpc/v1/provider.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProvidersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"` // Include inactive providers
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ListProvidersRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Provider code (e.g., "openai", "anthropic")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *GetProviderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderInfo          `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *GetProviderResponse) GetProvider() *ProviderInfo {
	if x != nil {
		return x.Provider
	}
	return nil
}

type DetectProtocolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectProtocolsRequest) Reset() {
	*x = DetectProtocolsRequest{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectProtocolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectProtocolsRequest) ProtoMessage() {}

func (x *DetectProtocolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectProtocolsRequest.ProtoReflect.Descriptor instead.
func (*DetectProtocolsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *DetectProtocolsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DetectProtocolsRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *DetectProtocolsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type DetectProtocolsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportedProtocols  []string               `protobuf:"bytes,1,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	RecommendedProtocol string                 `protobuf:"bytes,2,opt,name=recommended_protocol,json=recommendedProtocol,proto3" json:"recommended_protocol,omitempty"`
	DetectionResults    map[string]string      `protobuf:"bytes,3,rep,name=detection_results,json=detectionResults,proto3" json:"detection_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DetectProtocolsResponse) Reset() {
	*x = DetectProtocolsResponse{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectProtocolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectProtocolsResponse) ProtoMessage() {}

func (x *DetectProtocolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectProtocolsResponse.ProtoReflect.Descriptor instead.
func (*DetectProtocolsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *DetectProtocolsResponse) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *DetectProtocolsResponse) GetRecommendedProtocol() string {
	if x != nil {
		return x.RecommendedProtocol
	}
	return ""
}

func (x *DetectProtocolsResponse) GetDetectionResults() map[string]string {
	if x != nil {
		return x.DetectionResults
	}
	return nil
}

type ProviderInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Code               string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SupportedProtocols []string               `protobuf:"bytes,4,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	DefaultProtocol    string                 `protobuf:"bytes,5,opt,name=default_protocol,json=defaultProtocol,proto3" json:"default_protocol,omitempty"`
	Website            string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	LogoUrl            string                 `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	IsActive           bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderInfo) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *ProviderInfo) GetDefaultProtocol() string {
	if x != nil {
		return x.DefaultProtocol
	}
	return ""
}

func (x *ProviderInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ProviderInfo) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ProviderInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProviderInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_rpc_v1_provider_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/rpc/v1/provider.proto\x12\n" +
	"zgi.rpc.v1\"A\n" +
	"\x14ListProvidersRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\"O\n" +
	"\x15ListProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.zgi.rpc.v1.ProviderInfoR\tproviders\"(\n" +
	"\x12GetProviderRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"K\n" +
	"\x13GetProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.zgi.rpc.v1.ProviderInfoR\bprovider\"h\n" +
	"\x16DetectProtocolsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"\xaa\x02\n" +
	"\x17DetectProtocolsResponse\x12/\n" +
	"\x13supported_protocols\x18\x01 \x03(\tR\x12supportedProtocols\x121\n" +
	"\x14recommended_protocol\x18\x02 \x01(\tR\x13recommendedProtocol\x12f\n" +
	"\x11detection_results\x18\x03 \x03(\v29.zgi.rpc.v1.DetectProtocolsResponse.DetectionResultsEntryR\x10detectionResults\x1aC\n" +
	"\x15DetectionResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x03\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x13supported_protocols\x18\x04 \x03(\tR\x12supportedProtocols\x12)\n" +
	"\x10default_protocol\x18\x05 \x01(\tR\x0fdefaultProtocol\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x19\n" +
	"\blogo_url\x18\a \x01(\tR\alogoUrl\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12B\n" +
	"\bmetadata\x18\t \x03(\v2&.zgi.rpc.v1.ProviderInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x93\x02\n" +
	"\x0fProviderService\x12T\n" +
	"\rListProviders\x12 .zgi.rpc.v1.ListProvidersRequest\x1a!.zgi.rpc.v1.ListProvidersResponse\x12N\n" +
	"\vGetProvider\x12\x1e.zgi.rpc.v1.GetProviderRequest\x1a\x1f.zgi.rpc.v1.GetProviderResponse\x12Z\n" +
	"\x0fDetectProtocols\x12\".zgi.rpc.v1.DetectProtocolsRequest\x1a#.zgi.rpc.v1.DetectProtocolsResponseB'Z%github.com/zgiai/zgi/api/pkg/rpc/v1;v1b\x06proto3"

var (
	file_pkg_rpc_v1_provider_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_provider_proto_rawDescData []byte
)

func file_pkg_rpc_v1_provider_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_provider_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_provider_proto_rawDesc), len(file_pkg_rpc_v1_provider_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_provider_proto_rawDescData
}

var file_pkg_rpc_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_rpc_v1_provider_proto_goTypes = []any{
	(*ListProvidersRequest)(nil),    // 0: zgi.rpc.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),   // 1: zgi.rpc.v1.ListProvidersResponse
	(*GetProviderRequest)(nil),      // 2: zgi.rpc.v1.GetProviderRequest
	(*GetProviderResponse)(nil),     // 3: zgi.rpc.v1.GetProviderResponse
	(*DetectProtocolsRequest)(nil),  // 4: zgi.rpc.v1.DetectProtocolsRequest
	(*DetectProtocolsResponse)(nil), // 5: zgi.rpc.v1.DetectProtocolsResponse
	(*ProviderInfo)(nil),            // 6: zgi.rpc.v1.ProviderInfo
	nil,                             // 7: zgi.rpc.v1.DetectProtocolsResponse.DetectionResultsEntry
	nil,                             // 8: zgi.rpc.v1.ProviderInfo.MetadataEntry
}
var file_pkg_rpc_v1_provider_proto_depIdxs = []int32{
	6, // 0: zgi.rpc.v1.ListProvidersResponse.providers:type_name -> zgi.rpc.v1.ProviderInfo
	6, // 1: zgi.rpc.v1.GetProviderResponse.provider:type_name -> zgi.rpc.v1.ProviderInfo
	7, // 2: zgi.rpc.v1.DetectProtocolsResponse.detection_results:type_name -> zgi.rpc.v1.DetectProtocolsResponse.DetectionResultsEntry
	8, // 3: zgi.rpc.v1.ProviderInfo.metadata:type_name -> zgi.rpc.v1.ProviderInfo.MetadataEntry
	0, // 4: zgi.rpc.v1.ProviderService.ListProviders:input_type -> zgi.rpc.v1.ListProvidersRequest
	2, // 5: zgi.rpc.v1.ProviderService.GetProvider:input_type -> zgi.rpc.v1.GetProviderRequest
	4, // 6: zgi.rpc.v1.ProviderService.DetectProtocols:input_type -> zgi.rpc.v1.DetectProtocolsRequest
	1, // 7: zgi.rpc.v1.ProviderService.ListProviders:output_type -> zgi.rpc.v1.ListProvidersResponse
	3, // 8: zgi.rpc.v1.ProviderService.GetProvider:output_type -> zgi.rpc.v1.GetProviderResponse
	5, // 9: zgi.rpc.v1.ProviderService.DetectProtocols:output_type -> zgi.rpc.v1.DetectProtocolsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_provider_proto_init() }
func file_pkg_rpc_v1_provider_proto_init() {
	if File_pkg_rpc_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_provider_proto_rawDesc), len(file_pkg_rpc_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_provider_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_provider_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_provider_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_provider_proto = out.File
	file_pkg_rpc_v1_provider_proto_goTypes = nil
	file_pkg_rpc_v1_provider_proto_depIdxs = nil
}
